stack_using_two_queues
TheAlgorithms/Python pull request #10002
Opened 2023-10-07 09:37 UTC by IndranjanaChatterjee

### Describe your change:

Added the code for the implementation of stack using two queues

Fixes:#9987

* [x] Add an algorithm?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-10-08 09:30 UTC, cclauss requested changes
Looks cool...

2023-10-08 09:30 UTC, cclauss commented on data_structures/stacks/stack_with_two_queues.py
> +        self.insert_queue.append(item)  # Add items into the Queue
The code already says what the comment repeats.
```suggestion
        self.insert_queue.append(item)
```

2023-10-08 09:30 UTC, cclauss commented on data_structures/stacks/stack_with_two_queues.py
> +            )  # Popping the elements
Let's not wrap lines just to make room for a comment.
```suggestion
            # Popping the elements
            self.insert_queue.append(self.suffle_queue.popleft())
```

2023-10-08 09:30 UTC, cclauss commented on data_structures/stacks/stack_with_two_queues.py
> +        if not (self.suffle_queue):  # if the stack  is empty
```suggestion
        if not self.suffle_queue:  # if the stack  is empty
```

2023-10-08 09:30 UTC, cclauss commented on data_structures/stacks/stack_with_two_queues.py
> +        return len(self.suffle_queue)
These `magic methods` will allow us to just `print(stack)` and `len(stack)`.
```suggestion
    def __str__(self) -> str:
        return tuple(self.suffle_queue)

    def __len__(self) -> int:
        return len(self.suffle_queue)
```

2023-10-08 09:30 UTC, cclauss commented on data_structures/stacks/stack_with_two_queues.py
> +    s = Stack()  # Creating a stack in S
Single-letter variable names makes code look like it was written in the 1970's.
```suggestion
    stack = Stack()  # Create a empty stack
```

2023-10-08 09:31 UTC, cclauss commented on data_structures/stacks/stack_with_two_queues.py
> +        self.suffle_queue = deque()  # Second Queue to be used for suffling
OPTIONAL: Should `Stack` be a dataclass?

2023-10-08 13:18 UTC, IndranjanaChatterjee commented
@cclauss I have tried to make the required changes in the PR #10109 . Please review. Apologies for the inconveniences caused.

2023-10-15 16:43 UTC, cclauss commented
Fixed in data_structures/stacks/stack_using_two_queues.py

2023-10-15 16:43 UTC, closed without merging