add tests for enigma_machine
TheAlgorithms/Python pull request #10017
Opened 2023-10-07 14:23 UTC by gabriellypinto

### Describe your change:

Related to https://github.com/TheAlgorithms/Python/issues/9943

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-10-22 19:19 UTC, tianyizheng02 requested changes, later dismissed

2023-10-22 19:19 UTC, tianyizheng02 commented on hashes/enigma_machine.py
> +def menu():
This code chunk is all driver code, so it's fine to keep it in the `__main__` block.

2023-10-22 19:19 UTC, tianyizheng02 commented on hashes/enigma_machine.py
> +def encode_or_decode(message, token):
Isn't this just the body of the driver code? Why is it not used in the driver code?

Also, please add type hints

2026-09-21 10:51 UTC, cclauss approved these changes

2026-09-21 10:51 UTC, cclauss approved these changes

2026-09-21 10:53 UTC, cclauss commented on hashes/enigma_machine.py
> +    doctest.testmod()
```suggestion
    doctest.testmod()
    menu()
```

2026-09-21 10:54 UTC, cclauss approved these changes

2026-09-21 10:54 UTC, merged