Added Lens formulae to the Physics repository
TheAlgorithms/Python pull request #10187
Opened 2023-10-09 15:51 UTC by san-jay-14

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-10-10 02:05 UTC, san-jay-14 commented on physics/lens_formulae.py
> +def image_distance(focal_length_of_lens: float, object_distance_from_lens: float):
Sorry, I will review and resolve in few hours.

2023-10-10 02:47 UTC, san-jay-14 commented
I have Resolved all the issues commented in my code. Kindly go through my code and if any issues found comment them  and I'll look into it and try to resolve as soon as possible.

2023-10-12 03:39 UTC, san-jay-14 commented
@cclauss Can you please take a look into my PR.
Thank you in advance 🙂

2023-10-19 16:02 UTC, tianyizheng02 requested changes
Please remove the indentation in the header docstring so that there's more space for text

2023-10-26 07:58 UTC, tianyizheng02 approved these changes

2023-10-26 07:58 UTC, merged