Adding avg and mps speed formulae for ideal gases
TheAlgorithms/Python pull request #10229
Opened 2023-10-10 14:21 UTC by Baron105

### Describe your change:

Added functions to calculate the average and most probable speeds of molecules in a gas given the temperature and molar mass of the gas. Also added a few doctests for testing.

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-10-12 15:40 UTC, tianyizheng02 requested changes

2023-10-12 16:34 UTC, Baron105 commented
Incorporated all the suggestions in the file. Please check @tianyizheng02. Thank you for the detailed review.

2023-10-12 16:41 UTC, tianyizheng02 requested changes

2023-10-12 16:41 UTC, tianyizheng02 commented on physics/speeds_of_gas_molecules.py
> +        ---------------------
```suggestion
        ---------------------
        | vavg = √(8RT/πM)  |
        ---------------------
```
For clarity

2023-10-12 16:41 UTC, tianyizheng02 commented on physics/speeds_of_gas_molecules.py
> +        ---------------------
```suggestion
        ---------------------
        | vmp = √(2RT/M)    |
        ---------------------
```

2023-10-12 16:41 UTC, tianyizheng02 commented on physics/speeds_of_gas_molecules.py
> +        ---------------------
```suggestion
        ---------------------
        | vrms = √(3RT/M)   |
        ---------------------
```

2023-10-12 16:41 UTC, tianyizheng02 commented on physics/speeds_of_gas_molecules.py
> +The root-mean-square speed is another measure of the average speed
No function for the RMS speed?

2023-10-12 16:41 UTC, tianyizheng02 commented on physics/speeds_of_gas_molecules.py
> +in a gas.
```suggestion
The root-mean-square, average and most probable speeds of gas molecules
are derived from the Maxwell-Boltzmann distribution. The Maxwell-Boltzmann
distribution is a probability distribution that describes the distribution of
speeds of particles in an ideal gas.
```
A few minor additions for clarity

2023-10-13 16:47 UTC, Baron105 commented
@tianyizheng02 please check if the current file is ok

2023-10-14 06:59 UTC, tianyizheng02 approved these changes

2023-10-14 07:01 UTC, tianyizheng02 commented
> I did not add the rms function as there is already a file that defines the function ie physics/rms_speed_of_molecule.py as that would be repeating the function. Should I add it here for a complete comparison of all three speeds?

No need, I forgot that we already had a file for the RMS speed. However, it'd make more sense in my opinion to move the existing RMS speed code into your code file since they're all about gas molecule speeds—that could be work for a later PR.

2023-10-14 07:01 UTC, merged

2023-10-14 07:01 UTC, tianyizheng02 commented
Thanks for your contribution!

2023-10-14 08:25 UTC, Baron105 commented
> Thanks for your contribution!

Glad to contribute! Thank you for taking time to review the file and giving great advice!