Add perfect cube binary search
TheAlgorithms/Python pull request #10477
Opened 2023-10-15 02:43 UTC by CouldNot

### Describe your change:

This pull request adds a new algorithm within the existing perfect_cube.py file, including a doctest. While similar files such as perfect_square.py have added an improved time complexity binary search algorithm, perfect_cube.py lacks another faster algorithm that can be used as an alternative. This PR aims to bring the set of algorithms up to standard (such as perfect_square.py) with a new binary search implementation.

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-10-16 00:34 UTC, tianyizheng02 requested changes
Could you modify your algorithm to support negative numbers? For instance, -27 = (-3)^3

2023-10-17 03:26 UTC, CouldNot commented
Hi, thanks for the reply - I've made the changes, let me know if everything's OK now. To add support for negative perfect cubes to the other non binary search algorithm in the same file, I can open another PR.

2023-10-17 07:30 UTC, tianyizheng02 requested changes

2023-10-17 07:30 UTC, tianyizheng02 commented on maths/perfect_cube.py
> +    TypeError: '<=' not supported between instances of 'int' and 'str'
Please add your own TypeError check for invalid inputs like this rather than relying on the built-in error message for `<=`

2023-10-18 04:10 UTC, CouldNot commented
A TypeError check was added, thanks for the reply.

2023-10-23 05:52 UTC, tianyizheng02 approved these changes

2023-10-23 05:53 UTC, tianyizheng02 commented
```
=========================== short test summary info ============================
FAILED web_programming/fetch_anime_and_play.py::web_programming.fetch_anime_and_play.search_anime_episode_list
============= 1 failed, 1669 passed, 1 warning in 95.85s (0:01:35) =============
```
Ugh, not this file again...

2023-10-23 05:56 UTC, merged

2023-10-23 05:57 UTC, tianyizheng02 commented
Thanks for your contribution!