Sorts : Added Block Sort Algorithm
TheAlgorithms/Python pull request #10490
Opened 2023-10-15 06:36 UTC by SportingDot1024

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-10-15 06:42 UTC, Aditya-K-Pathak approved these changes

2023-10-15 06:51 UTC, SportingDot1024 commented on sorts/block_sort.py
> +        min_block = min(blocks, key=lambda x: x[0])
done

2023-10-15 07:45 UTC, Aditya-K-Pathak approved these changes
Add Comments for understanding if possible, else it's fine

2023-10-15 08:07 UTC, Aditya-K-Pathak requested changes
Line 1: use list instead of List
Line 41 is too long, break it from comma and use a full stop their and start the rest in new line with caps
Line 45 return sorted result, you are storing result in sorted_result not in sorted_lst

2023-10-15 08:07 UTC, SportingDot1024 commented
I have added comments.

2023-10-15 08:08 UTC, SportingDot1024 commented
All the checks have been passed.

2023-10-17 16:43 UTC, SportingDot1024 commented
#10490

2023-10-20 18:38 UTC, closed without merging