Adds hinge loss function algorithm
TheAlgorithms/Python pull request #10628
Opened 2023-10-17 02:55 UTC by PoojanSmart

### Describe your change:

- Adding Hinge loss function which is useful loss function in Support Vector Machine (SVM) for calculating loss.

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-10-17 06:45 UTC, tianyizheng02 requested changes

2023-10-17 06:45 UTC, tianyizheng02 commented on machine_learning/loss_functions/hinge_loss.py
> +        y_true: Array of actual values (ground truth) encoded as -1 and 1.
Please have an if-statement enforce that `y_true` must be encoded as -1 or 1 (and please raise a ValueError for invalid inputs)

2023-10-17 06:45 UTC, tianyizheng02 commented on machine_learning/loss_functions/hinge_loss.py
> +        Hinge loss
```suggestion
    Returns:
        The hinge loss between y_true and y_pred
```

2023-10-17 06:45 UTC, tianyizheng02 commented on machine_learning/loss_functions/hinge_loss.py
> +    Calculate the hinge loss for y_true and pred for binary classification.
```suggestion
    Calculate the mean hinge loss for y_true and pred for binary classification.
```
The documentation should reflect the fact that you're averaging the hinge losses over the arrays

2023-10-17 06:45 UTC, tianyizheng02 commented on machine_learning/loss_functions/hinge_loss.py
> +    intermidiate_result[intermidiate_result < 0] = 0
```suggestion
    hinge_losses = np.max(0, 1 - y_true * y_pred)
```
More descriptive variable name, and you can just use `np.max`

2023-10-17 06:45 UTC, tianyizheng02 commented on machine_learning/loss_functions/hinge_loss.py
> +    return loss
```suggestion
    return np.mean(hinge_losses)
```

2023-10-17 15:40 UTC, cclauss commented
https://github.com/TheAlgorithms/Python/pull/10637#issuecomment-1766252341 also applies here.

2023-10-17 15:58 UTC, PoojanSmart commented
> [#10637 (comment)](https://github.com/TheAlgorithms/Python/pull/10637#issuecomment-1766252341) also applies here.

I can combine all loss function into single file, then you can review. We will do further modularization if required based on loss function category.
But before that, Is it fine if you merge this one? 
I will raise new issue and PR to compile all loss functions.

Let me know your thoughts..

2023-10-17 18:39 UTC, tianyizheng02 requested changes

2023-10-17 18:39 UTC, tianyizheng02 commented on machine_learning/loss_functions/hinge_loss.py
> +    if np.array_equal(np.sort(np.unique(y_true)), np.array([-1, 1])) is False:
```suggestion
    if np.any((y_true != 1) & (y_true != -1)):
```
This should do the same thing (check if any entry is neither 1 or -1)

2023-10-18 14:09 UTC, tianyizheng02 approved these changes

2023-10-18 14:09 UTC, merged