Update CONTRIBUTING.md
TheAlgorithms/Python pull request #10660
Opened 2023-10-18 02:38 UTC by Camelpilot33

### Describe your change:

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Documentation change? -> Grammar and spelling change on CONTRIBUTING.md

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
 - This part is not applicable:
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-10-18 04:27 UTC, imSanko approved these changes
Improved grammers ??

2023-10-18 07:18 UTC, jazelly commented on CONTRIBUTING.md
> +* Perform some internal calculations or data manipulations,
I think this should be lower cased as it's following a comma

2023-10-18 07:18 UTC, jazelly commented on CONTRIBUTING.md
> +Welcome to [TheAlgorithms/Python](https://github.com/TheAlgorithms/Python)! Before sending your pull requests, make sure that you __read the whole guidelines__. If you have any doubt about the contri
"on" sounds correct to me

2023-10-18 14:05 UTC, tianyizheng02 requested changes
Most of these changes correct "mistakes" that aren't actually incorrect, so please change them

2023-10-18 14:05 UTC, tianyizheng02 commented on CONTRIBUTING.md
> +- [__List comprehensions and generators__](https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions) are preferred over the use of `lambda`, `map`, `filter`, and `reduce` but the im
```suggestion
- [__List comprehensions and generators__](https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions) are preferred over the use of `lambda`, `map`, `filter`, `reduce`, etc. but the important thing is to demonstrate the power of Python in code that is easy to read and maintain.
```

2023-10-18 14:05 UTC, tianyizheng02 commented on CONTRIBUTING.md
> +- Strictly use snake_case (underscore_separated) in your file_name, as it will be easy to parse in the future using scripts.
British English makes a distinction between "in the future" and "in future"

2024-06-01 09:30 UTC, tianyizheng02 commented
Closing this PR because
1. OP hasn't responded in over 6 months, so the PR may as well be stale
2. Almost all of the "fixes" were unnecessary, as most changes didn't fix any real mistakes

2024-06-01 09:30 UTC, closed without merging