added runge-kutta-gills method to python/maths
TheAlgorithms/Python pull request #10682
Opened 2023-10-18 18:48 UTC by iamrknain

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-10-18 22:35 UTC, cclauss commented on maths/runge_kutta_gills.py
> +Author : Ravi Kumar
```suggestion
https://en.wikipedia.org/wiki/Runge%E2%80%93Kutta_methods
Author : Ravi Kumar
```

2023-10-18 22:43 UTC, cclauss commented
I wonder:
1. Should these go into the arithmatic_analysis directory instead of the generic `math` directory?
2. Should the `arithmatic_analysis` directory be renamed to `numerical_analysis`?
    *https://en.wikipedia.org/wiki/Numerical_analysis
3 Should we combine this and two existing Runge-Kutta algorithms so visitors can easily study them together?

2023-10-18 22:46 UTC, cclauss commented on maths/runge_kutta_gills.py
> +from math import sqrt
```suggestion

from collections.abc import Callable
from math import sqrt

import numpy as np
```

2023-10-22 16:33 UTC, tianyizheng02 requested changes

2023-10-22 16:33 UTC, tianyizheng02 commented on maths/runge_kutta_gills.py
> +    func: Callable,
```suggestion
    func: Callable[[float, float], float],
```
Please annotate the parameter and output types

2023-10-22 16:33 UTC, tianyizheng02 commented on maths/runge_kutta_gills.py
> +    )
Why not this?
```suggestion
    y = np.zeros(n + 1)
```

Also, is there a reason why you're using a numpy array as opposed to a built-in Python list?

2023-10-22 16:33 UTC, tianyizheng02 commented on maths/runge_kutta_gills.py
> +    for i in range(n):
Could you have this for-loop iterate directly over x values instead?
```suggestion
    for x in range(x_initial, x_final, step_size):
```
Or something along those lines. That way you don't need to manually increment x, nor do you need store the x values in a list.

2023-10-25 06:56 UTC, closed without merging