add exponential search algorithm
TheAlgorithms/Python pull request #10732
Opened 2023-10-20 19:01 UTC by kiarash8112

### Describe your change:

added exponential algorithm using binary_search_recursion also tests and docs about it

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-10-21 06:10 UTC, cclauss requested changes
Nice addition!

For optional extra credit, add a `timeit` benchmark to show relative performance.

2023-10-21 06:10 UTC, cclauss commented on searches/binary_search.py
> +
```suggestion
    >>> exponential_search([0, 5, 7, 10, 15], 0)
    0
    >>> exponential_search([0, 5, 7, 10, 15], 15)
    4
    >>> exponential_search([0, 5, 7, 10, 15], 5)
    1
    >>> exponential_search([0, 5, 7, 10, 15], 6) = None
    True
```

2023-10-21 06:10 UTC, cclauss commented on searches/binary_search.py
> +def exponential_search(sorted_collection: list[int], item: int) -> int | None:
I am not a fan of functions that return multiple datatypes.  If the search fails, let's return `-1` (like `"Hello".find("Z")`) or raise a `ValueError` (like `"Hello".index("Z")`).
```suggestion
def exponential_search(sorted_collection: list[int], item: int) -> int:
```

2023-10-21 06:10 UTC, cclauss commented on searches/binary_search.py
>  if __name__ == "__main__":
Only one of these.  Run the tests first and let the user interact afterward.
```suggestion
```

2023-10-21 07:19 UTC, cclauss commented on searches/binary_search.py
> +    left = int(bound / 2)
```suggestion
    left = bound // 2
```

2023-10-21 07:23 UTC, cclauss commented on searches/binary_search.py
> +    True
```suggestion
    >>> exponential_search([0, 5, 7, 10, 15], 6)
    -1
```

2023-10-21 08:14 UTC, cclauss commented
I thought more about sorting the sorted collection… it is a bad idea.  The second item in might be different in the two lists so the function might tell me that is the second item when in my list it is the third item.  So, the implementations should raise ValueError on unsorted input.

2023-10-21 18:53 UTC, cclauss approved these changes
This is a really slick addition.  Thanks for doing it!

2023-10-21 18:53 UTC, merged

2023-10-21 18:58 UTC, kiarash8112 commented
@cclauss  thank you for your suggestions :)

2023-10-25 23:16 UTC, tianyizheng02 commented
@cclauss Since exponential search is a different algorithm from binary search, why was it placed in the `binary_search.py` file? Shouldn't it have gotten its own file?

2023-10-26 08:33 UTC, cclauss commented on searches/binary_search.py
> +    last_result = binary_search_by_recursion(
@tianyizheng02 `exponential_search()` embeds a call to `binary_search_by_recursion()` but as the benchmarks demonstrate delivers a faster result.  Looking at the first commit makes this clearer.