Create DDA_line_drawing.py
TheAlgorithms/Python pull request #10929
Opened 2023-10-25 03:07 UTC by nababuddin

### Describe your change:

* [X] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [X] This pull request is all my own work -- I have not plagiarized.
* [X] I know that pull requests will not be merged if they fail the automated tests.
* [X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [X] All new Python files are placed inside an existing directory.
* [X] All filenames are in all lowercase characters with no spaces or dashes.
* [X] All functions and variable names follow Python naming conventions.
* [X] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [X] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [X] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [X] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-10-26 15:35 UTC, tianyizheng02 requested changes

2023-10-26 15:35 UTC, tianyizheng02 commented on graphics/DDA_line_drawing.py
1. Please do not abbreviate "digital differential analyzer", as it's not clear to readers who aren't already familiar with the algorithm.
2. The file name should be in all-lowercase.

2023-10-26 16:49 UTC, nababuddin reviewed
Thanks for the suggestion, made the changes

2023-10-26 17:01 UTC, nababuddin reviewed
made the necessary changes

2023-10-26 22:07 UTC, tianyizheng02 requested changes

2023-10-26 22:07 UTC, tianyizheng02 commented on graphics/digital_differential_analyzer_line_drawing.py
> +def dda_line(x1, y1, x2, y2):
1. Like I said earlier, please do not abbreviate "digital differential analyzer".
2. Like the algorithm-keeper bot said, please add type hints and doctests.

2023-10-27 05:30 UTC, nababuddin reviewed
check I made the changes

2023-10-27 05:38 UTC, nababuddin reviewed
I made the changes.

2023-10-27 14:56 UTC, tianyizheng02 commented on graphics/digital_differential_analyzer_line_drawing.py
> +from typing import list, tuple
```suggestion
```
You don't need to import the types, they're already built into Python

2023-10-27 14:57 UTC, tianyizheng02 commented on graphics/digital_differential_analyzer_line_drawing.py
> +        and the second list contains the y-coordinates.
Instead of having separate lists for the x- and y-coordinates, could you have the algorithm just return a list of coordinate pairs?

2023-10-27 14:58 UTC, tianyizheng02 requested changes

2023-10-27 14:58 UTC, tianyizheng02 commented on graphics/digital_differential_analyzer_line_drawing.py
Let's name the file `digital_differential_analyzer_line.py` to try to keep it short

2023-10-28 01:33 UTC, nababuddin reviewed
I have made the changes you requested.

2023-10-28 06:57 UTC, nababuddin reviewed
I think its  all fixed now and ready to merge.

2024-12-31 02:09 UTC, tianyizheng02 approved these changes

2024-12-31 02:09 UTC, merged