Add error tests in doctest and fix error message
TheAlgorithms/Python pull request #10930
Opened 2023-10-25 03:20 UTC by CouldNot

### Describe your change:

Despite is_prime() already having an error message for invalid inputs, the doctest doesn't include any tests displaying invalid inputs. This PR adds two examples which cover this and also rephrases the error message for more consistent grammar.

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-10-25 20:18 UTC, tianyizheng02 requested changes

2023-10-25 20:18 UTC, tianyizheng02 commented on maths/prime_check.py
> +    ), "is_prime() only accepts positive integers"
Could you change this `assert` to a `ValueError` instead?

2023-10-26 01:15 UTC, CouldNot commented
Done, take another look!

2023-10-26 05:27 UTC, tianyizheng02 approved these changes

2023-10-26 05:27 UTC, merged