Added adams-bashforth method of order 2, 3, 4, 5
TheAlgorithms/Python pull request #10969
Opened 2023-10-25 20:29 UTC by ravi-ivar-7

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-10-26 07:26 UTC, tianyizheng02 commented
This PR also has the `runge_kitta_gills.py` file from your other PR, #10967, which has already been merged. Please remove this extraneous file.

2023-10-27 21:07 UTC, cclauss requested changes

2023-10-27 21:07 UTC, cclauss commented on maths/numerical_analysis/adams_bashforth.py
> +    ):
```suggestion
    ) -> None:
```
Or should this be a https://docs.python.org/3/library/dataclasses.html instead?

2023-10-27 21:07 UTC, cclauss commented on maths/numerical_analysis/adams_bashforth.py
> +    """
This needs to move up just after the function signature.

2023-10-27 21:07 UTC, cclauss commented on maths/numerical_analysis/adams_bashforth.py
> +    >>> y
```suggestion
    >>> AdamsBashforth(f, [0, 0.2], [0, 0], 0.2, 1).step_2()
```

2023-10-27 21:07 UTC, cclauss commented on maths/numerical_analysis/adams_bashforth.py
> +    >>> y = AdamsBashforth(f, [0, 0.2, 1], [0, 0, 0.04], 0.2, 1).step_3()
```suggestion
    >>> AdamsBashforth(f, [0, 0.2, 1], [0, 0, 0.04], 0.2, 1).step_3()
```

2023-10-27 21:07 UTC, cclauss commented on maths/numerical_analysis/adams_bashforth.py
> +    >>> y = AdamsBashforth(f, [0, 0.2, 0.3], [0, 0, 0.04], 0.2, 1).step_3()
```suggestion
    >>> AdamsBashforth(f, [0, 0.2, 0.3], [0, 0, 0.04], 0.2, 1).step_3()
```

2023-10-27 21:07 UTC, cclauss commented on maths/numerical_analysis/adams_bashforth.py
> +    >>> y = AdamsBashforth(f,[0,0.2,0.4,0.6,0.8],[0,0,0.04,0.128 0.307],-0.2,1).step_5()
```suggestion
    >>> AdamsBashforth(f,[0,0.2,0.4,0.6,0.8],[0,0,0.04,0.128 0.307],-0.2,1).step_5()
```

2023-10-27 21:07 UTC, cclauss commented on maths/numerical_analysis/adams_bashforth.py
> +    >>> y = AdamsBashforth(f, [0, 0.2, 0.4], [0, 0, 0.04], 0.2, 1).step_2()
```suggestion
    >>> AdamsBashforth(f, [0, 0.2, 0.4], [0, 0, 0.04], 0.2, 1).step_2()
```

2023-10-27 21:07 UTC, cclauss commented on maths/numerical_analysis/adams_bashforth.py
> +    def step_2(self) -> np.ndarray:
Please add doctests to each method.

2023-10-28 22:12 UTC, cclauss approved these changes
Let's do this!!

2023-10-28 22:12 UTC, merged