Add automatic differentiation algorithm
TheAlgorithms/Python pull request #10977
Opened 2023-10-26 02:21 UTC by PoojanSmart

### Describe your change:

- Adding implementation of automatic differentiation algorithm which is useful for calculating gradients automatically. This algorithm is widely used in machine learning and deep learning models for optimization. 

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-10-26 02:45 UTC, imSanko reviewed
Have you checked with `Pre --commits`

2023-10-26 04:12 UTC, PoojanSmart commented
I am getting conflicting suggestions from mypy and ruff:

From mypy:
```
machine_learning\automatic_differentiation.py:45: error: Module "typing" has no attribute "Self"  [attr-defined]
machine_learning\automatic_differentiation.py:45: note: Use `from typing_extensions import Self` instead
```
And If I change typing to typing_extensions then ruff shows:
```
machine_learning\automatic_differentiation.py:45:1: UP035 [*] Import from `typing` instead: `Self`
   |
43 | from enum import Enum
44 | from types import TracebackType
45 | from typing_extensions import Self
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ UP035
46 |
47 | import numpy as np
   |
   = help: Import from `typing`

```

2023-10-26 04:15 UTC, PoojanSmart commented
Apart from that I am not getting these ones in my local:

`machine_learning/automatic_differentiation.py:195: error: Access to generic instance variables via class is ambiguous  [misc]
machine_learning/automatic_differentiation.py:195: error: Incompatible return value type (got "GradientTracker", expected "Self")  [return-value]`

@imSanko / @cclauss can you please help?

2023-10-26 05:24 UTC, cclauss commented on machine_learning/automatic_differentiation.py
> +from typing import Self
Ruff was upgraded for Py3.12 but mypy has not yet been upgraded.
```suggestion
from typing_extensions import Self  # noqa: UP035
```

2023-10-26 13:29 UTC, cclauss requested changes
This looks really cool.  I hope the comments help.

2023-10-26 13:29 UTC, cclauss commented on machine_learning/automatic_differentiation.py
> +    will be calculated.
We get 88 characters per line max so let's use them to get to fewer lines.
```suggestion
    Class represents n-dimensional object which is used to wrap numpy array on which
    operations will be performed and the gradient will be calculated.
```

2023-10-26 13:29 UTC, cclauss commented on machine_learning/automatic_differentiation.py
> +    def __init__(self, value) -> None:
`from typing import Any`
```suggestion
    def __init__(self, value: Any) -> None:
```

2023-10-26 13:29 UTC, cclauss commented on machine_learning/automatic_differentiation.py
> +    def __str__(self) -> str:
```suggestion
    def __repr__(self) -> str:
```

2023-10-26 13:29 UTC, cclauss commented on machine_learning/automatic_differentiation.py
> +    def numpy(self) -> np.ndarray:
```suggestion
    def to_ndarray(self) -> np.ndarray:
```

2023-10-26 13:29 UTC, cclauss commented on machine_learning/automatic_differentiation.py
> +                tracker.add_operation(OpType.SUB, params=[self, other], output=result)
`add` ... `SUB` is a bit difficult to track.  What able `tracker.add_operation()` --> `tracker.append()`

2023-10-26 13:29 UTC, cclauss commented on machine_learning/automatic_differentiation.py
> +class OpType(Enum):
I would put this at the top of the file.

2023-10-26 13:29 UTC, cclauss commented on machine_learning/automatic_differentiation.py
> +    Class represents list of supported operations on Variable for
88 chars

2023-10-26 13:29 UTC, cclauss commented on machine_learning/automatic_differentiation.py
> +        return False
```suggestion
        return self.op_type == value if isinstance(value, OpType) else False
```

2023-10-26 13:29 UTC, cclauss commented on machine_learning/automatic_differentiation.py
> +        partial_deriv = {target: np.ones_like(target.numpy())}
This should be a `defaultdict[list]` so that we can streamline below.

2023-10-26 13:29 UTC, cclauss commented on machine_learning/automatic_differentiation.py
> +                    partial_deriv[param] = dparam_dtarget
```suggestion
                partial_deriv[param] += dparam_dtarget
```

2023-10-26 13:29 UTC, cclauss commented on machine_learning/automatic_differentiation.py
> +                        operation_queue.append(param.result_of)
```suggestion
                if param.result_of and param.result_of != OpType.NOOP:
                    operation_queue.append(param.result_of)
```

2023-10-26 13:29 UTC, cclauss commented on machine_learning/automatic_differentiation.py
> +        return None
```suggestion
        return partial_deriv.get(source)
```

2023-10-26 13:29 UTC, cclauss commented on machine_learning/automatic_differentiation.py
> +        derivative = None
The method `.derivative()` does not need a variable also called `derivative`.  Just return the value as soon as you have it.
```suggestion
```

2023-10-26 13:29 UTC, cclauss commented on machine_learning/automatic_differentiation.py
> +        elif operation == OpType.SUB:
```suggestion
            return np.ones_like(params[0].numpy(), dtype=np.float64)
        if operation == OpType.SUB:
```

2023-10-26 13:29 UTC, cclauss commented on machine_learning/automatic_differentiation.py
> +            derivative = (
```suggestion
                return np.ones_like(params[0].numpy(), dtype=np.float64)
            else:
                return -np.ones_like(params[1].numpy(), dtype=np.float64)
        if operation == OpType.MUL:
            return (
```

2023-10-26 13:29 UTC, cclauss commented on machine_learning/automatic_differentiation.py
> +        elif operation == OpType.DIV:
```suggestion
        if operation == OpType.DIV:
```

2023-10-26 13:29 UTC, cclauss commented on machine_learning/automatic_differentiation.py
> +            derivative = (
```suggestion
                return 1 / params[1].numpy()
            else:
                return -params[0].numpy() / (params[1].numpy() ** 2)
        if operation == OpType.MATMUL:
            return (
```

2023-10-26 13:29 UTC, cclauss commented on machine_learning/automatic_differentiation.py
> +            derivative = power * (params[0].numpy() ** (power - 1))
```suggestion
        if operation == OpType.POWER:
            power = operation.other_params["power"]
            return power * (params[0].numpy() ** (power - 1))
```

2023-10-26 13:29 UTC, cclauss commented on machine_learning/automatic_differentiation.py
> +        return derivative
Do we want to `raise ValueError("Invalid operation")` here?

2023-10-27 08:47 UTC, cclauss approved these changes
Awesome contribution!  Thanks for doing this.

2023-10-27 08:47 UTC, merged