adding a geometry module
TheAlgorithms/Python pull request #11138
Opened 2023-11-03 15:47 UTC by meg-1

### Describe your change:
implementing suggestion: [specifics] (https://github.com/TheAlgorithms/Python/pull/8778#issuecomment-1600934020) which was brought up in #8778 

This is a geometry module dedicated to working with different geometrical structures and shapes in a strucutred manner.

**The main interfaces are:**
1. Shape - an interface which represents all possible geometrical shapes
2. Shape Types (submodule) - Interfaces for different types of shapes
3. Geometrical Primitives - Utility Data Structures for working with shapes

Feel free to extend this module.

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-11-05 09:56 UTC, cclauss commented
A lot of these errors could be automatically fixed with:
```
python3 -m pip install ruff
ruff --select=I,TID --fix geometry
```

2023-11-16 02:29 UTC, cclauss commented
OK...  I created a new file that contains a bunch of feedback on how to structure things and how to create doctests.  The current pull request contains tons of files which makes it difficult to review but there is great stuff here.  Rectangles need four Sides, not two.  Using dataclasses makes building doctests easier.

2023-11-17 15:34 UTC, meg-1 commented
> OK... I created a new file that contains a bunch of feedback on how to structure things and how to create doctests. The current pull request contains tons of files which makes it difficult to review but there is great stuff here. Rectangles need four Sides, not two. Using dataclasses makes building doctests easier.

@cclauss , Thank you incredibly for the thorough code review, it is grately appreciated! I have a few clarifying questions, just to check whether I understood everything correctly, if you don't mind, to not waste more of your time in the future:

1. Should we keep all of the code in one file, just as the code review showed, or was the code placed in one file simply for a more efficient code review, and the original structure is fine?

2. Do you think it would be a good idea to move all of the primitives (Angle, Side) to a file (f.e. 'primities.py'), and Shapes into a different file (f.e. 'shapes.py'), as a more structured approach (leave files such as open_shape, closed_shape, e.t.c.)?

3. Based on 'The Algorithms' structure, and the mission of the repo, would it be better to leave the structure as it is right now, complicated yet easy to add onto in the future (f.e. adding a new class to the structure), if anyone wishes, or to simplify it by modifying the existing code directly (f.e. adding a new method to an existing class), yet making it harder to add onto in the future?

2023-11-24 17:28 UTC, cclauss commented on geometry/code_review_feedback.py
> +import math
```suggestion

import math
```

2023-11-24 17:30 UTC, cclauss commented on geometry/code_review_feedback.py
> +
```suggestion
```

2023-11-24 17:32 UTC, cclauss commented on geometry/geometry.py
> +import math
```suggestion

import math
```

2023-11-24 17:35 UTC, cclauss commented
```
codespell................................................................Failed
- hook id: codespell
- exit code: 65

geometry/geometry.py:43: lightyears ==> light years
geometry/code_review_feedback.py:43: lightyears ==> light years
```
Hint: This should not be `light years` anyway.  Put something better instead.

2023-11-24 17:49 UTC, cclauss requested changes

2023-11-24 17:49 UTC, cclauss commented on geometry/code_review_feedback.py
> +    def post_init(self):
```suggestion
    def post_init(self) -> None:
```

2023-11-24 17:49 UTC, cclauss commented on geometry/code_review_feedback.py
> +    def perimeter(self):
```suggestion
    def perimeter(self) -> float:
```

2023-11-24 17:49 UTC, cclauss commented on geometry/code_review_feedback.py
> +    def area(self):
```suggestion
    def area(self) -> float:
```

2023-11-24 17:49 UTC, cclauss commented on geometry/geometry.py
> +    def perimeter(self):
```suggestion
    def perimeter(self) -> float:
```

2023-11-24 17:49 UTC, cclauss commented on geometry/geometry.py
> +    def area(self):
```suggestion
    def area(self) -> float:
```

2023-11-24 17:49 UTC, cclauss commented on geometry/geometry.py
> +    def __init__(self, side_length):
```suggestion
    def __init__(self, side_length) -> None:
```

2023-11-24 17:49 UTC, cclauss commented on geometry/geometry.py
> +    def perimeter(self):
```suggestion
    def perimeter(self) -> float:
```

2023-11-24 17:49 UTC, cclauss commented on geometry/geometry.py
> +    def area(self):
```suggestion
    def area(self) -> float:
```

2023-11-24 17:49 UTC, cclauss commented on geometry/geometry.py
> +    def post_init(self):
```suggestion
    def post_init(self) -> None:
```

2023-11-24 17:52 UTC, cclauss requested changes

2023-11-24 17:52 UTC, cclauss commented on geometry/geometry.py
> +    def __init__(self, side_length) -> None:
```suggestion
    def __init__(self, side_length: float) -> None:
```

2023-11-24 17:55 UTC, cclauss commented on geometry/geometry.py
> +    length: the length of the current side in lightyears
```suggestion
    length: the length of the current side in meters
```

2023-11-24 17:55 UTC, cclauss approved these changes

2023-11-24 18:00 UTC, merged

2023-11-24 18:17 UTC, cclauss commented
Thanks for doing this.  Sorry that it took so long to land.

In a future pull request(s) could be broken into the following files.
* `angle.py`
* `side.py`
* `ellipse.py` includes Ellipse and Circle (Perhaps `Oval` should be the base class ;-) )
* `polygon.py` includes Rectangle, Square, (future...) Trapezoid, Triangle, Pentagon, Hexigon, etc...

* `Circle` has optimized calculations for `area` but `Square` does not yet have such optimizations.
* `Rectangle` has two sides, not four!