Added doctest to skew_heap.py
TheAlgorithms/Python pull request #11147
Opened 2023-11-07 18:13 UTC by Suyashd999

### Describe your change:

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-11-08 02:07 UTC, imSanko requested changes

2023-11-08 02:07 UTC, imSanko commented on data_structures/heap/skew_heap.py
> +        >>> sn = SkewNode(10)
"""
Return the value of the node.

>>> sn = SkewNode(0)
>>> sn.value
0

>>> sn = SkewNode(3.14159)
>>> sn.value
3.14159

>>> sn = SkewNode("hello")
>>> sn.value
'hello'

>>> sn = SkewNode(None)
>>> sn.value
None

>>> sn = SkewNode(True)
>>> sn.value
```suggestion
        >>> sn = SkewNode(10)
```
```suggestion
        >>> sn = SkewNode(10)
```
True

>>> sn = SkewNode([])
>>> sn.value
[]

>>> sn = SkewNode({})
>>> sn.value
{}

>>> sn = SkewNode(set())
>>> sn.value
set()

>>> sn = SkewNode(0.0)
>>> sn.value
0.0

>>> sn = SkewNode(-1e-10)
>>> sn.value
-1e-10
"""

2023-11-08 02:11 UTC, imSanko requested changes

2023-11-08 02:11 UTC, imSanko commented on data_structures/heap/skew_heap.py
> +
```suggestion
"""
Return the value of the node.

>>> sn = SkewNode(0)
>>> sn.value
0

>>> sn = SkewNode(3.14159)
>>> sn.value
3.14159

>>> sn = SkewNode("hello")
>>> sn.value
'hello'

>>> sn = SkewNode(None)
>>> sn.value
None

>>> sn = SkewNode(True)
>>> sn.value
True

>>> sn = SkewNode([])
>>> sn.value
[]

>>> sn = SkewNode({})
>>> sn.value
{}

>>> sn = SkewNode(set())
>>> sn.value
set()

>>> sn = SkewNode(0.0)
>>> sn.value
0.0

>>> sn = SkewNode(-1e-10)
>>> sn.value
-1e-10
"""


```

2024-01-18 12:39 UTC, cclauss approved these changes

2024-01-18 12:39 UTC, merged