Added doctest to binary_search_tree.py
TheAlgorithms/Python pull request #11145
Opened 2023-11-06 15:05 UTC by Suyashd999

### Describe your change:

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-11-08 02:09 UTC, imSanko requested changes

2023-11-08 02:09 UTC, imSanko commented on data_structures/binary_tree/binary_search_tree.py
> +        """
```suggestion
        """"""
>>> bst = BinarySearchTree()
>>> bst.insert(10)
>>> bst.search(10)
10
>>> bst.insert(5)
>>> bst.insert(15)
>>> bst.insert(3)
>>> bst.insert(7)
>>> bst.insert(12)
>>> bst.insert(18)
>>> bst.search(5)
5
>>> bst.search(15)
15
>>> bst.search(3)
3
>>> bst.search(7)
7
>>> bst.search(12)
12
>>> bst.search(18)
18
>>> bst.search(9)  # Element not present
>>> bst.search(0)  # Element not present
>>> bst.search(20)  # Element not present
"""


```

2023-11-25 14:19 UTC, cclauss requested changes

2023-11-25 14:19 UTC, cclauss commented on data_structures/binary_tree/binary_search_tree.py
> +        >>> bst= BinarySearchTree().search(10)
```suggestion
        >>> tree = BinarySearchTree().insert(10, 20, 30, 40, 50)
        >>> tree.search(10)
        {'10': (None, {'20': (None, {'30': (None, {'40': (None, 50)})})})}
        >>> tree.search(20)
        {'20': (None, {'30': (None, {'40': (None, 50)})})}
        >>> tree.search(30)
        {'30': (None, {'40': (None, 50)})}
        >>> tree.search(40)
        {'40': (None, 50)}
        >>> tree.search(50)
        50
        >>> bst.search(5) is None  # element not present
        True
        >>> bst.search(0) is None  # element not present
        True
        >>> bst.search(-5) is None  # element not present
        True
        >>> BinarySearchTree().search(10)
```

2023-11-25 14:19 UTC, cclauss commented on data_structures/binary_tree/binary_search_tree.py
> +        ...
```suggestion
            ...
```

2023-11-25 14:19 UTC, cclauss commented on data_structures/binary_tree/binary_search_tree.py
> +        {'783': ({'30': (1, 740)}, None)}
```suggestion
        >>> BinarySearchTree().insert(10, 20, 30, 40, 50).get_max()
        50
        >>> BinarySearchTree().insert(-5, -1, 0.1, -0.3, -4.5).get_max()
        {'0.1': (-0.3, None)}
        >>> BinarySearchTree().insert(1, 78.3, 30, 74.0, 1).get_max()
        {'78.3': ({'30': (1, 74.0)}, None)}
        >>> BinarySearchTree().insert(1, 783, 30, 740, 1).get_max()
        {'783': ({'30': (1, 740)}, None)}
```

2023-11-25 14:19 UTC, cclauss commented on data_structures/binary_tree/binary_search_tree.py
> +        >>> BinarySearchTree().insert(1,783,30,740,1).get_min()
```suggestion
        >>> BinarySearchTree().insert(10, 20, 30, 40, 50).get_min()
        {'10': (None, {'20': (None, {'30': (None, {'40': (None, 50)})})})}
        >>> BinarySearchTree().insert(-5, -1, 0, -0.3, -4.5).get_min()
        {'-5': (None, {'-1': (-4.5, {'0': (-0.3, None)})})}
        >>> BinarySearchTree().insert(1, 78.3, 30, 74.0, 1).get_min()
        {'1': (None, {'78.3': ({'30': (1, 74.0)}, None)})}
        >>> BinarySearchTree().insert(1, 783, 30, 740, 1).get_min()
```

2023-11-25 14:26 UTC, cclauss commented on data_structures/binary_tree/binary_search_tree.py
> +        >>> bst.search(-5) is None  # element not present
```suggestion
        >>> tree.search(5) is None  # element not present
        True
        >>> tree.search(0) is None  # element not present
        True
        >>> tree.search(-5) is None  # element not present
```

2023-11-25 14:29 UTC, cclauss approved these changes

2023-11-25 14:29 UTC, merged