Updated power_of_4.py
TheAlgorithms/Python pull request #11152
Opened 2023-11-11 06:51 UTC by AseemGupta39

2023-11-13 03:21 UTC, imSanko reviewed
Check with the `pre-commit run --all-files --show-diff-on-failure` for your errors to go through

2023-11-29 20:48 UTC, cclauss commented on bit_manipulation/power_of_4.py
> +        while number != 1 and number != 2:
```suggestion
        while number not in (1, 2):
```

2023-12-20 01:53 UTC, tianyizheng02 requested changes

2023-12-20 01:53 UTC, tianyizheng02 commented on bit_manipulation/power_of_4.py
> -        return False
The function now doesn't return anything if the if-statement evaluates to False. This is why the build is failing.

2024-09-30 09:15 UTC, cclauss commented
Closing tests_are_failing PRs to prepare for Hacktoberfest 2024

2024-09-30 09:15 UTC, closed without merging