Create Spearman's rank correlation coefficient
TheAlgorithms/Python pull request #11155
Opened 2023-11-14 17:02 UTC by cyrixninja

### Describe your change:
Implemented Python program to find Spearman's rank correlation coefficient. Spearman's rank correlation coefficient is a nonparametric measure of rank correlation (statistical dependence between the rankings of two variables). It assesses how well the relationship between two variables can be described using a monotonic function.

Wikipedia References: 
https://en.wikipedia.org/wiki/Spearman%27s_rank_correlation_coefficient

* [x] Add an algorithm?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.

2023-11-14 17:17 UTC, cyrixninja commented on maths/spearman_rank_correlation_coefficient.py
> +def rankdata(arr):
Done

2023-11-14 17:17 UTC, cyrixninja commented on maths/spearman_rank_correlation_coefficient.py
> +def spearman_rank_correlation(x, y):
Done

2023-11-15 11:03 UTC, cyrixninja commented on maths/spearman_rank_correlation_coefficient.py
> +def calculate_spearman_rank_correlation(x: list[float], y: list[float]) -> float:
Done

2023-11-25 14:05 UTC, cclauss requested changes

2023-11-25 14:05 UTC, cclauss commented on maths/spearman_rank_correlation_coefficient.py
> +    rho1 = calculate_spearman_rank_correlation(x1, y1)
```suggestion
    print(f"{calculate_spearman_rank_correlation([1, 2, 3, 4, 5], [2, 4, 6, 8, 10]) = }")
```

2023-11-25 14:05 UTC, cclauss commented on maths/spearman_rank_correlation_coefficient.py
> +    rho2 = calculate_spearman_rank_correlation(x2, y2)
```suggestion
    print(f"{calculate_spearman_rank_correlation([1, 2, 3, 4, 5], [5, 4, 3, 2, 1]) = }")
```

2023-11-25 14:05 UTC, cclauss commented on maths/spearman_rank_correlation_coefficient.py
> +    rho3 = calculate_spearman_rank_correlation(x3, y3)
```suggestion
    print(f"{calculate_spearman_rank_correlation([1, 2, 3, 4, 5], [5, 1, 2, 9, 5]) = }")
```

2023-11-25 14:05 UTC, cclauss commented on maths/spearman_rank_correlation_coefficient.py
> +    print(f"Spearman's rank correlation coefficient (Example 3): {rho3}")
```suggestion
```

2023-11-25 14:05 UTC, cclauss commented on maths/spearman_rank_correlation_coefficient.py
> +    print(f"Spearman's rank correlation coefficient (Example 2): {rho2}")
```suggestion
```

2023-11-25 14:05 UTC, cclauss commented on maths/spearman_rank_correlation_coefficient.py
> +    print(f"Spearman's rank correlation coefficient (Example 1): {rho1}")
```suggestion
```

2023-11-25 14:08 UTC, cclauss commented on maths/spearman_rank_correlation_coefficient.py
> +def assign_ranks(data: list[float]) -> list[int]:
```suggestion
def assign_ranks(data: Sequence[float]) -> list[int]:
```

2023-11-25 14:20 UTC, cclauss approved these changes

2023-11-25 14:20 UTC, merged