add graphs/ant_colony_optimization_algorithms.py
TheAlgorithms/Python pull request #11163
Opened 2023-11-16 08:14 UTC by Clarkzzzzz

### Describe your change:
A simple example uses the ant colony optimization algorithm to solve the classic TSP problem.

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-11-16 08:59 UTC, Clarkzzzzz commented
Hello, The file that failed the test is not my file. What should I do?

2023-11-16 10:47 UTC, cclauss requested changes

2023-11-16 10:47 UTC, cclauss commented on graphs/ant_colony_optimization_algorithms.py
> +to solve the classic TSP problem
What is TSP and why does the reader need to guess?

2023-11-16 10:47 UTC, cclauss commented on graphs/ant_colony_optimization_algorithms.py
> +    >>> distance([0,0],[3,4] )
```suggestion
    >>> distance([0,0], [3,4] )
```

2023-11-16 10:47 UTC, cclauss commented on graphs/ant_colony_optimization_algorithms.py
> +    pheromone: list[list],
```suggestion
    pheromone: list[list[WHAT]],
```

2023-11-16 10:47 UTC, cclauss commented on graphs/ant_colony_optimization_algorithms.py
> +    q: float,
What is `q` and why is the reader forced to guess?

2023-11-16 10:47 UTC, cclauss commented on graphs/ant_colony_optimization_algorithms.py
> +    best_path: list,
```suggestion
    best_path: list[WHAT],
```

2023-11-16 10:47 UTC, cclauss commented on graphs/ant_colony_optimization_algorithms.py
> +    Update pheromones on the route and update the best route
doctests needed.

2023-11-16 10:47 UTC, cclauss commented on graphs/ant_colony_optimization_algorithms.py
> +    Choose the next city for ants
doctests needed.

2023-11-16 10:47 UTC, cclauss commented on graphs/ant_colony_optimization_algorithms.py
> +    print("Best Distance:", best_distance)
```suggestion
    print(f"{best_path = }")
    print(f"{best_distance = }")
```

2023-11-25 12:26 UTC, cclauss approved these changes
It would be better to detect if there are no `cities` or `ants_num < 1`or `iterations_num < 1` and raise ValueError.

2023-11-25 12:26 UTC, merged