optimize quicksort implementation
TheAlgorithms/Python pull request #11197
Opened 2023-12-04 19:49 UTC by tusharpamnani

### Describe your change:
Optimized quicksort implementation for clarity and performance.

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-12-05 00:27 UTC, leonidas-king approved these changes

2023-12-05 11:54 UTC, imSanko requested changes

2023-12-05 11:54 UTC, imSanko commented on sorts/quicksort.py
>      Examples:
```suggestion
  # Example 3: Empty list
>>> quick_sort([])
[]

# Example 4: List with a single element
>>> quick_sort([42])
[42]

# Example 5: Already sorted list
>>> quick_sort([1, 2, 3, 4, 5])
[1, 2, 3, 4, 5]

# Example 6: List with duplicate elements
>>> quick_sort([5, 2, 1, 4, 2, 1, 5])
[1, 1, 2, 2, 4, 5, 5]

# Example 7: List with negative and positive numbers
>>> quick_sort([7, -5, 3, 0, -1])
[-5, -1, 0, 3, 7]

# Example 8: List with repeated elements
>>> quick_sort([3, 2, 3, 2, 3, 2])
[2, 2, 2, 3, 3, 3]

# Example 9: List with large values
>>> quick_sort([1000, 999, 10000, 0, -100])
[-100, 0, 999, 1000, 10000]

```

2023-12-05 11:54 UTC, imSanko commented on sorts/quicksort.py
>      Examples:
Can you try these tests?

2023-12-20 01:49 UTC, tianyizheng02 commented
Duplicate of #11196

2023-12-20 01:49 UTC, closed without merging