Add Van der Waals equation of state
TheAlgorithms/Python pull request #11359
Opened 2024-04-10 15:19 UTC by Glebfra

### Describe your change:

* [x] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [x] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2024-04-14 04:19 UTC, imSanko approved these changes
Nice !!

2024-04-19 20:55 UTC, cclauss requested changes

2024-04-19 20:55 UTC, cclauss commented on physics/vander_vaals_gas_law.py
> +        raise ValueError("Please provide the positive values")
```suggestion
        raise ValueError("Please provide non-negative values")
```

2024-04-19 20:55 UTC, cclauss commented on physics/vander_vaals_gas_law.py
> +    quantity: float, temperature: float, volume: float, a: float, b: float
Please replace `a` and `b` with self-documentating variable names.

2024-04-19 20:55 UTC, cclauss commented on physics/vander_vaals_gas_law.py
> +    quantity: float, temperature: float, volume: float, a: float, b: float
What happens when quantity is zero?  When quantity is negative?

2024-04-19 20:55 UTC, cclauss commented on physics/vander_vaals_gas_law.py
> +        raise ValueError("Please provide the positive values")
Please add a test for both values being zero.

2024-04-19 20:55 UTC, cclauss commented on physics/vander_vaals_gas_law.py
> +        raise ValueError("Please provide the positive values")
Non-negative

2024-04-19 20:55 UTC, cclauss commented on physics/vander_vaals_gas_law.py
> +    return 8 * a / (27 * b * R)
Please replace b & R with self-documentating names

2024-09-30 09:20 UTC, cclauss commented
Closing awaiting_changes PRs to prepare for Hacktoberfest 2024

2024-09-30 09:20 UTC, closed without merging