An alternate solution for pairs_with_given_sum
TheAlgorithms/Python pull request #11415
Opened 2024-05-24 14:10 UTC by PavanVenkataNagaManoj17

### Describe your change:
implemented a very simple alternative solution instead of using the itertools package

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2024-05-25 01:25 UTC, imSanko requested changes

2024-05-25 01:25 UTC, imSanko commented on data_structures/arrays/pairs_with_given_sum.py
> +    return count_total
```suggestion
def no_of_pairs(arr: list, req_sum: int) -> int:
    count_total = 0
    seen = {}
    
    for number in arr:
        complement = req_sum - number
        count_total += seen.get(complement, 0)
        seen[number] = seen.get(number, 0) + 1
    
    return count_total

```

2024-06-02 01:01 UTC, tianyizheng02 requested changes

2024-06-02 01:01 UTC, tianyizheng02 commented on data_structures/arrays/pairs_with_given_sum.py
> +            if (arr[i] + arr[j]) == req_sum:
```suggestion
            if arr[i] + arr[j] == req_sum:
```
The parentheses are unnecessary

2024-06-02 01:03 UTC, tianyizheng02 requested changes

2024-06-02 01:03 UTC, tianyizheng02 commented on data_structures/arrays/pairs_with_given_sum.py
> +def no_of_pairs(arr: list, req_sum: int) -> int:
```suggestion
def no_of_pairs(arr: list[int], req_sum: int) -> int:
```
Please specify the type of the list's contents

2024-08-16 05:35 UTC, PavanVenkataNagaManoj17 commented on data_structures/arrays/pairs_with_given_sum.py
> +def no_of_pairs(arr: list, req_sum: int) -> int:
ok sir

2024-08-16 05:35 UTC, PavanVenkataNagaManoj17 commented on data_structures/arrays/pairs_with_given_sum.py
> +    # very much slower in execution
ok sir

2024-09-30 08:48 UTC, cclauss commented
Closing tests_are_failing PRs to prepare for Hacktoberfest 2024

2024-09-30 08:48 UTC, closed without merging