The sum of outcomes for rolling an N-sided dice K times.
TheAlgorithms/Python pull request #11463
Opened 2024-06-15 02:23 UTC by dipuk0506

### Describe your change:

* [x] Add an algorithm?

   The sum of outcomes for rolling an N-sided dice K times.
   
   This function returns a list. The last two elements are the 
    range of probability distribution.
    The range is: 'k_time' to 'k_time*n_side'
    
    Other elements contain probabilities for getting a summation 
    from 'k_time' to 'k_time*n_side'.

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2024-06-16 09:59 UTC, dipuk0506 commented
Hi, If you have any confusion about the algorithm, you can email me at hmdkabir@connect.ust.hk and arrange a meeting.

2024-06-19 02:53 UTC, dipuk0506 commented
Please email me, if you are confused.

2024-06-19 05:16 UTC, dipuk0506 commented
There are two typos in comments. Everything else seems correct.

Lines 40 and 41 will be as follows:

The probability of getting 2 is 1/36.
The probability of getting 3 is 2/36.

2024-06-20 03:39 UTC, dipuk0506 commented
Please approve

2024-06-20 18:06 UTC, imSanko approved these changes

2024-06-25 00:55 UTC, dipuk0506 commented
For theory visit the wiki page:
https://en.wikipedia.org/wiki/Convolution_of_probability_distributions

For more explanation of the theory please visit my GitHub repository:
https://github.com/dipuk0506/dice

Please correct 2 typos and merge.

2024-07-05 00:46 UTC, dipuk0506 commented
Please Merge the request.

2025-07-27 19:26 UTC, mindaugl approved these changes

2026-09-15 12:30 UTC, cclauss commented on maths/sum_of_outcomes_for_rolling_n_sided_dice_k_time.py
> +def outcome_of_rolling_n_sided_dice_k_time(n_side: int, k_time: int) -> float:
CONTRIBUTING.md says that variable names should be self-documenting.
```suggestion
def outcome_of_rolling_n_sided_dice_k_time(number_of_sides: int, number_of_rolls: int) -> float:
```

2026-09-15 12:30 UTC, cclauss requested changes

2026-09-22 05:46 UTC, closed without merging