Add doctests to interpolation_search.py
TheAlgorithms/Python pull request #11492
Opened 2024-07-18 10:30 UTC by Ihor-Pryyma

### Describe your change:
Contributes to https://github.com/TheAlgorithms/Python/issues/9943

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2024-07-20 01:45 UTC, Abonimohan approved these changes

2024-07-20 01:48 UTC, Abonimohan requested changes
Line 11-12 please check it out

2024-07-22 01:47 UTC, imSanko requested changes
`value not in ("#", "")`. Use a `set` if the elements are hashable.

2024-07-22 06:59 UTC, Ihor-Pryyma commented
> `value not in ("#", "")`. Use a `set` if the elements are hashable.

but that file is not in my PR

2024-07-23 08:43 UTC, cclauss commented on searches/interpolation_search.py
> +    >>> interpolation_search([], 1)
```suggestion
    >>> interpolation_search([1, 2, 3, 4, 5], 6) is None
    True
    >>> interpolation_search([], 1) is None
    True
```
Please repeat below.

2024-07-23 08:45 UTC, cclauss commented
`web_programming/emails_from_url.py` was fixed in a separate pull request.

2024-07-25 14:31 UTC, Ihor-Pryyma commented on searches/interpolation_search.py
> +    >>> interpolation_search([], 1)
fixed

2024-07-25 14:39 UTC, imSanko reviewed
Looks good to be @cclauss will let know better to move forward with this.

2024-07-25 15:56 UTC, cclauss approved these changes
Thanks!

2024-07-25 15:56 UTC, merged