Feature/kd tree implementation
TheAlgorithms/Python pull request #11532
Opened 2024-08-28 11:29 UTC by Ramy-Badr-Ahmed

### Describe your change:

This pull request adds an implementation of the KD-Tree data structure along with related functionalities, such as nearest neighbor searches.

**Definition**: The KD-Tree is a space-partitioning data structure used for organizing points in a k-dimensional space. (URL: [KD-Tree](https://en.wikipedia.org/wiki/K-d_tree))

**Implementation Details**:

- `build_kdtree.py`: Contains the function to build a KD-Tree from a set of points.
- `nearest_neighbor_search.py`: Implements the nearest neighbor search algorithm using the built KD-Tree.
- `kd_node.py`: Defines the KDNode class representing nodes in the KD-Tree.

**Example Usage**:
- `hypercube_points.py`: Provides a function to generate random points uniformly distributed within an n-dimensional hypercube.
- `example_usage.py`: Demonstrates how to use the KD-Tree implementation with the generated random hypercube points and querying for nearest neighbors.

2024-08-28 12:16 UTC, Ramy-Badr-Ahmed reviewed
done

2024-08-28 19:03 UTC, Ramy-Badr-Ahmed reviewed
Added pytests, docstrings, & typehints

2024-08-28 19:10 UTC, Ramy-Badr-Ahmed reviewed
added pytests, changed assertion style

2024-08-28 19:30 UTC, Ramy-Badr-Ahmed reviewed
eliminated earlier build errors

2024-08-29 11:22 UTC, Ramy-Badr-Ahmed commented
Fixed pre-commit.ci - pr & ruff / ruff (pull_request) checks

2024-08-29 11:23 UTC, Ramy-Badr-Ahmed reviewed
All checks have passed

2024-08-30 02:31 UTC, imSanko requested changes
Sound Good to me, [at]Claus will let you know better.

2024-09-03 09:09 UTC, Ramy-Badr-Ahmed commented
@cclauss 
Thanks for your review :)

2024-09-03 09:11 UTC, Ramy-Badr-Ahmed commented
> Sound Good to me, [at]Claus will let you know better.

Thanks! The "tests are failing" label is till assigned.

2024-09-03 09:46 UTC, cclauss commented on data_structures/kd_tree/build_kdtree.py
> +        KDNode | None: The root node of the KD-Tree,
```suggestion
        The root node of the KD-Tree,
```

2024-09-03 09:48 UTC, cclauss commented on data_structures/kd_tree/example/hypercube_points.py
> +        num_dimensions (int): Number of dimensions of the hypercube.
```suggestion
        num_points: Number of points to generate.
        hypercube_size: Size of the hypercube.
        num_dimensions: Number of dimensions of the hypercube.
```

2024-09-03 09:49 UTC, cclauss commented on data_structures/kd_tree/example/hypercube_points.py
> +        np.ndarray: An array of shape (num_points, num_dimensions)
```suggestion
        An array of shape (num_points, num_dimensions)
```

2024-09-03 09:53 UTC, cclauss commented on data_structures/kd_tree/tests/test_kdtree.py
> +    kdtree = build_kdtree(points.tolist())
Please add `build_kdtree()` tests where:
* [ ] `points = []`
* [ ] `depth = 2`
* [ ] `depth = -2`

2024-09-03 10:42 UTC, Ramy-Badr-Ahmed commented on data_structures/kd_tree/tests/test_kdtree.py
> +    kdtree = build_kdtree(points.tolist())
done

2024-09-03 11:09 UTC, cclauss commented on data_structures/kd_tree/tests/test_kdtree.py
> +            f"Expected point dimension {num_dimensions}, got {len(kdtree.point)}"
PEP8: Avoid backslashes in Python code.
```suggestion
        assert len(kdtree.point) == num_dimensions, (
            f"Expected point dimension {num_dimensions}, got {len(kdtree.point)}"
        )
```

2024-09-03 11:15 UTC, Ramy-Badr-Ahmed commented on data_structures/kd_tree/tests/test_kdtree.py
> +        assert (
removed backslashes: PEP8

2024-09-03 11:57 UTC, cclauss commented on data_structures/kd_tree/build_kdtree.py
> +        depth (int): The current depth in the tree
```suggestion
        points: The list of points to build the KD-Tree from.
        depth: The current depth in the tree
```

2024-09-03 11:57 UTC, cclauss commented on data_structures/kd_tree/kd_node.py
> +
```suggestion
```

2024-09-03 11:57 UTC, cclauss commented on data_structures/kd_tree/kd_node.py
> +        right: Optional["KDNode"] = None,
```suggestion
        point: The point stored in this node.
        left: The left child node.
        right: The right child node.
    """

    def __init__(
        self,
        point: list[float],
        left: KDNode | None = None,
        right: KDNode | None  = None,
```

2024-09-03 11:57 UTC, cclauss commented on data_structures/kd_tree/nearest_neighbour_search.py
> +            depth (int): The current depth in the KD-Tree.
```suggestion
            node: The current node in the KD-Tree.
            depth: The current depth in the KD-Tree.
```

2024-09-03 11:59 UTC, cclauss commented
I made some changes... Let's see if it passes.

2024-09-03 12:34 UTC, Ramy-Badr-Ahmed commented
> I made some changes... Let's see if it passes.

Works now :-)

2024-09-03 12:39 UTC, cclauss approved these changes
Nice...  Nodes are usually great candidates for `dataclass`.

Thanks for doing this.

2024-09-03 12:39 UTC, merged