Update linear_regression.py
TheAlgorithms/Python pull request #11567
Opened 2024-09-15 10:03 UTC by PurvalBhude

add error handling function. it can handle errors and still run the linear regression algorithm.

### Describe your change:
Added try-except blocks for network errors while fetching the dataset (requests.exceptions.RequestException).
Added error handling for gradient descent and sum of square error calculations to avoid crashing during matrix operations.
Ensured that the main function can handle unexpected issues during the linear regression process and print useful debugging messages.

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2024-09-16 07:02 UTC, PurvalBhude commented
Please review the pull request and merge it.

2024-09-16 16:52 UTC, imSanko requested changes
Let me know what exactly you are trying to change or enhance for ??

2024-09-20 16:07 UTC, PurvalBhude commented
i am trying enhancing the code's robustness by adding error handling to prevent crashes during key operations like dataset fetching, gradient descent, and error calculations. Specifically, i am ensuring that network issues, matrix operations, and computational errors don't disrupt the linear regression process, providing useful debugging messages instead.

2024-09-23 13:42 UTC, PurvalBhude commented
Can you merge my pull request by reviewing the PR.

2024-10-14 12:41 UTC, PurvalBhude commented
pls merge the this for following issue 

Create error handling function in linear regression algorithm of ML #11534

2026-09-16 07:06 UTC, closed without merging