Create sliding_window.py
TheAlgorithms/Python pull request #11581
Opened 2024-09-25 01:36 UTC by OmMahajan29

created sliding_window algorithm under greedy algorithm section please merge with master

### Describe your change: created a function for sliding window under greedy algorithm file please merge 

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2024-09-25 03:37 UTC, OmMahajan29 commented
All test cases have passed , allow merge

2024-09-25 16:19 UTC, imSanko requested changes

2024-09-25 16:19 UTC, imSanko commented on greedy_methods/sliding_window.py
> +    3
Can you make it more enhanced ?

2024-09-25 16:31 UTC, OmMahajan29 commented on greedy_methods/sliding_window.py
> +    3
Enhanced in what way?

2024-09-29 14:48 UTC, imSanko approved these changes

2024-10-02 17:04 UTC, haxkd commented
@OmMahajan29 function and file name can be **longest_substring_sliding_window**

2026-09-21 05:32 UTC, cclauss approved these changes

2026-09-21 05:32 UTC, merged