Add Algorithm for Fresnel Diffraction
TheAlgorithms/Python pull request #11580
Opened 2024-09-24 07:01 UTC by jakerogers-1

Fresnel diffraction of wave fields is commonly simulated within optical physics yet no algorithm exists within the repository presently to facilitate this. The included code utilizes the transfer function based approach found in the textbook Computational Fourier Optics by David Voelz and his related research publications to perform Fresnel diffraction for a given (coherent and monochromatic) wave field. 

The original MATLAB has been translated into Python with a more user-friendly interface added and error handling.

2024-09-24 15:05 UTC, imSanko requested changes
Add more tests !

2024-09-26 18:25 UTC, imSanko approved these changes
seems fair enough!

2026-09-13 20:53 UTC, cclauss commented
@priya-sundaram-dev, please review.

2026-09-13 21:21 UTC, priya-sundaram-dev commented
Re-checked #11580 on the current head (`128bf6d`) — all checks are green now (`build`, `ty`, `build_docs`, `ruff` all success; `deploy_docs` skipped as expected). The line-79 `np.isclose(...)` → `bool(np.isclose(...))` doctest fix landed, so the NumPy 2.x `np.True_` repr failure is resolved. Ready to merge from a CI standpoint. 👍

2026-09-13 21:40 UTC, cclauss approved these changes

2026-09-13 21:41 UTC, merged