chore: improve comments and add tests to trapezoidal rule
TheAlgorithms/Python pull request #11640
Opened 2024-10-01 17:30 UTC by jurichar

### Describe your change:

Contributes to https://github.com/TheAlgorithms/Python/issues/9943
And convert value explicity to float

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [x] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2024-10-04 10:11 UTC, tianyizheng02 requested changes
Apart from my other comments, this file also needs type hints

2024-10-04 10:11 UTC, tianyizheng02 commented on maths/trapezoidal_rule.py
>  def method_1(boundary, steps):
```suggestion
def trapezoidal_rule(boundary, steps):
```
Let's rename the function to something more descriptive. I'm not sure why the code calls it "method 1" when there's only one method in the file.

2024-10-04 10:11 UTC, tianyizheng02 commented on maths/trapezoidal_rule.py
> +This method is the classical approach of summing 'Equally Spaced Abscissas'
```suggestion
The trapezoidal rule is the classical approach of summing 'Equally Spaced Abscissas'
```
Let's rephrase the header docstring to name the rule directly. I'm not sure why the original author called it "method 1".

2024-10-04 10:11 UTC, tianyizheng02 commented on maths/trapezoidal_rule.py
```suggestion
```
See previous comment

2024-10-04 10:11 UTC, tianyizheng02 commented on maths/trapezoidal_rule.py
>      return y
```suggestion
    return x**2
```
Doesn't this do the same thing?

2024-10-06 12:23 UTC, jurichar commented on maths/trapezoidal_rule.py
>      return y
Yes

2024-10-06 12:30 UTC, jurichar reviewed
The functions seems tested and goodly commented

2024-12-31 01:11 UTC, tianyizheng02 approved these changes

2024-12-31 01:11 UTC, merged