Added max_sum_BST.py
TheAlgorithms/Python pull request #11832
Opened 2024-10-06 15:48 UTC by 1227haran

### Describe your change:

* [X] Add an algorithm?
* [X] Fix a bug or typo in an existing algorithm?
* [X] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [X] This pull request is all my own work -- I have not plagiarized.
* [X] I know that pull requests will not be merged if they fail the automated tests.
* [X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [X] All new Python files are placed inside an existing directory.
* [X] All filenames are in all lowercase characters with no spaces or dashes.
* [X] All functions and variable names follow Python naming conventions.
* [X] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [X] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [X] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [X] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2024-10-06 16:33 UTC, imSanko requested changes
Visit the CONTRIBUTION.md for info about testing the Code before an PR

2024-10-06 16:56 UTC, cclauss commented on data_structures/binary_tree/maximum_sum_bst.py
> +class TreeNode:
Please make this a https://docs.python.org/3/library/dataclasses.html

2024-10-07 06:42 UTC, cclauss commented
On your computer: `python3 -m doctest data_structures/binary_tree/maximum_sum_bst.py`

2024-10-07 06:47 UTC, cclauss commented on data_structures/binary_tree/maximum_sum_bst.py
> +class TreeNode:
See https://github.com/TheAlgorithms/Python/blob/master/data_structures/binary_tree/binary_tree_traversals.py#L10 for a working example.

2024-10-07 08:20 UTC, cclauss commented on data_structures/binary_tree/maximum_sum_bst.py
> +from typing import Optional
```suggestion
```

2024-10-07 08:20 UTC, cclauss commented on data_structures/binary_tree/maximum_sum_bst.py
> +    right: Optional["TreeNode"] = None
```suggestion
    left: TreeNode | None = None
    right: TreeNode | None = None
```

2024-10-07 08:25 UTC, cclauss commented on data_structures/binary_tree/maximum_sum_bst.py
> +def max_sum_bst(root: TreeNode) -> int:
```suggestion
def max_sum_bst(root: TreeNode | None) -> int:
```

2024-10-07 08:32 UTC, cclauss commented on data_structures/binary_tree/maximum_sum_bst.py
> +    def solver(node: TreeNode) -> tuple[bool, int, int, int]:
```suggestion
    def solver(node: TreeNode | None) -> tuple[bool, int, int, int]:
```

2024-10-07 08:36 UTC, cclauss approved these changes
Nice!  Thanks for doing this.

2024-10-07 08:36 UTC, merged