Fixed: #12233
TheAlgorithms/Python pull request #12249
Opened 2024-10-23 13:47 UTC by vedprakash226

I have added a logic that restricts the evaluation of log function if y_true is 0.

* [x] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #12233

2024-10-23 14:36 UTC, kevin1kevin1k commented
- Note that y_true is an array so comparing it to 0 might not be a good idea here, and there are nonzero entries that should be calculated instead of just returning 0.
- I think this is a duplicate of #12237

2024-10-25 04:38 UTC, anandfresh approved these changes

2024-10-27 05:54 UTC, kevin1kevin1k requested changes
Please see my comment in the conversation

> Note that y_true is an array so comparing it to 0 might not be a good idea here, and there are nonzero entries that should be calculated instead of just returning 0.

This causes
`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

2024-10-27 05:55 UTC, kevin1kevin1k commented
@anandfresh I do not think the PR should be approved as it is not correct and do not resolve what the issue intends.

2024-10-27 16:31 UTC, anandfresh commented
> @anandfresh I do not think the PR should be approved as it is not correct and do not resolve what the issue intends.

@kevin1kevin1k - Yes, my bad ! I didn't see it is an array variable . Ideally he has to check if the array length is greater than 0

2024-10-27 16:32 UTC, anandfresh requested changes

2024-10-27 16:32 UTC, anandfresh commented on machine_learning/loss_functions.py
> +    if y_true != 0:
Shouldn't you check the length of the `y_true` array greater than 0?

2024-11-01 08:12 UTC, cclauss commented
Closing tests_are_failing PRs to prepare for Hacktoberfest

2024-11-01 08:12 UTC, closed without merging