#9943 : adding some coverage for string
TheAlgorithms/Python pull request #12301
Opened 2024-10-27 22:40 UTC by Scarfinos

### Describe your change:

#9943

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [X] This pull request is all my own work -- I have not plagiarized.
* [X] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [X] All new Python files are placed inside an existing directory.
* [X] All filenames are in all lowercase characters with no spaces or dashes.
* [X] All functions and variable names follow Python naming conventions.
* [X] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [X] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [X] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [X] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2024-10-28 03:27 UTC, ratchanonsuttawas commented
https://github.com/TheAlgorithms/Python/issues/9943#issue-1930869192


#12301

2024-10-28 03:27 UTC, ratchanonsuttawas commented
> [#9943 (ความคิดเห็น)](https://github.com/TheAlgorithms/Python/issues/9943#issue-1930869192)
> 
> #12301

2024-10-28 03:28 UTC, ratchanonsuttawas commented
> ### อธิบายการเปลี่ยนแปลงของคุณ:
> #9943
> 
> * [ ] เพิ่มอัลกอริทึ่ม?
> * [ ] แก้ไขจุดบกพร่องหรือการพิมพ์ผิดในอัลกอริทึมที่มีอยู่หรือไม่
> * [ ] เพิ่มหรือเปลี่ยน doctests? -- หมายเหตุ: โปรดหลีกเลี่ยงการเปลี่ยนแปลงทั้งโค้ดและการทดสอบในคำขอการดึงครั้งเดียว
> * [ ] เอกสารมีการเปลี่ยนแปลง?
> 
> ### รายการตรวจสอบ:
> * [x] ฉันได้อ่าน[CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md)แล้ว
> * [x] คำขอการดึงนี้เป็นผลงานของฉันทั้งหมด ฉันไม่ได้ลอกเลียนผลงานใคร
> * [x] ฉันทราบว่าคำขอการดึงจะไม่ถูกรวมเข้าด้วยกันหากไม่ผ่านการทดสอบอัตโนมัติ
> * [ ] PR นี้เปลี่ยนแปลงไฟล์อัลกอริทึมเพียงไฟล์เดียวเท่านั้น เพื่อความสะดวกในการตรวจสอบ โปรดเปิด PR แยกต่างหากสำหรับอัลกอริทึมที่แยกจากกัน
> * [x] ไฟล์ Python ใหม่ทั้งหมดจะถูกวางไว้ภายในไดเร็กทอรีที่มีอยู่
> * [x] ชื่อไฟล์ทั้งหมดเป็นตัวอักษรพิมพ์เล็กไม่มีช่องว่างหรือขีดกลาง
> * [x] ฟังก์ชันและชื่อตัวแปรทั้งหมดปฏิบัติตามข้อตกลงการตั้งชื่อของ Python
> * [x] พารามิเตอร์ฟังก์ชันทั้งหมดและค่าส่งคืนจะมี[คำอธิบายประเภท](https://docs.python.org/3/library/typing.html) Python
> * [x] ฟังก์ชั่นทั้งหมดมี[doctests](https://docs.python.org/3/library/doctest.html)ที่ผ่านการทดสอบอัตโนมัติ
> * [x] อัลกอริทึมใหม่ทั้งหมดมีอย่างน้อยหนึ่ง URL ที่ชี้ไปยัง Wikipedia หรือคำอธิบายที่คล้ายคลึงกัน
> * [x] หากคำขอการดึงนี้แก้ไขปัญหาเปิดอยู่หนึ่งรายการหรือหลายรายการ คำอธิบายด้านบนจะรวมถึงหมายเลขปัญหาพร้อม[คำสำคัญปิด](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)ท้ายว่า "แก้ไข #ISSUE-NUMBER"

#12301

2024-10-28 03:33 UTC, ratchanonsuttawas commented on strings/is_valid_email_address.py
> +    if domain.startswith("-") or domain.endswith("-"):
```suggestion
    if domain.startswith("-") or domain.endswith("-"):
```
#12302

2024-10-28 03:33 UTC, ratchanonsuttawas commented on strings/is_valid_email_address.py
> -    if domain.startswith("-") or domain.endswith("."):
#12301

2024-10-28 03:34 UTC, ratchanonsuttawas commented
> > ### อธิบายการเปลี่ยนแปลงของคุณ:
> > #9943
> > 
> > * [x]  เพิ่มอัลกอริทึ่ม?
> > * [x]  แก้ไขจุดบกพร่องหรือการพิมพ์ผิดในอัลกอริทึมที่มีอยู่หรือไม่
> > * [x]  เพิ่มหรือเปลี่ยน doctests? -- หมายเหตุ: โปรดหลีกเลี่ยงการเปลี่ยนแปลงทั้งโค้ดและการทดสอบในคำขอการดึงครั้งเดียว
> > * [x]  เอกสารมีการเปลี่ยนแปลง?
> > 
> > ### รายการตรวจสอบ:
> > 
> > * [x]  ฉันได้อ่าน[CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md)แล้ว
> > * [x]  คำขอการดึงนี้เป็นผลงานของฉันทั้งหมด ฉันไม่ได้ลอกเลียนผลงานใคร
> > * [x]  ฉันทราบว่าคำขอการดึงจะไม่ถูกรวมเข้าด้วยกันหากไม่ผ่านการทดสอบอัตโนมัติ
> > * [x]  PR นี้เปลี่ยนแปลงไฟล์อัลกอริทึมเพียงไฟล์เดียวเท่านั้น เพื่อความสะดวกในการตรวจสอบ โปรดเปิด PR แยกต่างหากสำหรับอัลกอริทึมที่แยกจากกัน
> > * [x]  ไฟล์ Python ใหม่ทั้งหมดจะถูกวางไว้ภายในไดเร็กทอรีที่มีอยู่
> > * [x]  ชื่อไฟล์ทั้งหมดเป็นตัวอักษรพิมพ์เล็กไม่มีช่องว่างหรือขีดกลาง
> > * [x]  ฟังก์ชันและชื่อตัวแปรทั้งหมดปฏิบัติตามข้อตกลงการตั้งชื่อของ Python
> > * [x]  พารามิเตอร์ฟังก์ชันทั้งหมดและค่าส่งคืนจะมี[คำอธิบายประเภท](https://docs.python.org/3/library/typing.html) Python
> > * [x]  ฟังก์ชั่นทั้งหมดมี[doctests](https://docs.python.org/3/library/doctest.html)ที่ผ่านการทดสอบอัตโนมัติ
> > * [x]  อัลกอริทึมใหม่ทั้งหมดมีอย่างน้อยหนึ่ง URL ที่ชี้ไปยัง Wikipedia หรือคำอธิบายที่คล้ายคลึงกัน
> > * [x]  หากคำขอการดึงนี้แก้ไขปัญหาเปิดอยู่หนึ่งรายการหรือหลายรายการ คำอธิบายด้านบนจะรวมถึงหมายเลขปัญหาพร้อม[คำสำคัญปิด](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)ท้ายว่า "แก้ไข #ISSUE-NUMBER"
> 
> #12301

#12301 #12305 #12304 #12303 #12281

2024-10-28 03:34 UTC, ratchanonsuttawas commented
> > > ### อธิบายการเปลี่ยนแปลงของคุณ:
> > > #9943
> > > 
> > > * [x]   เพิ่มอัลกอริทึ่ม?
> > > * [x]   แก้ไขจุดบกพร่องหรือการพิมพ์ผิดในอัลกอริทึมที่มีอยู่หรือไม่
> > > * [x]   เพิ่มหรือเปลี่ยน doctests? -- หมายเหตุ: โปรดหลีกเลี่ยงการเปลี่ยนแปลงทั้งโค้ดและการทดสอบในคำขอการดึงครั้งเดียว
> > > * [x]   เอกสารมีการเปลี่ยนแปลง?
> > > 
> > > ### รายการตรวจสอบ:
> > > 
> > > * [x]   ฉันได้อ่าน[CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md)แล้ว
> > > * [x]   คำขอการดึงนี้เป็นผลงานของฉันทั้งหมด ฉันไม่ได้ลอกเลียนผลงานใคร
> > > * [x]   ฉันทราบว่าคำขอการดึงจะไม่ถูกรวมเข้าด้วยกันหากไม่ผ่านการทดสอบอัตโนมัติ
> > > * [x]   PR นี้เปลี่ยนแปลงไฟล์อัลกอริทึมเพียงไฟล์เดียวเท่านั้น เพื่อความสะดวกในการตรวจสอบ โปรดเปิด PR แยกต่างหากสำหรับอัลกอริทึมที่แยกจากกัน
> > > * [x]   ไฟล์ Python ใหม่ทั้งหมดจะถูกวางไว้ภายในไดเร็กทอรีที่มีอยู่
> > > * [x]   ชื่อไฟล์ทั้งหมดเป็นตัวอักษรพิมพ์เล็กไม่มีช่องว่างหรือขีดกลาง
> > > * [x]   ฟังก์ชันและชื่อตัวแปรทั้งหมดปฏิบัติตามข้อตกลงการตั้งชื่อของ Python
> > > * [x]   พารามิเตอร์ฟังก์ชันทั้งหมดและค่าส่งคืนจะมี[คำอธิบายประเภท](https://docs.python.org/3/library/typing.html) Python
> > > * [x]   ฟังก์ชั่นทั้งหมดมี[doctests](https://docs.python.org/3/library/doctest.html)ที่ผ่านการทดสอบอัตโนมัติ
> > > * [x]   อัลกอริทึมใหม่ทั้งหมดมีอย่างน้อยหนึ่ง URL ที่ชี้ไปยัง Wikipedia หรือคำอธิบายที่คล้ายคลึงกัน
> > > * [x]   หากคำขอการดึงนี้แก้ไขปัญหาเปิดอยู่หนึ่งรายการหรือหลายรายการ คำอธิบายด้านบนจะรวมถึงหมายเลขปัญหาพร้อม[คำสำคัญปิด](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)ท้ายว่า "แก้ไข #ISSUE-NUMBER"
> > 
> > 
> > #12301
> 
> #12301 #12305 #12304 #12303 #12281

2024-10-28 03:36 UTC, ratchanonsuttawas commented
> commit
> 66ab2a1f615aa9d6524d117072c2d454f8a4b816
#12301

2024-10-28 03:38 UTC, ratchanonsuttawas requested changes
> Pull​ Request
#12301

2024-10-28 03:38 UTC, ratchanonsuttawas approved these changes
#12301

2024-10-28 03:39 UTC, ratchanonsuttawas commented
> #12301

2024-10-28 03:56 UTC, ratchanonsuttawas commented on strings/is_valid_email_address.py
> -    if domain.startswith("-") or domain.endswith("."):
> #12301

2024-10-28 03:57 UTC, ratchanonsuttawas commented on strings/is_valid_email_address.py
> +    if domain.startswith("-") or domain.endswith("-"):
> ```suggestion
>     if domain.startswith("-") or domain.endswith("-"):
> ```
> #12302

2024-10-28 04:01 UTC, ratchanonsuttawas approved these changes

2024-11-30 10:51 UTC, shaw-621 commented
documents = ["文档1内容", "文档2内容", "文档3内容"]
target_string = "特定字符串"
count = 0
for doc in documents:
    if target_string in doc:
        count += 1
print(f"{target_string} 在 {count} 篇文档中出现。")

# 若要增加其覆盖范围，可以通过一些文本处理手段，比如在未出现该字符串的文档中适当添加该字符串等。
for doc in documents:
    if target_string not in doc:
        doc += " " + target_string
print("处理后：")
count = 0
for doc in documents:
    if target_string in doc:
        count += 1
print(f"{target_string} 在 {count} 篇文档中出现。")

2024-12-04 14:40 UTC, Scarfinos commented
> documents = ["文档1内容", "文档2内容", "文档3内容"] target_string = "特定字符串" count = 0 for doc in documents: if target_string in doc: count += 1 print(f"{target_string} 在 {count} 篇文档中出现。")
> # 若要增加其覆盖范围，可以通过一些文本处理手段，比如在未出现该字符串的文档中适当添加该字符串等。
> 
> for doc in documents: if target_string not in doc: doc += " " + target_string print("处理后：") count = 0 for doc in documents: if target_string in doc: count += 1 print(f"{target_string} 在 {count} 篇文档中出现。")

Hello, thanks for reviewing my pull request. However, I am not sure sure to understand the link between the loop you are showing me and the doctest I am adding. Also, I do not speak Chinese so I need replies in English to understand.

2025-06-11 21:19 UTC, mindaugl approved these changes

2025-08-31 00:10 UTC, MaximSmolskiy commented
Please separate for several PRs - one file per one PR

2025-08-31 00:10 UTC, closed without merging