Remove_Invalid_Parenthesis.py
TheAlgorithms/Python pull request #12340
Opened 2024-10-31 06:27 UTC by SonjeVilas

### Describe your change:

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2024-11-01 08:22 UTC, imSanko requested changes
[FIX] | This issue for getting things validated backtracking/Remove_Invalid_Parenthesis.py:18:5: N802 Function name `removeInvalidParenthesis` should be lowercase

2024-11-01 12:40 UTC, imSanko requested changes

2024-11-01 12:40 UTC, imSanko commented on backtracking/remove_invalid_parenthesis.py
> +        str = q[0]
Try running pre --commit [ More on Contribution.md ]

2024-12-28 09:50 UTC, tianyizheng02 reviewed
This is plagiarized from https://www.geeksforgeeks.org/remove-invalid-parentheses/

The code is nearly identical, with the only differences being the removal of some parentheses and almost all comments.

You had checked this checkbox in your PR, so you know that we do not plagiarism whatsoever.

> - [x] This pull request is all my own work -- I have not plagiarized.

2024-12-28 09:51 UTC, closed without merging