Fix leap year check
TheAlgorithms/Python pull request #12396
Opened 2024-11-24 04:44 UTC by minh-swinburne

Replace `!=` in `(year % 400) != 0` (line 49) with `==`

Justification: Years that are divisible by 100 (centurian == 100) but not by 400 (year % 400 != 0) are skipped and NOT leap year.

### Describe your change:

* [ ] Add an algorithm?
* [X] Fix a bug or typo in an existing algorithm?
* [ ] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [X] This pull request is all my own work -- I have not plagiarized.
* [X] I know that pull requests will not be merged if they fail the automated tests.
* [X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [X] All new Python files are placed inside an existing directory.
* [X] All filenames are in all lowercase characters with no spaces or dashes.
* [X] All functions and variable names follow Python naming conventions.
* [X] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [X] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [X] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [X] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2024-11-25 12:11 UTC, imSanko requested changes
Parenthesize `a and b` expressions when chaining `and` and `or` together, to make the precedence clear

2024-12-30 07:49 UTC, minh-swinburne reviewed
I've changed the incorrect conditional operator and ensure clarity using parentheses

2024-12-30 14:48 UTC, tianyizheng02 requested changes

2024-12-30 14:48 UTC, tianyizheng02 commented on other/doomsday.py
> +        if (year % 4 != 0) or ((centurian == 0) and (year % 400 != 0))
```suggestion
        if year % 4 != 0 or (centurian == 0 and year % 400 != 0)
```
I believe some of the parentheses are unnecessary, order of operations should still be clear due to the higher precedence of `%`, `==`, and `!=`.

2025-01-16 02:01 UTC, minh-swinburne commented on other/doomsday.py
> +        if (year % 4 != 0) or ((centurian == 0) and (year % 400 != 0))
You're right! The expression looks much better without redundant parentheses 👍

2025-01-18 02:05 UTC, imSanko approved these changes

2025-01-18 03:07 UTC, tianyizheng02 approved these changes

2025-01-18 03:07 UTC, merged