Tests electronics/electric_conductivity.py  #9943
TheAlgorithms/Python pull request #12437
Opened 2024-12-15 16:44 UTC by juliaaragao

### Describe your change:

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2024-12-16 13:01 UTC, imSanko requested changes
Nice changes

2024-12-30 12:14 UTC, cclauss commented on conversions/rec_to_pol.py
> +def rec_to_pol(real: float, img: float) -> tuple:
```suggestion
def rectangular_to_polar(real: float, img: float) -> tuple[float, float]:
```
or `cartesian_to_polar`

2024-12-30 12:14 UTC, cclauss commented on conversions/rec_to_pol.py
> +import doctest
```suggestion
```

2024-12-30 12:14 UTC, cclauss commented on conversions/rec_to_pol.py
> +if __name__ == "__main__":
```suggestion
if __name__ == "__main__":
    import doctest

```

2024-12-30 12:16 UTC, cclauss commented on DIRECTORY.md
> +  * [Rec To Pol](conversions/rec_to_pol.py)
```suggestion
```
This is done automatically as discussed in CONTRIBUTING.md

2024-12-30 12:21 UTC, cclauss commented on conversions/rectangular_to_polar.py
> +
```suggestion
```

2024-12-30 12:27 UTC, cclauss commented on conversions/rectangular_to_polar.py
> +    >>> rec_to_pol(10000,99999)
```suggestion
    >>> rectangular_to_polar(5,-5)
    (7.07, -45.0)
    >>> rectangular_to_polar(-1,1)
    (1.41, 135.0)
    >>> rectangular_to_polar(-1,-1)
    (1.41, -135.0)
    >>> rectangular_to_polar(1e-10,1e-10)
    (0.0, 45.0)
    >>> rectangular_to_polar(-1e-10,1e-10)
    (0.0, 135.0)
    >>> rectangular_to_polar(9.75,5.93)
    (11.41, 31.31)
    >>> rectangular_to_polar(10000,99999)
```

2024-12-30 12:36 UTC, cclauss approved these changes
Nice!  A few changes for readability.

2024-12-30 12:36 UTC, merged