Update pigeon_sort.py
TheAlgorithms/Python pull request #2359
Opened 2020-08-27 11:31 UTC by wuyudi

### **Describe your change:**

Update pigeon_sort.py

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-08-27 11:34 UTC, TravisBuddy commented
Hey @wuyudi,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.com&#x2F;TheAlgorithms&#x2F;Python&#x2F;builds&#x2F;181627724">View build log</a>

###### TravisBuddy Request Identifier: 52421fa0-e859-11ea-a3ad-29627dfdd765

2020-08-28 18:26 UTC, swapnanildutta approved these changes

2020-08-28 18:26 UTC, swapnanildutta approved these changes

2020-09-25 17:00 UTC, mateuszz0000 requested changes

2020-09-25 17:00 UTC, mateuszz0000 commented on sorts/pigeon_sort.py
> +    # Finds the minimum and maximum of the array.
Could we remove unnecessary comments? Code should be self documented

2020-10-22 12:45 UTC, 53jk1 requested changes

2020-10-22 12:45 UTC, 53jk1 commented on sorts/pigeon_sort.py
>      # Compute the variables
unnecesary comment

2020-11-26 01:15 UTC, poyea approved these changes
Thank you for your pull request!🤩

2020-11-30 12:49 UTC, xcodz-dot approved these changes
@dhruvmanila check this out

2020-11-30 14:56 UTC, dhruvmanila approved these changes
LGTM!

2020-11-30 14:59 UTC, merged