createminimum number of refills.py
TheAlgorithms/Python pull request #2388
Opened 2020-09-02 15:56 UTC by Saptarshi-prog

Added a new algorithm

### **Describe your change:**

* [x ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x ] This pull request is all my own work -- I have not plagiarized.
* [ x] I know that pull requests will not be merged if they fail the automated tests.
* [x ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ x] All new Python files are placed inside an existing directory.
* [x ] All filenames are in all lowercase characters with no spaces or dashes.
* [ x] All functions and variable names follow Python naming conventions.
* [ x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-09-02 16:00 UTC, TravisBuddy commented
Hey @Saptarshi-prog,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.com&#x2F;TheAlgorithms&#x2F;Python&#x2F;builds&#x2F;182453981">View build log</a>

###### TravisBuddy Request Identifier: 607ebe30-ed35-11ea-b6ba-27fe84eba218

2020-09-02 17:17 UTC, cclauss commented
GitHub task list work like this https://github.blog/2014-04-28-task-lists-in-all-markdown-documents/

Please do not check the task that says that you have read CONTRIBUTING.md if you have not done so.

2020-09-09 06:24 UTC, spamegg1 commented
@Saptarshi-prog Build log says
> 6     E225 missing whitespace around operator
4     E226 missing whitespace around arithmetic operator
5     E231 missing whitespace after ','
2     E262 inline comment should start with '# '
1     E302 expected 2 blank lines, found 1
1     E305 expected 2 blank lines after class or function definition, found 1

Can be easily fixed by running `black` on your file. [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md) explains it. Please read it.

2020-09-09 07:06 UTC, cclauss requested changes

2020-09-09 07:06 UTC, cclauss commented on greedy_method/minimum_number_of_refills.py
> +def MinRefills(x,n,L):
Single letter variable names are old school as discussed in CONTRIBUTING.md
* No python type hints
* No doctests

2020-10-09 15:25 UTC, closed without merging