Wiggle sort
TheAlgorithms/Python pull request #2419
Opened 2020-09-12 19:57 UTC by BriseBalloches

### **Describe your change:**

Improved wiggle_sort.py, mainly with type hinting and doctests.

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [X] Documentation change?

### **Checklist:**
* [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [X] This pull request is all my own work -- I have not plagiarized.
* [X] I know that pull requests will not be merged if they fail the automated tests.
* [X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [X] All filenames are in all lowercase characters with no spaces or dashes.
* [X] All functions and variable names follow Python naming conventions.
* [X] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [X] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-09-20 09:22 UTC, mateuszz0000 requested changes

2020-09-20 09:22 UTC, mateuszz0000 commented on sorts/wiggle_sort.py
> +def wiggle_sort(nums: list):
Please add return hint. Please also provide doctest with float numbers.

2020-09-24 16:49 UTC, BriseBalloches commented on sorts/wiggle_sort.py
> +def wiggle_sort(nums: list):
Done.

2020-09-24 19:15 UTC, cclauss commented
@mateuszz0000 If this is ready to merge then please approve and then click Squash & merge.

2020-09-25 07:17 UTC, mateuszz0000 approved these changes

2020-09-25 07:18 UTC, merged

2020-09-25 08:49 UTC, cclauss commented
@mateuszz0000 Thanks.  Are there any other open PRs that you think should be landed?