Web programming contribution
TheAlgorithms/Python pull request #2436
Opened 2020-09-16 11:43 UTC by niranjanhegde144

### **Describe your change:**
Added Currency Converter Program to web_programming directory. 

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-09-16 11:47 UTC, TravisBuddy commented
Hey @niranjanhegde144,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.com&#x2F;TheAlgorithms&#x2F;Python&#x2F;builds&#x2F;184661652">View build log</a>

###### TravisBuddy Request Identifier: 62e11780-f812-11ea-8f9f-a900ee46d44b

2020-09-25 07:32 UTC, niranjanhegde144 commented
Clauss Can you take a look at this

2020-09-25 08:13 UTC, cclauss requested changes

2020-09-25 08:13 UTC, cclauss commented on web_programming/currency_converter.py
> +    return res["error_message"]
```suggestion
def convert_currency(
    from: str = "USD",
    to: str = "INR",
    amount: float = 1.0,
    api_key: str = API_KEY
) -> str:
    """https://www.amdoren.com/currency-api/"""
    res = requests.get(URL_BASE, data=locals()).json()
    return str(res["amount"] if res["error"] == 0 else res["error_message"])
```
There are nice advantages in requests and locals() if our function parameter names exactly match the API.

2020-09-25 08:13 UTC, cclauss commented on web_programming/currency_converter.py
> +    )
```suggestion
    print(
        convert_currency(
            input("Enter from currency: ").strip(),
            input("Enter to currency: ").strip(),
            float(input("Enter the amount: ").strip())
        )
    )
```

2020-09-26 10:02 UTC, TravisBuddy commented
Hey @niranjanhegde144,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.com&#x2F;TheAlgorithms&#x2F;Python&#x2F;builds&#x2F;186803401">View build log</a>

###### TravisBuddy Request Identifier: 61ca28d0-ffdf-11ea-9882-0125ab0f75bf

2020-09-26 10:08 UTC, TravisBuddy commented
## Travis tests have failed

Hey @niranjanhegde144,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: 268e7950-ffe0-11ea-9882-0125ab0f75bf

2020-09-26 10:58 UTC, cclauss commented
https://docs.travis-ci.com/user/environment-variables/#default-environment-variables

2020-11-21 07:54 UTC, cclauss approved these changes

2020-11-21 08:04 UTC, merged