Reduce complexity linear_discriminant_analysis.
TheAlgorithms/Python pull request #2452
Opened 2020-09-19 21:31 UTC by NumberPiOso

Tracking issue #2128
### **Describe your change:**

* [X] Fix a bug or typo in an existing algorithm?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.

Not really know how to create doctests for this kind of input functions.

2020-09-19 21:33 UTC, TravisBuddy commented
Hey @NumberPiOso,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.com&#x2F;TheAlgorithms&#x2F;Python&#x2F;builds&#x2F;185375607">View build log</a>

###### TravisBuddy Request Identifier: bde32920-fabf-11ea-8017-3168cf2e728c

2020-10-27 17:34 UTC, NumberPiOso commented
How do I get for someone to approve this?

2020-11-10 03:07 UTC, dhruvmanila requested changes
Sorry for taking so long, just a few small changes and this is good to go.

2020-11-10 03:07 UTC, dhruvmanila commented on machine_learning/linear_discriminant_analysis.py
> +                print(f"Your entered value is {user_input}. {err_msg}")
```suggestion
                print(f"{user_input}: {err_msg}")
```

2020-11-10 14:40 UTC, NumberPiOso commented on machine_learning/linear_discriminant_analysis.py
> +            print("Your entered value is not numerical!")
Applied

2020-11-10 14:45 UTC, NumberPiOso commented
@dhruvmanila 

I just get one check from the Travis CI system, nothing from pre-commit. 

Does this mean that it is good to go or that something is bad?

2020-11-10 15:07 UTC, dhruvmanila commented
Your branch is based off on a very old commit, the `psf/black` automated action is deprecated. Also, do not start the workflow runs on your forked copy as some action might be automated which will make commits to your branch and that will come in this pull request as well.

Always update your fork copy to keep in sync with the main repository. If you want to make a pull request, make a branch from the latest copy and then make your changes in that branch.

2020-11-10 15:09 UTC, dhruvmanila commented on machine_learning/linear_discriminant_analysis.py
> +            print("Your entered value is not numerical!")
This was not applied or a GitHub action reverted the changes.

2020-11-10 20:20 UTC, NumberPiOso commented
Yes I get it, I suppose I always start the branches from the lastest commit.

But this pull request has been open since 19 September, almost two months, so I guess this explains why it is  200 commits behind.

If it is better to start another pull request cherry picking this changes or something let me know.

2020-11-11 02:32 UTC, dhruvmanila commented
I think rebasing should be enough, if that won't work then try cherry-picking otherwise another PR seems like the easiest option :)

2020-11-11 02:34 UTC, dhruvmanila approved these changes
This seems good to go. Thank you for your contribution! And sorry for the late review.

2020-11-11 02:35 UTC, merged

2020-11-12 16:05 UTC, NumberPiOso commented
Thank you for the review.