Update area.py
TheAlgorithms/Python pull request #2524
Opened 2020-09-30 16:14 UTC by SabariGanesh-K

Added Area for Rhombhus

### **Describe your change:**

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-09-30 16:19 UTC, TravisBuddy commented
Hey @SabariGanesh-K,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.com&#x2F;TheAlgorithms&#x2F;Python&#x2F;builds&#x2F;187445055">View build log</a>

###### TravisBuddy Request Identifier: aace97d0-0338-11eb-8abf-036a378110f7

2020-09-30 16:33 UTC, TravisBuddy commented
Hey @SabariGanesh-K,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.com&#x2F;TheAlgorithms&#x2F;Python&#x2F;builds&#x2F;187446942">View build log</a>

###### TravisBuddy Request Identifier: a65e5a80-033a-11eb-8abf-036a378110f7

2020-10-03 06:28 UTC, SabariGanesh-K commented
I have added a new shape for Area. All checks have been passed :)

2020-10-03 21:23 UTC, poyea commented
When I type `Area for Rhombus` into Google, it asks for 2 diagonals. I guess this is the more accepted version of it right?

2020-10-03 21:24 UTC, poyea requested changes

2020-10-03 21:24 UTC, poyea commented on maths/area.py
> +def area_rhombhus(base: float, height: float) -> float:
```suggestion
def area_rhombus(base: float, height: float) -> float:
```

2020-10-03 21:24 UTC, poyea commented on maths/area.py
> +    return 1 / 2 * base * height
Probably make it take two diagonals as parameters.

2020-10-04 14:20 UTC, poyea approved these changes
Thank you for your pull request!🤩

2020-10-04 14:20 UTC, merged