math/sieve of eras: add type hitns and doctest
TheAlgorithms/Python pull request #2627
Opened 2020-10-01 23:56 UTC by pikulet

### **Describe your change:**

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-10-22 12:42 UTC, 53jk1 approved these changes

2020-11-23 05:28 UTC, dhruvmanila requested changes

2020-11-23 05:28 UTC, dhruvmanila commented on maths/sieve_of_eratosthenes.py
> +        raise ValueError("Please enter positive integers.")
```suggestion
        raise ValueError(f"{n}: Invalid input, please enter a positive integer.")

```

2020-11-23 05:36 UTC, dhruvmanila approved these changes
Thank you for your contribution!

2020-11-23 05:37 UTC, merged