Fixed coding style problem 33 fixes: #2786
TheAlgorithms/Python pull request #2849
Opened 2020-10-05 14:30 UTC by bobluppes

### **Describe your change:**

Changed the function name to `solution` for project euler problem 33.

* [ ] Add an algorithm?
* [ x ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [ x ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ x ] This pull request is all my own work -- I have not plagiarized.
* [ x ] I know that pull requests will not be merged if they fail the automated tests.
* [ x ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ x ] All new Python files are placed inside an existing directory.
* [ x ] All filenames are in all lowercase characters with no spaces or dashes.
* [ x ] All functions and variable names follow Python naming conventions.
* [ x ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ x ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ x ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ x ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-10-06 03:18 UTC, dhruvmanila requested changes

2020-10-06 03:18 UTC, dhruvmanila commented on project_euler/problem_33/sol1.py
> +def solution(digit_len: int) -> str:
Please add the default value for the parameter `digit_len` such that when called without any arguments `solution()` returns the right answer to the solution.

2020-10-08 12:38 UTC, bobluppes commented
Hey @dhruvmanila, sorry, just saw this today. I have updated the code accordingly

2020-10-16 08:58 UTC, dhruvmanila commented
I'm closing this PR as this issue has been fixed.
Refer: #2786

2020-10-16 08:58 UTC, closed without merging