Cleanup Project Euler Problem 01
TheAlgorithms/Python pull request #2900
Opened 2020-10-06 04:44 UTC by CMeza99

### **Describe your change:**
(replacing PR #2893)
* clean up docstrs
* improve coding-style

&nbsp;

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

Part of Issues: #2786, #2510

2020-10-06 12:03 UTC, dhruvmanila requested changes

2020-10-09 06:11 UTC, CMeza99 commented on project_euler/problem_01/sol5.py
> +    return sum(i for i in range(n) if i % 3 == 0 or i % 5 == 0)
dropped commit

2020-10-09 06:11 UTC, CMeza99 commented on project_euler/problem_01/sol1.py
> +    return sum(e for e in range(3, n) if e % 3 == 0 or e % 5 == 0)
dropped commit

2020-10-10 05:32 UTC, dhruvmanila approved these changes

2020-10-10 05:33 UTC, merged