Project Euler 62 Solution
TheAlgorithms/Python pull request #3029
Opened 2020-10-08 05:44 UTC by peteryao7

### **Describe your change:**
Adds a solution and explanation for Project Euler 62.

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-10-08 06:49 UTC, peteryao7 commented
I'm not sure why there's a second Travis build running. It's been going for over 20 minutes now.

2020-10-08 07:26 UTC, peteryao7 commented
Pushing a new commit seems to have fixed the problem.

2020-10-14 21:35 UTC, peteryao7 commented
Hi @dhruvmanila, it's been almost a week and my PRs haven't been reviewed yet. I know you're probably swamped with hundreds of open PRs right now, but please look at my solutions for problem 62 (here), [65](https://github.com/TheAlgorithms/Python/pull/3035), [70](https://github.com/TheAlgorithms/Python/pull/3041), and [206](https://github.com/TheAlgorithms/Python/pull/3042), and let me know if there are any issues I need to fix. Thank you :)

2020-10-15 01:49 UTC, dhruvmanila commented
Closing and re-opening the PR for Travis CI to rerun with a new configuration.

2020-10-15 02:06 UTC, dhruvmanila requested changes

2020-10-15 02:06 UTC, dhruvmanila commented on project_euler/problem_62/sol1.py
> +    return "".join(digits)
```suggestion
    return "".join(sorted(list(str(num ** 3))))
```

2020-10-15 02:06 UTC, dhruvmanila commented on project_euler/problem_62/sol1.py
> +    print(solution())
```suggestion
    print(f"{solution() = }")
```

2020-10-15 02:07 UTC, dhruvmanila commented
You opened 4 PRs at a time when we eplicitly mentioned to open only one PR at a time. If you cannot follow that, then please don't expect us to review all your PRs at one go just because you think it's more important than others.

2020-10-15 02:10 UTC, dhruvmanila commented on project_euler/problem_62/sol1.py
> +    return "".join(digits)
One line is also faster than the 4 lines:
```console
$ python -m timeit -s "num = 999" "''.join(sorted(list(str(num ** 3))))"
200000 loops, best of 5: 1.16 usec per loop

$ python -m timeit -s "num = 999" "cube=num ** 3;digits=[str(x) for x in str(cube)];digits.sort();''.join(digits)"
100000 loops, best of 5: 2.07 usec per loop
```

2020-10-15 02:11 UTC, peteryao7 commented
> You opened 4 PRs at a time when we eplicitly mentioned to open only one PR at a time. If you cannot follow that, then please don't expect us to review all your PRs at one go just because you think it's more important than others.

Got it. I saw other PRs made after mine that got reviewed and merged sooner, so I was concerned about getting skipped over.

I'll make the changes later tonight.

2020-10-15 03:28 UTC, peteryao7 commented
@dhruvmanila Finished the changes. Thanks again for getting back to me! I will make similar changes to my other 3 PRs so they look like this one.

2020-10-15 03:31 UTC, dhruvmanila commented on project_euler/problem_62/sol1.py
> +    >>> solution(5)
Please remove the test for the answer as that is done by us using `validate_solutions` script. This will create duplication in testing.

2020-10-15 03:32 UTC, dhruvmanila commented
Yes, that would make it easy for us to review. Thank you for doing that :)

2020-10-15 03:40 UTC, peteryao7 commented
@dhruvmanila Answer test case removed.

2020-10-15 03:43 UTC, dhruvmanila approved these changes
Looks good! Thank you for your contribution!

2020-10-15 03:43 UTC, merged