[Project Euler] Added type hints and refactored the code a bit for Problem 14
TheAlgorithms/Python pull request #3047
Opened 2020-10-08 10:16 UTC by sgalpha01

Continuing #2786

- Added type hints
- Added default argument values for validate_solutions script
- Refactored the code

### **Describe your change:**

* [x] Fix a bug or typo in an existing algorithm?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).

2020-10-08 11:29 UTC, dhruvmanila requested changes

2020-10-08 11:29 UTC, dhruvmanila commented on project_euler/problem_14/sol1.py
> +        "Longest Collatz sequence under {} is produced by {} with length {}".format(
Nice idea.
Please use `f-strings` as mentioned in CONTRIBUTING.md

2020-10-08 11:29 UTC, dhruvmanila commented on project_euler/problem_14/sol2.py
> +        "Longest Collatz sequence under {} is produced by {} with length {}".format(
`f-strings`

2020-10-08 11:29 UTC, dhruvmanila commented on project_euler/problem_14/sol1.py
> +def solution(n: int = 1000000) -> dict:
Use `from typing import Dict` and then `Dict[<type>, <type>,...]`

2020-10-08 11:29 UTC, dhruvmanila commented on project_euler/problem_14/sol2.py
> +def collatz_sequence(n: int) -> list:
Use `from typing import List` and then `List[<type>,...]`

2020-10-08 11:29 UTC, dhruvmanila commented on project_euler/problem_14/sol2.py
> +def solution(n: int = 1000000) -> dict:
Same as above.

2020-10-08 12:34 UTC, sgalpha01 commented
Hey @dhruvmanila, thanks for reviewing. I have pushed some changes. Can you please check if it still need some styling modification?

2020-10-08 15:47 UTC, dhruvmanila commented
This gives us answer in an incorrect type. 
https://travis-ci.com/github/TheAlgorithms/Python/jobs/396914178#L250-L256

2020-10-08 16:40 UTC, sgalpha01 commented
Sure!

2020-10-09 03:02 UTC, dhruvmanila approved these changes

2020-10-09 03:03 UTC, merged