Added solution for Project Euler problem 77. Fixes: #2695
TheAlgorithms/Python pull request #3132
Opened 2020-10-09 16:40 UTC by fpringle

Name: Prime summations

It is possible to write ten as the sum of primes in exactly five different ways:

7 + 3
5 + 5
5 + 3 + 2
3 + 3 + 2 + 2
2 + 2 + 2 + 2 + 2

What is the first value which can be written as the sum of primes in over five thousand different ways?

Reference: [https://projecteuler.net/problem=77](url)

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-10-15 07:27 UTC, dhruvmanila reviewed
### Announcement:

@fpringle

*This message is sent to all pull requests which are **OPEN, NOT MERGED, not containing 'wontfix' label and contains 'Project Euler' or 'Project' or 'Euler' (case doesn't matter) in their title**. If this message doesn't apply to your pull request, please ignore this.*

### Message:

This is to notify all the users submitting a pull request for the Project Euler solution that the [README.md](https://github.com/TheAlgorithms/Python/blob/master/project_euler/README.md) file has been updated with all the style requirements necessary for the directory and solution files. ***Please read through it and make all the necessary changes required to your submission.***

2020-10-22 12:14 UTC, 53jk1 approved these changes

2020-10-29 07:00 UTC, dhruvmanila commented on project_euler/problem_077/sol1.py
> +    return 0
`0` becomes an answer as well. Maybe you want `None`?

2020-10-29 19:56 UTC, fpringle commented on project_euler/problem_077/sol1.py
> +CACHE_PARTITION = {0: {1}}
Thanks for the tip!

2020-11-06 16:19 UTC, dhruvmanila requested changes
Please provide descriptive parameter/variable names wherever the length is 1.

2020-11-27 15:35 UTC, fpringle commented
> Please provide descriptive parameter/variable names wherever the length is 1.

Done

2020-11-27 16:07 UTC, dhruvmanila approved these changes
LGTM!

2020-11-27 16:08 UTC, merged