created new cipher
TheAlgorithms/Python pull request #3205
Opened 2020-10-11 17:16 UTC by radadiyamohit81

if you like my code, merge it and add the label as `hacktoberfest-accepted`

### **Describe your change:**

* [* ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [ *] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ *] This pull request is all my own work -- I have not plagiarized.
* [ *] I know that pull requests will not be merged if they fail the automated tests.
* [ *] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ *] All new Python files are placed inside an existing directory.
* [ *] All filenames are in all lowercase characters with no spaces or dashes.
* [ *] All functions and variable names follow Python naming conventions.
* [ *] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-10-11 17:23 UTC, TravisBuddy commented
## Travis tests have failed

Hey @radadiyamohit81,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: 7d1a6ec0-0be6-11eb-a59b-f3f3774a9991

2020-10-17 06:06 UTC, radadiyamohit81 reviewed
updated

2020-10-17 06:50 UTC, cclauss commented on ciphers/vigenera_cipher_dictionary_hacker.py
> +    fo.close()
```suggestion
def hackVigenere(ciphertext: str) -> str:
    with open('dictionary.txt') as in_file:
        words = in_file.readlines()
```

2020-10-17 06:51 UTC, cclauss commented on ciphers/vigenera_cipher_dictionary_hacker.py
> +    fo.close()
Python type hints are required in this repo as discussed in CONTRIBUTING.md.

2020-10-17 08:02 UTC, radadiyamohit81 reviewed
UPdate the file

2020-10-17 08:30 UTC, cclauss commented
Please run your code thru psf/black as discussed in CONTRIBUTING.md.

2020-10-17 12:35 UTC, TravisBuddy commented
## Travis tests have failed

Hey @radadiyamohit81,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: 3046daa0-1075-11eb-af89-615b230ba186

2020-10-17 13:12 UTC, cclauss requested changes

2020-10-17 13:12 UTC, cclauss commented on ciphers/vigenera_cipher_dictionary_hacker.py
> +    hackedMessage = hackVigenere(ciphertext)
```suggestion
    hacked_message = hack_vigenere(ciphertext)
```
Pythonic naming please as discussed in CONTRIBUTING.md.  Please repeat for all variable and function names.

2020-10-17 13:12 UTC, cclauss commented on ciphers/vigenera_cipher_dictionary_hacker.py
> +            response = input("> ")
As discussed in CONTRIBUTING.md, algorithmic functions should not print() and input() will hang our automated testing.

2020-10-17 14:22 UTC, cclauss commented on ciphers/vigenera_cipher_dictionary_hacker.py
> +            print(f"Key {str(word)} : {decryptedText[:100]}")
```suggestion
            print(f"Key {word} : {decryptedText[:100]}")
```

2020-10-17 14:22 UTC, TravisBuddy commented
## Travis tests have failed

Hey @radadiyamohit81,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: 26b55e80-1084-11eb-af89-615b230ba186

2020-10-17 14:22 UTC, cclauss commented on ciphers/vigenera_cipher_dictionary_hacker.py
> +            print(f"Enter D for done, or just press Enter to continue breaking:")
```suggestion
            print("Enter D for done, or just press Enter to continue breaking:")
```
No {}, no f

2020-10-17 14:23 UTC, cclauss commented on ciphers/vigenera_cipher_dictionary_hacker.py
> +        print(f"Failed to hack encryption")
```suggestion
        print("Failed to hack encryption")
```
No {}, no f.

2020-10-17 14:25 UTC, radadiyamohit81 commented on ciphers/vigenera_cipher_dictionary_hacker.py
> +            print(f"Enter D for done, or just press Enter to continue breaking:")
ok got it

2020-10-18 12:18 UTC, closed without merging