modified vigenere_cipher.py
TheAlgorithms/Python pull request #3265
Opened 2020-10-13 18:30 UTC by sharyudongre

### **Describe your change:**

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-10-13 18:36 UTC, ridhishjain commented
@sharyudongre some of the checks are failing, please look into it before requesting a review

2020-10-14 07:37 UTC, cclauss requested changes
How are these modifications an improvement over the current code?  I do not see the advantage.

2020-10-14 07:37 UTC, cclauss commented on ciphers/vigenere_cipher.py
> +class cipher:
```suggestion
class Cipher:
```

2020-10-14 09:17 UTC, sharyudongre commented
Thanks a lot. I will do the suggested changes.But will the checks pass
after it?

On Wed, 14 Oct 2020, 1:07 pm Christian Clauss, <notifications@github.com>
wrote:

> *@cclauss* requested changes on this pull request.
>
> How are these modifications an improvement over the current code? I do not
> see the advantage.
> ------------------------------
>
> In ciphers/vigenere_cipher.py
> <https://github.com/TheAlgorithms/Python/pull/3265#discussion_r504463165>:
>
> > -
>
> -def encryptMessage(key, message):
>
> -    """
>
> -    >>> encryptMessage('HDarji', 'This is Harshil Darji from Dharmaj.')
>
> -    'Akij ra Odrjqqs Gaisq muod Mphumrs.'
>
> -    """
>
> -    return translateMessage(key, message, "encrypt")
>
> -
>
> -
>
> -def decryptMessage(key, message):
>
> -    """
>
> -    >>> decryptMessage('HDarji', 'Akij ra Odrjqqs Gaisq muod Mphumrs.')
>
> -    'This is Harshil Darji from Dharmaj.'
>
> -    """
>
> -    return translateMessage(key, message, "decrypt")
>
> +class cipher:
>
>
> ⬇️ Suggested change
>
> -class cipher:
>
> +class Cipher:
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/TheAlgorithms/Python/pull/3265#pullrequestreview-508069858>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMYC62U5KYC5GEJBSO3I56DSKVIMFANCNFSM4SPNN32Q>
> .
>

2020-10-14 09:31 UTC, cclauss commented
You may have to make other changes to make the tests pass.

The more important question is https://github.com/TheAlgorithms/Python/pull/3265#pullrequestreview-508069858

2020-10-14 09:48 UTC, sharyudongre commented
> How are these modifications an improvement over the current code? I do not see the advantage.

Using a class gives the code object oriented design

2020-10-14 09:51 UTC, closed without merging