added script to perform quantum entanglement
TheAlgorithms/Python pull request #3270
Opened 2020-10-13 20:27 UTC by nkpro2000sr

#2923 

### **Describe your change:**

added script to perform quantum entanglement with a simple quantum circuit.

* [X] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [X] This pull request is all my own work -- I have not plagiarized.
* [X] I know that pull requests will not be merged if they fail the automated tests.
* [X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [X] All new Python files are placed inside an existing directory.
* [X] All filenames are in all lowercase characters with no spaces or dashes.
* [X] All functions and variable names follow Python naming conventions.
* [X] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [X] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [X] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [X] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-10-13 20:51 UTC, TravisBuddy commented
## Travis tests have failed

Hey @nkpro2000sr,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: d5301b40-0d95-11eb-9111-f326d0cb7f09

2020-10-13 21:10 UTC, TravisBuddy commented
## Travis tests have failed

Hey @nkpro2000sr,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: 5f25e080-0d98-11eb-9111-f326d0cb7f09

2020-10-14 07:47 UTC, cclauss requested changes
Please either rebase this pull request against master or create a new PR that ___only___ modifies `quantum/quantum_entanglement.py`.  As discussed in CONTRIBUTING.md, pull requests should not modify `DIRECTORY.md` because this file is rebuilt by GitHub Actions.

2020-10-14 07:47 UTC, cclauss commented on quantum/quantum_entanglement.py
> +    return counts
```suggestion
    return job.result().get_counts(circuit)
```

2020-10-14 09:37 UTC, nkpro2000sr commented
@cclauss 
i moved changes in **ciphers/affine_cipher.py** to a new pr #3281 
please consider reviewing that also.

2020-10-14 10:25 UTC, cclauss approved these changes

2020-10-14 10:25 UTC, merged