Added solution to Project Euler problem 301
TheAlgorithms/Python pull request #3343
Opened 2020-10-15 18:29 UTC by KumarUniverse

### **Describe your change:**

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-10-15 18:39 UTC, TravisBuddy commented
## Travis tests have failed

Hey @KumarUniverse,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: a4930340-0f15-11eb-9bff-abeacd856cb9

2020-10-15 19:32 UTC, TravisBuddy commented
## Travis tests have failed

Hey @KumarUniverse,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: 049676d0-0f1d-11eb-9bff-abeacd856cb9

2020-10-15 19:35 UTC, TravisBuddy commented
## Travis tests have failed

Hey @KumarUniverse,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: a271fe60-0f1d-11eb-9bff-abeacd856cb9

2020-10-15 20:06 UTC, mateuszz0000 approved these changes

2020-10-15 20:06 UTC, mateuszz0000 commented on project_euler/problem_301/sol1.py
> +    lossCount = 0
loss_count

2020-10-15 20:07 UTC, mateuszz0000 submitted a review, later dismissed
Missclick

2020-10-15 20:15 UTC, TravisBuddy commented
## Travis tests have failed

Hey @KumarUniverse,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: 1bb3c3d0-0f23-11eb-9bff-abeacd856cb9

2020-10-15 20:16 UTC, KumarUniverse commented
Why does the  pre-commit run keep failing? The log say isort failed but I don't know what that means.

2020-10-15 20:20 UTC, KumarUniverse reviewed
Hi, I renamed my lossCount variable to loss_count. Can you review it please?

2020-10-15 23:35 UTC, KumarUniverse commented
I managed to pass all 3 checks and made the requested changes. Can you please accept my pull request? Thank you.

2020-10-16 10:24 UTC, dhruvmanila commented on project_euler/problem_301/sol1.py
> +        if x(i, 2 * i, 3 * i) == 0:
I don't think you need a function for such a small thing :)

2020-10-16 10:24 UTC, dhruvmanila commented on project_euler/problem_301/sol1.py
> +    print(solution())
```suggestion
    print(f"{solution() = }")
```

2020-10-16 15:31 UTC, dhruvmanila commented
Your solution is taking 3 minutes to run. You need to optimize it to bring it down to seconds. Try not to use brute force in here as time complexity matters in here.

https://travis-ci.com/github/TheAlgorithms/Python/jobs/400702745#L243

```
============================= slowest 10 durations =============================
167.57s call     project_euler/validate_solutions.py::test_project_euler[problem_301/sol1.py]
25.52s call     project_euler/validate_solutions.py::test_project_euler[problem_014/sol1.py]
20.23s call     project_euler/validate_solutions.py::test_project_euler[problem_014/sol2.py]
15.14s call     project_euler/validate_solutions.py::test_project_euler[problem_009/sol1.py]
11.44s call     project_euler/validate_solutions.py::test_project_euler[problem_010/sol1.py]
7.69s call     project_euler/validate_solutions.py::test_project_euler[problem_010/sol2.py]
5.45s call     project_euler/validate_solutions.py::test_project_euler[problem_034/sol1.py]
3.68s call     project_euler/validate_solutions.py::test_project_euler[problem_112/sol1.py]
3.67s call     project_euler/validate_solutions.py::test_project_euler[problem_012/sol1.py]
3.66s call     project_euler/validate_solutions.py::test_project_euler[problem_012/sol2.py]
```

2020-10-16 16:45 UTC, KumarUniverse commented
I have optimized my solution and committed the changes.

2020-10-25 03:31 UTC, dhruvmanila requested changes

2020-10-25 03:31 UTC, dhruvmanila commented on project_euler/problem_301/sol1.py
> +    2178309
You do not need to test the answer. It is being tested by our script. Please remove these two lines.

2020-10-25 03:31 UTC, dhruvmanila commented on project_euler/problem_301/sol1.py
> +    fib_ind = exponent + 2
Descriptive variable names please.

2020-10-25 03:31 UTC, dhruvmanila commented on project_euler/problem_301/sol1.py
> +    return nim_loss_count
```suggestion

    return int(fib)
```

2020-10-26 13:57 UTC, KumarUniverse commented
I have made the requested changes to the code @dhruvmanila.

2020-11-01 10:54 UTC, dhruvmanila approved these changes
Thank you for your contribution!

2020-11-01 10:57 UTC, merged