Median of Two Arrays
TheAlgorithms/Python pull request #3554
Opened 2020-10-19 11:40 UTC by anneCoder1805

This code finds the median of two arrays (which may or may not be sorted initially).
Example: 
Enter elements of an array: 1 5 4 2
Enter elements of another array: 1 7 4 2 7
The median of two arrays is :  4

### **Describe your change:**

* [✓ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [✓] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [✓] This pull request is all my own work -- I have not plagiarized.
* [✓] I know that pull requests will not be merged if they fail the automated tests.
* [✓] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [✓] All new Python files are placed inside an existing directory.
* [✓] All filenames are in all lowercase characters with no spaces or dashes.
* [✓] All functions and variable names follow Python naming conventions.
* [✓] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [✓] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [✓] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [✓] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-10-19 11:45 UTC, TravisBuddy commented
## Travis tests have failed

Hey @anneCoder1805,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: a6753050-1200-11eb-af4f-e3a6e0ba4ce0

2020-10-19 11:49 UTC, TravisBuddy commented
## Travis tests have failed

Hey @anneCoder1805,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: 08572c10-1201-11eb-af4f-e3a6e0ba4ce0

2020-10-19 12:22 UTC, jessica02200 approved these changes

2020-10-20 06:41 UTC, TravisBuddy commented
## Travis tests have failed

Hey @anneCoder1805,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: 2f17a1b0-129f-11eb-af4f-e3a6e0ba4ce0

2020-10-20 06:53 UTC, cclauss commented
Please reformat this code with psf/black as discussed in CONTRIBUTING.md so that the tests below turn green.

2020-10-20 06:59 UTC, cclauss requested changes

2020-10-20 06:59 UTC, cclauss commented on other/median_of_two_arrays.py
> +        return (list3[a] + list3[a - 1]) / 2
These lines are `unreachable code` because of the `return` statement on lin 13

2020-10-20 06:59 UTC, cclauss commented on other/median_of_two_arrays.py
> +def findMedianArrays(nums1, nums2):
```suggestion
def find_median_arrays(nums1, nums2):
```
Python naming as discussed in CONTRIBUTING.md.  Please add type hints on this line and doctests.

2020-10-20 06:59 UTC, cclauss commented on other/median_of_two_arrays.py
> +        a = int(len(list3)/2)
Please use [divmod](https://docs.python.org/3/library/functions.html#divmod)

2020-10-20 06:59 UTC, cclauss commented on other/median_of_two_arrays.py
> +    n2 = list(map(int, input("Enter elements of another array: ").split()))
Please use list comprehensions instead of list(map()) as discussed in CONTRIBUTING.md.

2020-10-20 06:59 UTC, cclauss commented on other/median_of_two_arrays.py
> +    print("The median of two arrays is: ", findMedianArrays(n1, n2))
Please use f-strings as discussed in CONTRIBUTING.md

2020-10-20 07:08 UTC, cclauss commented on other/median_of_two_arrays.py
> +    print(f'The median of two arrays is: {m}')
```suggestion
    print(f'The median of two arrays is: {findMedianArrays(n1, n2)}')    
```

2020-10-20 07:10 UTC, anneCoder1805 commented
@cclauss , thanks for letting me know. I will format the the code accordingly :)

2020-10-20 07:17 UTC, TravisBuddy commented
## Travis tests have failed

Hey @anneCoder1805,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: 4613a080-12a4-11eb-8230-47bfa5f272e1

2020-10-20 07:26 UTC, TravisBuddy commented
## Travis tests have failed

Hey @anneCoder1805,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: 8f00cbf0-12a5-11eb-8230-47bfa5f272e1

2020-10-20 07:33 UTC, cclauss commented on other/median_of_two_arrays.py
> +    if divmod(len(list3), 2).[1] == 1:
```suggestion
    div, mod = divmod(len(list3), 2)
    if mod == 1:
```

2020-10-20 07:35 UTC, cclauss commented on other/median_of_two_arrays.py
> +    list3 = nums1 + nums2
```suggestion
    all_numbers = nums1 + nums2
```
Remove duplication and use a more self-documenting variable name.

2020-10-20 08:29 UTC, cclauss commented on other/median_of_two_arrays.py
>  def find_median_arrays(nums1, nums2):
OK...  There is a lot here so let me explain...
1. We add [type hints](https://docs.python.org/3/library/typing.html) to say that `nums` are list of ints and the the function returns an int.
2. We add [doctests](https://docs.python.org/3/library/doctest.html) which we can run locally with the command `python3 -m doctest -v median_of_two_arrays.py`
```suggestion
from typing import List


def median_of_two_arrays(nums1: List[int], nums2: List[int]) -> int:
    """
    >>> median_of_two_arrays((9, 1), (7, 3, 5))
    5
    >>> median_of_two_arrays([1], [0, 1000])
    1
    >>> median_of_two_arrays([-10], [10])
    0
    >>> median_of_two_arrays([-10], [10, 5])
    5
    >>> median_of_two_arrays([0], [3])
    1
    >>> median_of_two_arrays([], [0])
    0
    >>> median_of_two_arrays([], [])
    Traceback (most recent call last):
      ...
    IndexError: list index out of range
    """
```
Are the answers in the doctests what we expect them to be?

2020-10-20 08:32 UTC, cclauss commented on other/median_of_two_arrays.py
> +    all_numbers.sort()
```suggestion
    all_numbers = sorted(nums1 + nums2)
```

2020-10-20 09:32 UTC, anneCoder1805 commented
@cclauss 
Thanks a lot for helping me out wherever I got stuck. This is really a great learning experience for me. I am really grateful to you for this help.

2020-10-20 10:07 UTC, cclauss commented on other/median_of_two_arrays.py
>          a = int(len(all_numbers) / 2)
```suggestion
    if mod == 1:
        return all_numbers[div]
    else:
        return (all_numbers[div] + all_numbers[div - 1]) / 2
```
(and delete the rest of the lines in the function)

I am a bit crazy so I would have written it all on one line as:
```python
     return all_numbers[div] if mod else (all_numbers[div] + all_numbers[div - 1]) / 2
```
but the four-line version is probably easier to think about.

2020-10-20 10:09 UTC, cclauss commented on other/median_of_two_arrays.py
> +    print(f"The median of two arrays is: {median_of_two_arrays(array_1, array_2)}")
```suggestion
    array_1 = [float(x) for x in input("Enter the elements of first array: ").split()]
    array_2 = [float(x) for x in input("Enter the elements of second array: ").split()]
    print(f"The median of two arrays is: {median_of_two_arrays(array_1, array_2)}")

```
Python is smart enough to know that that list comprehension will generate a `List[float]` without our hint.  I tend to use type hints just for function parameters and return types to document these things for the caller of the funtion.

2020-10-20 10:36 UTC, cclauss approved these changes
Awesome work!  Thanks for your persistence.

2020-10-20 10:38 UTC, merged

2020-10-20 10:40 UTC, cclauss commented
https://docs.python.org/3/library/statistics.html#statistics.median ;-)

2020-10-20 20:22 UTC, jessica02200 approved these changes

2020-10-22 04:24 UTC, jessica02200 approved these changes

2020-10-22 04:47 UTC, jessica02200 approved these changes

2020-10-22 04:47 UTC, jessica02200 approved these changes