Greedy candy
TheAlgorithms/Python pull request #3669
Opened 2020-10-23 14:03 UTC by siddharthzs

### **Describe your change:**
Leetcode 135: Distribute Candy
There are N children standing in a line. Each child is assigned a rating value. You are giving candies to these children subjected to the following requirements:
      Each child must have at least one candy. 
      Children with a higher rating get more candies than their neighbors.
What is the minimum candies you must give?

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-10-23 14:08 UTC, TravisBuddy commented
## Travis tests have failed

Hey @siddharthzs,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: 2f89eee0-1539-11eb-aff7-dd8cbeb067cc

2020-10-23 14:37 UTC, jmothiki commented
awesome

2020-10-23 19:30 UTC, TravisBuddy commented
## Travis tests have failed

Hey @siddharthzs,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: 2803d780-1566-11eb-94fa-edf6748ec8ed

2020-10-23 19:39 UTC, TravisBuddy commented
## Travis tests have failed

Hey @siddharthzs,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: 6474e7d0-1567-11eb-94fa-edf6748ec8ed

2020-10-23 19:51 UTC, TravisBuddy commented
## Travis tests have failed

Hey @siddharthzs,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: 27cbd030-1569-11eb-94fa-edf6748ec8ed

2020-10-24 06:05 UTC, xcodz-dot requested changes

2020-10-24 06:05 UTC, xcodz-dot commented on greedy_method/distribute_candy.py
> +    >>> 7
```suggestion

    >>> distribute_candy([1, 2])
    3
    >>> distribute_candy([1, 5, 2, 1])
    7
    >>> distribute_candy([1, 3, 2, 1])
    7
```

This is the correct syntax of doctests, i have made the changes for you. please accept them

2020-10-24 09:21 UTC, siddharthzs commented
Thank you @xcodz-dot, If you wouldn't have helped me I wouldn't be able to pass the test.

2020-10-24 09:21 UTC, xcodz-dot commented
This seems to be good to go

@Kush1101 @dhruvmanila, Check this out

2020-11-09 08:41 UTC, dhruvmanila commented
This pull request contains an additional file which seems like a mistake. Please make the necessary changes to only include the file containing the `Greedy candy` algorithm or open a new pull request for it.

2020-12-16 18:25 UTC, closed without merging