add project euler for problem 50
TheAlgorithms/Python pull request #3697
Opened 2020-10-24 06:36 UTC by willtryagain

### **Describe your change:**

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-10-24 06:46 UTC, xcodz-dot requested changes
required changes to type hinting of return value

2020-10-24 06:46 UTC, xcodz-dot commented on project_euler/problem_050/sol1.py
> +def solution(limit: int = 1_000_000):
```suggestion
def solution(limit: int = 1_000_000) -> int:
```
type hinting for return values

2020-10-24 06:46 UTC, xcodz-dot commented on project_euler/problem_050/sol1.py
> +def sieve_of_eratosthenes(limit: int) -> [list]:
```suggestion
def sieve_of_eratosthenes(limit: int) -> list:
```
brackets are not needed

2020-10-24 06:46 UTC, xcodz-dot commented on project_euler/problem_050/sol1.py
> +def is_prime(number: int) -> [bool]:
```suggestion
def is_prime(number: int) -> bool:
```
brackets are not required

2020-10-24 06:47 UTC, xcodz-dot commented on project_euler/problem_050/sol1.py
> +    print(f"{solution() = }")
```suggestion
    print(f"{solution() = }")

```
PEP 8 fix required for action to complete

2020-10-24 06:52 UTC, xcodz-dot commented on project_euler/problem_050/sol1.py
> +def sieve_of_eratosthenes(limit: int) -> [list]:
@willtryagain this is also needed to be accepted

2020-10-24 06:53 UTC, xcodz-dot commented on project_euler/problem_050/sol1.py
> +    print(f"{solution() = }")
@willtryagain, this will fix a github workflow error

2020-10-24 07:09 UTC, xcodz-dot commented on project_euler/problem_050/sol1.py
> +
```suggestion

```
These are too many new lines

2020-10-24 07:10 UTC, xcodz-dot commented on project_euler/problem_050/sol1.py
> +
```suggestion
```

These are too many newlines

2020-10-24 07:32 UTC, Takosaga commented
You have the same pre-commit hooks as I did, these helped me figure it out
https://stackoverflow.com/questions/30884131/remove-trailing-spaces-automatically-or-with-a-shortcut

https://www.geeksforgeeks.org/python-code-formatting-using-black/

2020-10-24 07:34 UTC, xcodz-dot commented
> You have the same pre-commit hooks as I did, these helped me figure it out
> https://stackoverflow.com/questions/30884131/remove-trailing-spaces-automatically-or-with-a-shortcut
> 
> https://www.geeksforgeeks.org/python-code-formatting-using-black/

You are right @Takosaga, @willtryagain can use black, it will be good for his work to get done instantly.

2020-10-24 14:32 UTC, willtryagain commented
> You have the same pre-commit hooks as I did, these helped me figure it out
> https://stackoverflow.com/questions/30884131/remove-trailing-spaces-automatically-or-with-a-shortcut
> 
> https://www.geeksforgeeks.org/python-code-formatting-using-black/

Thank you @Takosaga, now it does pass black. Can you tell 
How do we fix End of File?

2020-10-24 15:36 UTC, Takosaga commented
@willtryagain oh that is a different hook than me, but seems like it is Fixing project_euler/problem_050/__init__.py. That file should be an empty file. It took me while to figure out this stuff but there is some more information in the .pre-commit-config.yaml for the hooks

2020-10-24 16:36 UTC, xcodz-dot commented
@willtryagain, try using black on `__init__.py` file as well. It might fix it

2020-10-24 16:39 UTC, xcodz-dot commented on project_euler/problem_050/__init__.py
> +
```suggestion


```
If black does not help than apply this change

2020-10-26 19:49 UTC, Takosaga commented
This should be how your **__init__.py** file should be. That might be what is catching your hook
![empty](https://user-images.githubusercontent.com/32805901/97220871-2c442d00-179a-11eb-80a3-45d8729f7544.PNG)

2020-10-27 09:57 UTC, xcodz-dot requested changes

2020-10-27 09:57 UTC, xcodz-dot commented on project_euler/problem_050/__init__.py
> +
```suggestion
```

Try deleting this line

2020-10-27 15:08 UTC, xcodz-dot commented
rename `__init__.py.txt` -> `__init__.py`

2020-10-28 04:47 UTC, xcodz-dot requested changes

2020-10-28 04:47 UTC, xcodz-dot commented on project_euler/problem_050/__init__.py
> +
Try making a completly empty `__init__.py` file with no content and not even a single new line

2020-10-29 05:48 UTC, xcodz-dot commented
I got the perfect solution:
* Download the repository
* Make sure you Have git installed
* run `pip install pre-commit`
* go to the repository directory and run `pre-commit install`
* also run `pre-commit run --all-files`

This is garuenteed to fix your issues

2020-11-08 02:58 UTC, dhruvmanila commented
Thank you for your contribution but we already have another solution for it which was opened and got accepted. Maybe try solving another problem which is not present in our directory?

2020-12-16 18:25 UTC, closed without merging