Clock hands
TheAlgorithms/Python pull request #3761
Opened 2020-10-26 12:24 UTC by verdantfire

### **Describe your change:**
The function will return the angle between the hour and minute hands for an input time in hours and minutes

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-10-26 12:58 UTC, itsvinayak commented
Hey @verdantfire codespell fails, please have a look

2020-11-08 15:26 UTC, dhruvmanila requested changes

2020-11-08 15:26 UTC, dhruvmanila commented on other/angle_between_clock_hands.py
> +ValueError: Hour value out of bounds (0-12)
Please put the `doctest` in function docstring.

2020-11-08 15:26 UTC, dhruvmanila commented on other/angle_between_clock_hands.py
> +        raise ValueError("Hour value out of bounds (0-12)")
```suggestion
        raise ValueError("Hour value out of bounds [0-12]")
```
Square brackets are used to indicate inclusiveness and round brackets are used for exclusiveness.

2020-11-08 15:26 UTC, dhruvmanila commented on other/angle_between_clock_hands.py
> +        raise ValueError("Minutes value out of bounds (0-59)")
```suggestion
        raise ValueError("Minutes value out of bounds [0-59]")
```
Same as above.

2021-01-16 10:16 UTC, closed without merging