mastodon_toot_using_api.py
TheAlgorithms/Python pull request #3771
Opened 2020-10-27 05:52 UTC by sulochanaviji

daily one tamil word toot on mastodon using mastodon api key

### **Describe your change:**
tooting daily one tamil word on mastodon using mastodon api key
database name : wordcorpus(located in base4app server)

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-10-27 05:55 UTC, sulochanaviji commented
tooting daily one tamil word on mastodon using mastodon api key

2020-10-27 05:57 UTC, TravisBuddy commented
## Travis tests have failed

Hey @sulochanaviji,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: 3b513980-1819-11eb-bc4d-2726ba7bdf50

2020-10-27 06:02 UTC, cclauss commented
Publishing you private API key is not good for security reasons.  It would be a good idea to generate a new security key on the service and not publish that security key.

2020-10-30 16:08 UTC, TravisBuddy commented
## Travis tests have failed

Hey @sulochanaviji,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: 12343760-1aca-11eb-ae00-6f9b88d90b9e

2020-10-30 16:12 UTC, TravisBuddy commented
## Travis tests have failed

Hey @sulochanaviji,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: a3a1ad90-1aca-11eb-ae00-6f9b88d90b9e

2020-10-30 16:16 UTC, cclauss requested changes

2020-10-30 16:16 UTC, cclauss commented on ciphers/password_encryption.py
> +password_val=input("Enter the password :")
This line will hang our automated testing as discussed in CONTRIBUTING.md.

This looks more like a how-to-use demonstration than an algorithm as discussed in CONTRIBUTING.md.

2020-10-30 16:46 UTC, TravisBuddy commented
## Travis tests have failed

Hey @sulochanaviji,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


###### TravisBuddy Request Identifier: 6b1b8450-1acf-11eb-ae00-6f9b88d90b9e

2020-12-08 10:21 UTC, closed without merging