Added code for Regular Expression Matching
TheAlgorithms/Python pull request #3809
Opened 2020-10-28 13:36 UTC by Vinaysukhwal

### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-11-05 17:28 UTC, mrmaxguns requested changes

2020-11-05 17:28 UTC, mrmaxguns commented on dynamic_programming/regular_expression_matching.py
> +def isMatch(self, s: str, p: str) -> bool:
Python naming conventions state that function names should be in snake case and one letter variable names are not acceptable. Also, there is no need for a `self` argument as the function isn't a class method:

```python
def is_match(check_string: str, pattern: str) -> bool:
    ...
```

2020-11-05 17:28 UTC, mrmaxguns commented on dynamic_programming/regular_expression_matching.py
> +        dp = [[0 for i in range(len(p)+1)] for j in range(len(s)+1)]
What is `dp`? Variable names should be short, but descriptive.

2020-11-05 17:28 UTC, mrmaxguns commented on dynamic_programming/regular_expression_matching.py
> +                if(p[j-1]==s[i-1] or p[j-1]=="."):
The parentheses are unnecessary and redundant:

```python
if p[j - 1] == s[i - 1] or p[j - 1] == ".":
    ...
```

2020-11-05 17:28 UTC, mrmaxguns commented on dynamic_programming/regular_expression_matching.py
> +                elif(j>1 and p[j-1]=="*"):
These parentheses can be removed.

2020-11-27 17:26 UTC, xcodz-dot commented
### This PR might get closed within 4 days from now:
* No doctests
* Pre-commit failed
* No author response

### Fix:
* Give a comment out here so we know you are here.
* Make required changes

You can ask me if you need to

2021-01-04 22:24 UTC, closed without merging