Stepwise Regression Example Added
TheAlgorithms/Python pull request #3818
Opened 2020-10-29 11:10 UTC by falconcode16

### **Describe your change:**

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-11-05 16:58 UTC, mrmaxguns commented
Python filenames should end with the extension `.py`. The filename should be in snake_case, i.e. `stepwise_regression.py`. The file bypassed all checks since it wasn't recognized as a Python file.

2020-11-05 17:05 UTC, mrmaxguns requested changes

2020-11-05 17:05 UTC, mrmaxguns commented on machine_learning/Stepwise Regression
> +data = load_boston()
You should put the test dataset and `X` and `y` variables in an `if __name__ == "__main__"` block at the end of the file:

```python
# End of file
if __name__ == "__main__":
    data = load_boston()
    X = pd.DataFrame(data.data, columns=data.feature_names)
    y = data.target

    result = stepwise_selection(X, y)

    print('resulting features:')
    print(result)

2020-11-05 17:05 UTC, mrmaxguns commented on machine_learning/Stepwise Regression
> +def stepwise_selection(X, y,
Add type hints to the function https://docs.python.org/3/library/typing.html

2020-11-05 17:05 UTC, mrmaxguns commented on machine_learning/Stepwise Regression
> +print(result)
Add a newline at the end of the file. Black should do this for you.

2020-11-08 15:13 UTC, dhruvmanila commented
Please read the [Contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md) before opening a pull request.

Closing this PR as it contains an extensionless file.

2020-11-08 15:13 UTC, closed without merging