Added solution for Project Euler problem 102
TheAlgorithms/Python pull request #3825
Opened 2020-10-29 17:12 UTC by Cosine42

### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-11-27 06:26 UTC, xcodz-dot commented
fix:
* `pip install pre-commit`
* `pre-commit run -a` at root of repo (this might show it failed but it did not)

2020-11-27 06:30 UTC, xcodz-dot requested changes
Shall fix flake8

2020-11-27 06:30 UTC, xcodz-dot commented on project_euler/problem_102/sol1.py
> +Problem statement: Three distinct points are plotted at random on a Cartesian plane, for which -1000 ≤ x, y ≤ 1000, such that a triangle is formed.
```suggestion
Problem statement: Three distinct points are plotted at random 
on a Cartesian plane, for which -1000 ≤ x, y ≤ 1000, such that a triangle is formed.
```

2020-11-27 06:30 UTC, xcodz-dot commented on project_euler/problem_102/sol1.py
> +Using triangles.txt (right click and 'Save Link/Target As...'), a 27K text file containing the co-ordinates of one thousand "random" triangles, find the number of triangles for which the interior con
```suggestion
Using triangles.txt (right click and 'Save Link/Target As...'), a 27K text file containing
 the co-ordinates of one thousand "random" triangles, find the number of triangles 
 for which the interior contains the origin.
```

2020-11-27 06:30 UTC, xcodz-dot commented on project_euler/problem_102/sol1.py
> +NOTE: The first two examples in the file represent the triangles in the example given above.
```suggestion
NOTE: The first two examples in the file represent the triangles in
 the example given above.
```

2020-12-23 09:51 UTC, dhruvmanila commented
@algorithms-keeper review

2020-12-23 10:37 UTC, xcodz-dot requested changes
snake case naming convention

2020-12-23 10:37 UTC, xcodz-dot commented on project_euler/problem_102/sol1.py
> +def isInside(
```suggestion
def is_inside(
```

2020-12-23 10:37 UTC, xcodz-dot commented on project_euler/problem_102/sol1.py
> +        if isInside(*list(map(float, line.split(",")))):
```suggestion
        if is_inside(*list(map(float, line.split(",")))):
```

2021-02-07 18:33 UTC, closed without merging