Add adfgvx_cipher.py
TheAlgorithms/Python pull request #3841
Opened 2020-10-30 20:59 UTC by oops-creator

### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-10-30 21:13 UTC, oops-creator commented
Some checks are failing. The problems seems to be incompatibility between flake8 and black, namely flake8 is not allowing whitespace before ':' but black adds the white space whenever I run the corresponding command. Can anyone please guide me on how to fix the conflict.

2020-11-04 15:11 UTC, mrmaxguns commented
That is strange. What are the commands that you use for `flake8` and `black`?

2020-11-04 15:37 UTC, oops-creator commented
I am using flake8 as linter in vscode and running 
flake8 adfgvx_cipher.py --ignore=E203,W503  --max-line-length=88 --show-source 
and
python -m black adfgvx_cipher.py

2020-11-05 01:25 UTC, mrmaxguns commented
I tried to reproduce this issue. By running black and then flake8, (the commands you specified above) both commands exited with `0`, so everything is compatible. I have no idea why the checks are failing (probably the `--ignore=E203,W503` flag was not specified for pre-commit).

2020-11-05 01:26 UTC, mrmaxguns commented
This looks like an issue with the pre-commit system itself.

2020-11-05 01:28 UTC, mrmaxguns commented
Try to reproduce the issue locally by running black, then pep8 and running and `pre-commit run --all-files`. (make sure you have pre-commit installed with `pip install pre-commit`)

2020-11-05 12:15 UTC, oops-creator commented
I dont know what the issue was but I reinstalled flake8 and black and it seems to be working now. I will make a new pull request now. Thanks for the help. Hope I didnt waste your time.

2020-11-05 16:25 UTC, mrmaxguns requested changes
In this case, exceptions are preferred over `sys.exit` due to the fact that exceptions provide a traceback (the user of the algorithm will be able to see where the problem occurred) and can also be easily handled by the user in `try`, `except` blocks.

2020-11-05 16:25 UTC, mrmaxguns commented on ciphers/adfgvx_cipher.py
> +        sys.exit("Please make sure that key length is 36")
Raise an exception instead of `sys.exit`:

```python
raise ValueError("Please make sure that key length is 36")
```

2020-11-05 16:25 UTC, mrmaxguns commented on ciphers/adfgvx_cipher.py
> +import sys
Remove the import

2020-11-05 16:25 UTC, mrmaxguns commented on ciphers/adfgvx_cipher.py
> +        sys.exit("Please make sure that key length is 36")
Change to exception

2020-11-06 05:46 UTC, oops-creator commented
Thanks for the input. I have done the suggested edits.

2020-12-13 22:36 UTC, closed without merging