@RonDingDing Check initial grid availability for backtracking/sudoku.py
TheAlgorithms/Python pull request #3849
Opened 2020-10-31 08:30 UTC by RonDingDing

### **Describe your change:**

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

```python
initial_grid = [
    [3, 0, 6, 5, 0, 8, 4, 0, 0],
    [5, 2, 0, 0, 0, 0, 0, 0, 0],
    [0, 8, 7, 0, 0, 0, 0, 3, 1],
    [0, 0, 3, 0, 1, 0, 0, 8, 0],
    [9, 0, 0, 8, 6, 3, 0, 0, 5],
    [0, 5, 0, 0, 9, 0, 6, 0, 0],
    [1, 3, 0, 0, 0, 0, 2, 5, 0],
    [0, 0, 0, 0, 0, 0, 0, 7, 4],
    [0, 0, 5, 2, 0, 6, 3, 0, 0],
]
```

In the previous code, if you change 9 at the fifth line to 5, the program will give you a solution. But the output does not conform to the definition of sudoku. It means the program is not checking the input at all. So I add some validation of the input, specifying the grid to be 9*9 2D-list of 1-9.

2020-11-05 16:06 UTC, mrmaxguns requested changes

2020-11-10 03:36 UTC, RonDingDing commented on backtracking/sudoku.py
> +def check_original_solvable(grid) -> bool:
Do I need to modify it?

2020-11-12 01:54 UTC, RonDingDing commented
???

2020-12-23 05:18 UTC, RonDingDing commented
??

2020-12-30 06:40 UTC, closed without merging