Added first solution to problem 135
TheAlgorithms/Python pull request #4035
Opened 2020-12-14 13:44 UTC by sharmapulkit04

### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-12-17 17:43 UTC, poyea approved these changes
Thank you for your pull request!🤩

2020-12-17 17:48 UTC, poyea commented on project_euler/problem_135/sol1.py
> +            count += 1
```suggestion
    count = sum(1 if x == 10 else 0 for x in frequency[1:limit])
```

2020-12-18 09:01 UTC, sharmapulkit04 commented on project_euler/problem_135/sol1.py
> +            count += 1
Done!

2020-12-18 09:44 UTC, dhruvmanila requested changes
One minor tweak and this is good to go!

2020-12-18 09:44 UTC, dhruvmanila commented on project_euler/problem_135/sol1.py
> +    count = sum(1 if x == 10 else 0 for x in frequency[1:limit])
```suggestion
    count = sum(1 for x in frequency[1:limit] if x == 10)
```
No point in adding 0.

2020-12-18 17:56 UTC, sharmapulkit04 commented on project_euler/problem_135/sol1.py
> +    count = sum(1 if x == 10 else 0 for x in frequency[1:limit])
Done!

2020-12-19 06:15 UTC, dhruvmanila approved these changes
LGTM! 🎉

2020-12-19 06:16 UTC, merged