Fixed shell sort
TheAlgorithms/Python pull request #4038
Opened 2020-12-16 10:47 UTC by shellhub

### **Describe your change:**

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](hxtps://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-12-16 10:53 UTC, cclauss commented
I do not quite understand the title of this PR.  In what way is the current implementation broken?

2020-12-16 11:02 UTC, shellhub commented
> I do not quite understand the title of this PR. In what way is the current implementation broken?

We should't insert value instead of swapping elements of array.

2020-12-16 12:02 UTC, mateuszz0000 commented
Is your implementation improve performance or what? If so please write proper tests for proof that your solution is better than already exists.

2020-12-16 12:03 UTC, mateuszz0000 requested changes
Need additional tests for performance

2020-12-16 19:20 UTC, poyea commented
Maybe we can strictly follow this?: https://en.wikipedia.org/wiki/Shellsort#Pseudocode 
Sometimes it's just a matter of styles.

2020-12-16 19:21 UTC, poyea requested changes
We may add a reference to the wiki page as well.

2020-12-17 07:52 UTC, shellhub commented
@poyea Done. Please review again.

2020-12-17 17:36 UTC, poyea commented on sorts/shell_sort.py
> +https://en.wikipedia.org/wiki/Shellsort#Pseudocode
I would leave the first line like this
```suggestion
"""
This is a Python implementation of the shell sort algorithm.

Reference: https://en.wikipedia.org/wiki/Shellsort#Pseudocode
```

2020-12-17 17:38 UTC, poyea approved these changes
I would approve this as the original version has really no reference to the algorithm (or at least, the implementation didn't strictly follow the algorithm). Thank you for your pull request!🤩

2020-12-17 17:38 UTC, poyea commented on sorts/shell_sort.py
> +            while j >= gap and insert_value < collection[j - gap]:
```suggestion
            while j >= gap and collection[j - gap] > insert_value:
```
for readability

2020-12-18 01:03 UTC, shellhub commented
@poyea Done

2020-12-18 07:16 UTC, shellhub commented
@mateuszz0000 Can you review again. Thanks :)

2020-12-18 09:39 UTC, mateuszz0000 approved these changes

2020-12-18 09:39 UTC, merged