Added code to merge two trees
TheAlgorithms/Python pull request #4121
Opened 2021-01-15 00:00 UTC by jindal2309

### **Describe your change:** 

**Merge two binary trees**
*Problem Description:* Given two binary tree, return the merged tree.
The rule for merging is that if two nodes overlap, then put the value sum of
both nodes to the new value of the merged node. Otherwise, the NOT null node
will be used as the node of the new tree.

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2021-01-17 04:16 UTC, ruppysuppy requested changes
Doctest for `main` is irrelevant, please implement all other suggestions made by `algorithms-keeper`

2021-01-18 06:25 UTC, jindal2309 commented on data_structures/binary_tree/merge_two_binary_trees.py
> +def main() -> None:
Done.

2021-01-18 06:25 UTC, jindal2309 commented on data_structures/binary_tree/merge_two_binary_trees.py
> +def main() -> None:
Done

2021-01-18 06:25 UTC, jindal2309 commented on data_structures/binary_tree/merge_two_binary_trees.py
> +def merge_two_binary_trees(tree1: Node, tree2: Node) -> Node:
Done

2021-01-18 07:38 UTC, ruppysuppy approved these changes

2021-01-18 07:38 UTC, merged