Create quickmultiply.py
TheAlgorithms/Python pull request #4403
Opened 2021-05-05 16:30 UTC by Rohit-beep-droid

### **Describe your change:**

Made a simple multiplication function which returns the multiplication of two integers

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2021-05-06 08:27 UTC, cclauss commented on maths/quickmultiply.py
> +def test_quick_multiply()
```suggestion
def test_quick_multiply():
```

2021-05-29 16:16 UTC, mrmaxguns requested changes
Hello! The error is due to invalid indentation. A fix is suggested in the review. After fixing the error, you may want to run Black in order to format the code according to best practices.

I actually don't believe that this PR should be merged, though. The function is simply a wrapper of a Python operator, although one could make an argument that it is still an algorithm. I'd like to hear your thoughts on this.

2021-05-29 16:16 UTC, mrmaxguns commented on maths/quickmultiply.py
> +assert 81 == test_quick_multiply(9,9)
The error is due to invalid indentation. Note that I added two spaces of indentation to be consistent with the rest of the file, but 4 spaces of indentation throughout the whole file are preferred.

```suggestion
  """
  >>> test_quick_multiply()
  """
  assert -25 == test_quick_mutiply(-5,5)
  assert 1000 == test_quick_mutiply(-10,-10)
  assert 0 == test_quick_multiply(0,1000)
  assert 81 == test_quick_multiply(9,9)
```

2021-05-29 17:20 UTC, cclauss commented
Closed as this is not an algorithm but a how-to-use as discussed in CONTRIBUTING.md.

2021-05-29 17:20 UTC, closed without merging