Added Hexadecimal to Binary Conversion
TheAlgorithms/Python pull request #4413
Opened 2021-05-11 23:53 UTC by lucasa1212

### **Describe your change:**
Added hexadecimal to binary conversion

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2021-05-13 11:30 UTC, kambum285 approved these changes

2021-05-16 19:33 UTC, onlinejudge95 requested changes
More doc tests covering the paths like empty string provided or paths where the initial string is not a hexadecimal string.

2021-05-16 19:34 UTC, onlinejudge95 requested changes

2021-05-16 19:34 UTC, onlinejudge95 commented on conversions/hexadecimal_to_binary.py
> +    >>> hex_to_binary("")
Need to fix the given doctest

2021-05-29 15:56 UTC, mrmaxguns commented
Hello! It looks like this algorithm has [already been implemented](https://github.com/TheAlgorithms/Python/blob/master/conversions/hex_to_bin.py). However, the other implementation of the algorithm uses bitwise operators to accomplish the conversion, so this may be OK.

Please also note that pre-commit is failing due to a test failure. Please fix this error by fixing mistakes in the doctests or in the code itself.

2021-06-06 13:36 UTC, onlinejudge95 commented
Last call, let's wait for 1-2 days then let's close it as the author is not responding

2021-07-15 11:32 UTC, closed without merging