Censor Function
TheAlgorithms/Python pull request #4450
Opened 2021-05-22 10:45 UTC by meg-1

### **Describe your change:**
Put the censor algorithm into a function

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2021-05-23 14:18 UTC, Jenil-S requested changes

2021-05-23 14:18 UTC, Jenil-S commented on strings/censor.py
> +def censor(txt, word):
I think you should update this function as
`def censor(txt,word) -> None:`

2021-05-26 09:30 UTC, Txbias commented on strings/censor.py
> +      txt_lst[txt_lst.index(word1)] = "*" * len(word1)
You could make this a little more efficient by using ```for index, word1 in enumerate(txt_lst)```. 
That way you already have the index and don't need to call ```txt_lst.index(word1)```. Instead you just use the variable ```index```.

2021-05-29 15:44 UTC, mrmaxguns commented
Hello. It looks like you haven't run `black` on the code. Black can be installed with `pip install black` (assuming you also have `pip` installed). Then, you can run `black your_file.py` (replacing `your_file` with the actual file path). This will automatically format the code according to relevant Python standards.

2021-07-08 08:47 UTC, closed without merging