Add catalan_numbers.py
TheAlgorithms/Python pull request #4455
Opened 2021-05-26 17:30 UTC by Kommandat

### **Describe your change:**
* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### Additional Notes

Excited to make my first contribution to The Algorithms! Catalan numbers are a sequence in mathematics that represent answers to many combinatorics problems. They can be calculated using a recurrence relation and we can use tabulation (similarly to how we can for the Fibonacci sequence). I thought this best fit in the "dynamic_programming" folder given we're using tabulation to compute the sequence.

All work is my own, but I did take a look at the existing [C++ Catalan number algorithm](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/dynamic_programming/catalan_numbers.cpp) and [Python Fibonacci algorithm ](https://github.com/TheAlgorithms/Python/blob/master/dynamic_programming/fibonacci.py) for inspiration and best practices. If this is approved, I hope to contribute to Algorithms-Explanation as well.

Please let me know if you have any feedback!

Sources:
[1] https://brilliant.org/wiki/catalan-numbers/
[2] https://en.wikipedia.org/wiki/Catalan_number

2021-05-26 17:42 UTC, Kommandat commented on dynamic_programming/catalan_numbers.py
> +    def __init__(self, N: int) -> None:
I added a comment explaining N's function below this line and I don't think a more descriptive variable name is necessary

2021-05-27 19:55 UTC, appgurueu commented
I don't like the unneeded OOP.

2021-05-29 14:23 UTC, mrmaxguns requested changes
Hello. Thanks for your contribution. I performed a review. If you disagree with the changes I suggested, feel free to explain your disagreement by commenting on the review.

Mostly, I suggested changes to avoid unwanted side-effects. These changes are based on the following contribution guideline:
> have minimal side effects (Ex. print(), plot(), read(), write()).

Also, when the user enters erroneous input, an exception should be raised, instead of it simply being printed (this applies only to the algorithm itself, not in the `if __name__ == "__main__"` block).
> raise Python exceptions (ValueError, etc.) on erroneous input values

2021-05-29 14:23 UTC, mrmaxguns commented on dynamic_programming/catalan_numbers.py
> +        print(self.catalan_numbers)
I would avoid print statements in the algorithm itself as they produce unwanted side-effects.

2021-05-29 14:23 UTC, mrmaxguns commented on dynamic_programming/catalan_numbers.py
> +                return print(self.catalan_numbers[: sequence_no + 1])
This should return the value directly for the same reason described above. This is where the algorithm produces its output, so the output should be directly returned.

2021-05-29 14:23 UTC, mrmaxguns commented on dynamic_programming/catalan_numbers.py
> +                print("Out of bound.")
This is an error, so an exception should be raised here.

2021-05-29 14:23 UTC, mrmaxguns commented on dynamic_programming/catalan_numbers.py
> +            print("Please specify a value")
Again, this should be refactored as an exception.

2021-05-31 21:23 UTC, Kommandat commented
> Hello. Thanks for your contribution. I performed a review. If you disagree with the changes I suggested, feel free to explain your disagreement by commenting on the review.
> 
> Mostly, I suggested changes to avoid unwanted side-effects. These changes are based on the following contribution guideline:
> 
> > have minimal side effects (Ex. print(), plot(), read(), write()).
> 
> Also, when the user enters erroneous input, an exception should be raised, instead of it simply being printed (this applies only to the algorithm itself, not in the `if __name__ == "__main__"` block).
> 
> > raise Python exceptions (ValueError, etc.) on erroneous input values

@mrmaxguns Thanks for the review! I agree with all your comments and made the changes you recommended. I requested a re-review, please take another look when you get a chance.

As an aside, I based much of my code on the [Fibonacci algorithm](https://github.com/TheAlgorithms/Python/blob/master/dynamic_programming/fibonacci.py) in the same folder thinking an existing algorithm already followed the guidelines but I was mistaken. It would nice to add some examples to the contribution guidelines that demonstrate best practices so others don't do what I did.

Once again, thanks!

2021-05-31 23:44 UTC, mrmaxguns approved these changes
Thank you for your contribution! Yes, indeed, some code in this repository does not follow the contribution guidelines, as they may have changed or the code was improperly reviewed. If you notice such code, feel free to open a pull request addressing the changes.

Regarding the code, it looks good. Thanks for applying the suggestions! This should be merged once tests are run and I double check the code for any issues I might not have caught now.

2021-06-01 00:54 UTC, mrmaxguns commented
Thank you for your contribution! :100:

2021-06-01 00:55 UTC, merged