case switch using python
TheAlgorithms/Python pull request #4482
Opened 2021-06-05 10:31 UTC by suyash2796

### **Describe your change:**

* [x] Add an algorithm?
* [] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2021-06-05 10:55 UTC, suyash2796 commented
code review comments addressed

2021-06-10 17:09 UTC, onlinejudge95 requested changes
General formatting changes are required, please use the pre-commit hook for the same.

2021-06-11 03:09 UTC, suyash2796 commented
> General formatting changes are required, please use the pre-commit hook for the same.

Hi @onlinejudge95 -  code formatting is completed!

2021-06-11 04:03 UTC, onlinejudge95 commented
Also correct me if I am not wrong, Python 3.10 has a switch case construct build already?

2021-06-11 04:14 UTC, suyash2796 commented
> Also correct me if I am not wrong, Python 3.10 has a switch case construct build already?

oh yes! that was released yesterday :+1: . That was not available until 3.9 therefore as an alternative I implemented that for one of my projects and found it very useful so I thought that would be beneficial for the community. 
But I think that is not needed now as switch case problem is solved in 3.10!!
Thanks for your inputs. I really Appreciate it !

2021-06-13 18:07 UTC, onlinejudge95 requested changes

2021-06-13 18:07 UTC, onlinejudge95 commented on other/switch_case_with_python_function.py
> +    switch_case_mapper("multiply", 1, 2)
Use doctests for testing

2021-07-16 17:30 UTC, onlinejudge95 requested changes

2021-07-16 17:30 UTC, onlinejudge95 commented on other/switch_case_with_python_function.py
> +    switch_case_mapper("multiply", 1, 2)
Remove the following piece of code

2021-08-28 16:54 UTC, closed without merging