Random anime character info
TheAlgorithms/Python pull request #4553
Opened 2021-07-18 15:10 UTC by ashish-patwal

### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2021-07-18 15:12 UTC, ashish-patwal commented on web_programming/random_anime_character.py
> +def random_anime_character() -> None:
As this script produces a random string of characters and info , i cannot presume and assert any conditions for the test . Thus doctests were not included .

2021-07-18 16:01 UTC, ashish-patwal commented
updates : black formatted the file as well as did pre-commit . 
ptal @cclauss

2021-07-18 16:47 UTC, cclauss commented
Run `mypy .`
```
web_programming/random_anime_character.py:38: error: No return value expected
web_programming/random_anime_character.py:42: error: "random_anime_character" does not return a value
Found 2 errors in 1 file (checked 316 source files)
```

2021-07-18 16:48 UTC, ASHIKSAR commented
Okay


On Sun, Jul 18, 2021, 10:04 PM Lucifer ***@***.***> wrote:

> updates : black formatted the file as well as did pre-commit .
> ptal @cclauss <https://github.com/cclauss>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TheAlgorithms/Python/pull/4553#issuecomment-882079158>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU4MCLC7VDAU7OSQ4RFPAJ3TYL3SVANCNFSM5ASHHCOA>
> .
>

2021-07-19 05:49 UTC, ashish-patwal commented
I did all the tests and the script passed all of them . pre-commit , black formatting , flake8 . Can you please take one more look @cclauss  . Doctests can't be created for this script therefore ommitted .

2021-07-19 06:47 UTC, cclauss requested changes
Please fix type hints until mypy passes.

2021-07-19 06:47 UTC, cclauss commented on web_programming/random_anime_character.py
> +    Returns the Name and Description of the anime character .
```suggestion
    Returns the Title, Description, and Image Title of a random anime character .
```

2021-07-19 06:47 UTC, cclauss commented on web_programming/random_anime_character.py
> +def random_anime_character() -> None:
```suggestion
def random_anime_character() -> tuple[str, str, str]:
```

2021-07-19 15:33 UTC, cclauss commented on web_programming/random_anime_character.py
> +    return None
```suggestion
```
This can safely be deleted.  We would only use `return None` on functions that could return other values.

2021-07-19 15:36 UTC, cclauss approved these changes
Looks good to me.  Thanks for your persistence.  Well done.

2021-07-19 15:40 UTC, merged

2021-07-19 17:34 UTC, ashish-patwal commented
> Looks good to me. Thanks for your persistence. Well done.

Thank you as well . I learnt a lot .