Added Branch And Bound algorithm to solve 0-1 Knapsack Problem
TheAlgorithms/Python pull request #4566
Opened 2021-07-22 11:52 UTC by yuanjie8629

### **Describe your change:**
Added Branch And Bound algorithm to solve 0-1 Knapsack Problem

* [x] Add an algorithm?
* [] Fix a bug or typo in an existing algorithm?
* [] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2021-08-19 06:10 UTC, nivedha02 approved these changes
well done

2021-08-19 06:11 UTC, nivedha02 requested changes
Great work

2021-09-22 17:39 UTC, poyea commented
@algorithms-keeper review-all

2021-09-22 17:51 UTC, poyea commented on knapsack/branch_and_bound/README.md
> +1. Sort the items based on their value/weight(V/W) ratio.
It'd be helpful if we make it \`V\` and \`W\`. Same for all other variables like minLB -> \`minLB\` -> `minLB`

2021-09-22 17:51 UTC, poyea commented on knapsack/branch_and_bound/README.md
> +To be completed.
I think you've completed?

2021-09-22 17:53 UTC, poyea commented on knapsack/branch_and_bound/branch_and_bound.py
> +"""
Or we can put these in README, making the code itself "self-contained"

2021-09-22 17:55 UTC, poyea commented on knapsack/branch_and_bound/item.py
> +        self._rating = rating
`rating`means `value` I guess? See if we can align it with the definition in README.

2022-10-01 10:35 UTC, cclauss commented
In preparation for that denial-of-service attack that is [Hacktoberfest](https://hacktoberfest.com), I am closing all pull requests that do not have passing tests.

2022-10-01 10:35 UTC, closed without merging