add date_to_weekday finder method
TheAlgorithms/Python pull request #4599
Opened 2021-08-07 15:43 UTC by suryapratapsinghsuryavanshi

### **Describe your change:**

* [x] Add an algorithm?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2021-08-10 08:44 UTC, L3str4nge requested changes

2021-08-10 08:44 UTC, L3str4nge commented on other/date_to_weekday.py
> +    new_base_date: str = f"{day}/{month}/{year%100} 23:15:59"
I think we don't need a time here.

2021-08-10 08:44 UTC, L3str4nge commented on other/date_to_weekday.py
> +    day_list: list = [
We have pretty module in python so we don't need to hardcode weekdays `import calendar;calendar.day_name`

2021-08-14 09:48 UTC, L3str4nge requested changes
Tests are failing

2021-08-14 09:57 UTC, suryapratapsinghsuryavanshi commented
Yes, but I don't get a reason why the tests are failing.

2021-08-18 12:05 UTC, L3str4nge approved these changes

2021-08-18 12:05 UTC, merged