Create exchange_sort.py
TheAlgorithms/Python pull request #4600
Opened 2021-08-07 22:02 UTC by bonbon99

### **Describe your change:**
Added exchange sort as referenced from https://en.wikipedia.org/wiki/Sorting_algorithm#Exchange_sort

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2021-08-09 06:54 UTC, L3str4nge requested changes
Please also take a look at build fail details.

2021-08-09 06:54 UTC, L3str4nge commented on sorts/exchange_sort.py
> +        for j in range(i + 1, len(numbers)):
Calling `len(numbers)` each iteration is inefficient. I would prefer create local variable like `numbers_count = len(numbers)` and use it then in for loops.

2021-08-12 07:15 UTC, L3str4nge commented
Tests are still failing @bonbon99

2021-08-14 22:58 UTC, bonbon99 commented
Thank you for reviewing @L3str4nge !

2021-08-15 05:42 UTC, L3str4nge approved these changes

2021-08-15 05:43 UTC, merged