Scrambled words
TheAlgorithms/Python pull request #5039
Opened 2021-10-05 14:13 UTC by jyothsnashaji

### **Describe your change:**
Added an algorithm to unscrambled a word into its meaningful English spelling

* [x ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2021-10-05 20:09 UTC, L3str4nge requested changes

2021-10-05 20:09 UTC, L3str4nge commented on strings/unscramble.py
> +    return set(solutions)
Instead of calling set we can just define solutions as a set: `solutions = set()`

2021-10-05 20:09 UTC, L3str4nge commented on strings/unscramble.py
> +    for word in set(scrambled_words):
It could be pythonic one liner

2021-10-31 15:50 UTC, jyothsnashaji commented
@L3str4nge  Can you please review and close?

2022-10-01 11:08 UTC, cclauss commented
In preparation for that denial-of-service attack that is [Hacktoberfest](https://hacktoberfest.com), I am closing all pull requests that do not have passing tests.

2022-10-01 11:08 UTC, closed without merging