Swati iiit/python code
TheAlgorithms/Python pull request #5126
Opened 2021-10-07 17:08 UTC by swatiIIIT

### **Describe your change:**

* [x ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-05-11 15:13 UTC, s39674 requested changes
I think that should take care of it.

2022-05-11 15:13 UTC, s39674 commented on strings/insert_char_after_every_k_characters.py
> +def insert_character_after_every_k_elements(input_string, k, character_to_insert):
```suggestion
def insert_character_after_every_k_elements(input_string: str, PlaceChrEvery: int, character_to_insert: str) -> str:
```

2022-05-11 15:13 UTC, s39674 commented on strings/insert_char_after_every_k_characters.py
> +    for i in range(0, len(input_string), k):
```suggestion
    for i in range(0, len(input_string), PlaceChrEvery):
```

2022-05-11 15:13 UTC, s39674 commented on strings/insert_char_after_every_k_characters.py
> +k = int(input('Enter after which K element want to enter the string '))
```suggestion
PlaceChrEvery = int(input('Enter after which element want to enter the string '))
```

2022-05-11 15:13 UTC, s39674 commented on strings/insert_char_after_every_k_characters.py
> +result = insert_character_after_every_k_elements(input_string, k, character_to_insert)
```suggestion
result = insert_character_after_every_k_elements(input_string, PlaceChrEvery, character_to_insert)
```

2022-10-01 11:04 UTC, cclauss commented
In preparation for that denial-of-service attack that is [Hacktoberfest](https://hacktoberfest.com), I am closing all pull requests that do not have passing tests.

2022-10-01 11:04 UTC, closed without merging