Create longest_path_in_a_matrix.py
TheAlgorithms/Python pull request #5195
Opened 2021-10-10 06:11 UTC by akulagrawal

### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2021-10-10 06:42 UTC, akulagrawal commented
@Kush1101 please approve

2021-10-11 12:27 UTC, akulagrawal commented
@Kush1101 please approve

2021-11-10 10:17 UTC, poyea approved these changes
Thank you for your pull request!🤩

2021-11-10 10:21 UTC, poyea commented on dynamic_programming/longest_path_in_matrix.py
> +    Find the length of longest path of increasing sequence in a matrix mat.
It's a bit unclear on what the problem is here. Could you provide a reference / explanation for a "longest path"?

2021-11-10 10:21 UTC, poyea requested changes
Please add a few references

2023-09-30 16:12 UTC, tianyizheng02 commented
Closing due to lack of response to code review. Also, I believe this PR is plagiarized from [this GeeksForGeeks article](https://www.geeksforgeeks.org/find-the-longest-path-in-a-matrix-with-given-constraints/) because the code structure is identical with the only differences being function names and some variable names.

2023-09-30 16:12 UTC, closed without merging