mypy: Exclude only 20 files that are still failing
TheAlgorithms/Python pull request #5608
Opened 2021-10-26 14:11 UTC by cclauss

Let's see what is required to finish  #4052

### **Describe your change:**

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2021-11-03 11:50 UTC, spazm commented
`other/` will be clean when the PRs in-fligh are landedt: #5647, #5648, #5653, #5656, and  #5755.

The middle three were autoclosed by the bot for "multiple PR detected", so if they could be re-opened and reviewed, that'd be appreciated.  [ #5648 #5653 #5656 ]

```
% git checkout mypy-fix-other-all

% mypy --ignore-missing-imports --install-types
Success: no issues found in 21 source files
```

2021-11-03 12:06 UTC, dylanbuchi commented
> The middle three were autoclosed by the bot for "multiple PR detected", so if they could be re-opened and reviewed, that'd be appreciated. [ #5648 #5653 #5656 ]

Hey @spazm. PR's can't be reopened! You'll have to create new pull requests.

2021-11-03 13:03 UTC, spazm commented
> Hey @spazm. PR's can't be reopened! You'll have to create new pull requests.

Thanks for the info.  It's a bummer, of course.

2021-11-03 13:40 UTC, cclauss commented
Improvements!  
```
./graphs          || true  # Errors: 10  -> 9
./maths           || true  # Errors: 14  -> 14
./matrix          || true  # Errors: 15  -> 15
./searches        || true  # Errors: 45  -> 21
./other           || true  # Errors: 51  -> 43
./data_structures || true  # Errors: 117 -> 67
```
Perhaps we should start `mypy --exclude` individual files.

2021-11-05 07:06 UTC, cclauss commented
```python
with open("mypy_errors.txt") as out_file:
    files = sorted({line.split(':')[0] for line in in_file if ':' in line})

print(f"{len(files) = }")
print("\n".join(f"                  --exclude={name}" for name in names))
```

2021-11-05 08:49 UTC, cclauss commented
@dhruvmanila Please let me know why the `mypy.ini` __exclude__ is not working.

2021-11-05 10:05 UTC, ErwinJunge commented
> @dhruvmanila Please let me know why the `mypy.ini` **exclude** is not working.

Probably due to the `mv mypy.ini was_mypy.ini` here: https://github.com/TheAlgorithms/Python/pull/5608/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R31

2021-11-05 10:42 UTC, cclauss commented
I was talking about the mypy run on line 24.

2021-11-05 13:30 UTC, dylanbuchi requested changes

2021-11-05 13:30 UTC, dylanbuchi commented on mypy.ini
> +exclude = /(data_structures/stacks/next_greater_element\.py|graphs/boruvka\.py|graphs/breadth_first_search\.py|graphs/breadth_first_search_2\.py|graphs/check_cycle\.py|graphs/finding_bridges\.py|grap
@cclauss 
This should work
```suggestion
exclude = (data_structures/stacks/next_greater_element.py|graphs/boruvka.py|graphs/breadth_first_search.py|graphs/breadth_first_search_2.py|graphs/check_cycle.py|graphs/finding_bridges.py|graphs/greedy_min_vertex_cover.py|graphs/random_graph_generator.py|maths/average_mode.py|maths/gamma_recursive.py|maths/proth_number.py|maths/series/geometric_series.py|maths/series/p_series.py|matrix_operation.py|other/fischer_yates_shuffle.py|other/least_recently_used.py|other/lfu_cache.py|other/lru_cache.py|searches/simulated_annealing.py|searches/ternary_search.py)

```

2021-11-05 14:01 UTC, cclauss commented
@dylanbuchi AWESOME!!  I own you a beer!!

2021-11-06 12:27 UTC, dhruvmanila approved these changes
A small nitpick, otherwise LGTM 👍

2021-11-06 12:27 UTC, dhruvmanila commented on mypy.ini
> +exclude = (data_structures/stacks/next_greater_element.py|graphs/boruvka.py|graphs/breadth_first_search.py|graphs/breadth_first_search_2.py|graphs/check_cycle.py|graphs/finding_bridges.py|graphs/gree
Maybe this could be done on multiline if possible for better readability. If not possible, then ignore this comment.

2021-11-06 12:52 UTC, poyea approved these changes

2021-11-06 12:58 UTC, merged