Add-README-files-3/8
TheAlgorithms/Python pull request #5819
Opened 2021-11-11 15:48 UTC by Leoriem-code

### Describe your change:

The 3rd of the serie

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2023-08-14 12:13 UTC, CaedenPH requested changes
I like the idea of adding README's to each directory, however the content here is insufficient an phrased incorrectly

@tianyizheng02 What is your opinion?

2023-08-14 12:13 UTC, CaedenPH commented on arithmetic_analysis/in_static_equilibrium.py
> -    [-9.999987317275396, 0.01592652916486828]
Can this change be reverted? Not sure why it was made

2023-08-14 12:13 UTC, CaedenPH commented on data_structures/README.md
> +There exist [many](https://en.wikipedia.org/wiki/List_of_data_structures) types of data structures, but some structures are more useful to keep some type of data over another type.
```suggestion
[Many](https://en.wikipedia.org/wiki/List_of_data_structures) types of data structures exist, but some structures are more useful than others when storing certain types of data.
```

2023-08-14 12:13 UTC, CaedenPH commented on data_structures/README.md
> +* <https://www.tommyds.it/doc/benchmark.html>
Doesn't seem relevant

2023-08-14 12:13 UTC, CaedenPH commented on digital_image_processing/README.md
> +Digital Image Processing (DIP) is when you are processing and applying changes to an image with a computer.
```suggestion
Digital Image Processing (DIP) is the process of applying changes to an image digitally
```

2023-08-14 12:13 UTC, CaedenPH commented on data_structures/README.md
> +The types used everywhere when programming is the boolean, the integer, the character and the floating point number. Those can lead to more advanced type, such as list, array, set, tuple, stack etc.
This line is wordy and doesn't make sense

2023-08-22 23:13 UTC, tianyizheng02 commented
> I like the idea of adding README's to each directory, however the content here is insufficient an phrased incorrectly
> 
> @tianyizheng02 What is your opinion?

@CaedenPH I agree, the content needs to be significantly expanded upon and the grammar/wording is a bit questionable. Having directory READMEs is definitely good documentation so we'll just have to wait until someone else opens another PR contributing one.

2023-08-22 23:13 UTC, closed without merging