feat: Add basic issue forms
TheAlgorithms/Python pull request #5822
Opened 2021-11-12 20:45 UTC by Panquesito7

### Describe your change:

- Add basic issue forms.

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2021-11-22 01:28 UTC, krishguptadev approved these changes

2022-03-30 20:00 UTC, WISSAL-MN commented
https://github.com/TheAlgorithms/Python/pull/5822#issue-1052395608

2022-04-29 22:09 UTC, Panquesito7 commented
@AnupKumarPanwar.

2022-04-29 22:09 UTC, Panquesito7 commented
@AnupKumarPanwar.

2022-08-06 14:02 UTC, dhruvmanila requested changes
Some initial thoughts. Also, I don't see any point of having the `other` issue form.

2022-08-06 14:02 UTC, dhruvmanila commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +title: "[FEATURE]"
Same suggestion, not a big fan of prefixed title. We have labels for that.

2022-08-07 00:15 UTC, Panquesito7 commented
> I don't see any point of having the `other` issue form

That's so people cannot make blank issues without any content. They have to provide some content if none of the provided issue templates fits their problem. Without this, people won't be able to make any other miscellaneous issues if we disable blank issues. Hope you understand. 🙂

2022-10-02 08:56 UTC, dhruvmanila commented
closing in favor of #6533

2022-10-02 08:56 UTC, closed without merging