Added 2 new algorythms (decrypt message, censor)
TheAlgorithms/Python pull request #5883
Opened 2021-12-25 12:51 UTC by meg-1

### Describe your change:

Added 2 new algorythms (decrypt message, censor)

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2021-12-28 00:52 UTC, IdoErel requested changes
The comments are too long.
Keep the comments short and concise.

The code is implementing what's already been implemented in python.

Kind regards,
IdoErel

2021-12-28 06:00 UTC, bayrsaixan commented
https://www.easeus.com/backup-software/?utm_source=youtube-heyiran-202107-tb-AsoftClick&utm_medium=referral

On Tue, 28 Dec 2021, 08:58 IdoErel, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> The comments are too long.
> Keep the comments short and concise.
>
> Kind regards,
> Ido Erel
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TheAlgorithms/Python/pull/5883#pullrequestreview-840600445>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASCQE6XICOYBW3MSNKLOHOTUTEDRRANCNFSM5KXZIB3Q>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-01-05 14:12 UTC, meg-1 commented
> The code is implementing what's already been implemented in python.

Thank you a lot for the feedback! Quick question, you mean both algorithms have been implemented in Python already, right? Or just the censor algorithm?

2022-01-16 08:44 UTC, xcodz-dot requested changes
Thank you for trying but it seems that `decrypt` does not do any decryption but only removes the character provided to it and does not do any real world decryption. You might say that it does English deobfuscation but that is also false as well (in case you say so).

here is an example, both of them are equivalent, the latter being already inbuilt.
```python
decrypt("o$ne", "$") == "o$ne".replace("$", "")
```

and for the `censor` function that is also achieved by the same `replace`.

```python
censor("bad word", "bad") == "bad word".replace("bad", "***")
```

Okay, I get it that censor is still reasonable but `decrypt` is unnecessary.

2022-01-22 12:34 UTC, meg-1 commented
> Thank you for trying but it seems that `decrypt` does not do any decryption but only removes the character provided to it and does not do any real world decryption. You might say that it does English deobfuscation but that is also false as well (in case you say so).
> 
> here is an example, both of them are equivalent, the latter being already inbuilt.
> 
> ```python
> decrypt("o$ne", "$") == "o$ne".replace("$", "")
> ```
> 
> and for the `censor` function that is also achieved by the same `replace`.
> 
> ```python
> censor("bad word", "bad") == "bad word".replace("bad", "***")
> ```
> 
> Okay, I get it that censor is still reasonable but `decrypt` is unnecessary.
 
Thank you so much for the feedback, it's greately appreciated. Would it be okay if I remove the "decrypt" function, and only set a pull request for the censor function? Or does the censor function not hold any value to the repository, and it's not neccessary to commit?

2022-01-22 13:17 UTC, xcodz-dot commented
As I am not a maintainer, I can only advise yes but please consider mentioning to any of the maintainers. My advise does not help with the merge decision of any PR and is completely up to maintainer

2022-01-31 07:38 UTC, xcodz-dot requested changes

2022-01-31 07:38 UTC, xcodz-dot commented on maths/average_welford.py
> +def average_welford(values):
```suggestion
def average_welford(values) -> float:
```

2022-03-16 15:14 UTC, meg-1 commented
@Kush1101 , hello! could you please review this pull request??

2022-03-24 18:39 UTC, poyea commented on maths/average_welford.py
> +    >>> average_welford([1, 2, 3, 4, 5])
Please reformat the code to use 4 spaces as indentation

2022-03-24 18:40 UTC, poyea commented on strings/decrypt.py
> +  one
4 spaces too.

2022-03-24 18:41 UTC, poyea commented
Sometimes the CI is not running - just LMK if that's the case

2022-03-26 12:47 UTC, meg-1 commented
> Sometimes the CI is not running - just LMK if that's the case

ty, i think that might have been the case. will definitely inform if it happens again!

2022-03-30 14:30 UTC, closed without merging