Digital root
TheAlgorithms/Python pull request #6324
Opened 2022-08-13 11:41 UTC by meg-1

### Describe your change:

**added the 'digital_root' method to maths/sum_of_digits.py.
a digital root is: https://en.wikipedia.org/wiki/Digital_root**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x]  This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-08-17 14:47 UTC, meg-1 commented
@poyea @cclauss , hi! thank you for your recommendations. i have closed, and recreated the previous pull requests!

2022-08-27 12:01 UTC, meg-1 commented
@Kush1101 hi! could you please check out this pull request?

2022-09-03 12:49 UTC, meg-1 commented
@Kush1101 hi! could you please check out this pull request?

2022-09-03 13:01 UTC, cclauss commented on maths/sum_of_digits.py
> +        return n % 9 or n and 9 if n >= 0 else -1
Should `n and 9` be `n & 9` ?  https://www.geeksforgeeks.org/difference-between-and-and-in-python

2022-09-03 13:03 UTC, cclauss requested changes

2022-09-03 13:03 UTC, cclauss commented on maths/sum_of_digits.py
> +    )
Please use a more readable syntax like lines 111 and 112.

2022-09-03 13:03 UTC, cclauss commented on maths/sum_of_digits.py
> +    )
Please use a more readable syntax like lines 111 and 112.

2022-09-14 15:51 UTC, cclauss commented
Please run psf/black on the code as discussed in CONTRIBUTING.md.
* https://pypi.org/project/black

2022-10-01 08:34 UTC, cclauss commented
In preparation for that denial-of-service attack that is [Hacktoberfest](https://hacktoberfest.com), I am closing all pull requests that have failing tests.

2022-10-01 08:34 UTC, closed without merging