Add simple neural network
TheAlgorithms/Python pull request #6452
Opened 2022-10-01 09:28 UTC by CaioCordeiro

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### Tests Results:
```
Trying:
    res = forward_propagation(32, 10000000)
Expecting nothing
ok
Trying:
    res > 31 and res < 33
Expecting:
    True
ok
Trying:
    res = forward_propagation(32, 1000)
Expecting nothing
ok
Trying:
    res > 31 and res < 33
Expecting:
    False
ok
Trying:
    sigmoid_function(3.5)
Expecting:
    0.9706877692486436
ok
Trying:
    sigmoid_function(3.5, True)
Expecting:
    -8.75
ok
1 items had no tests:
    simple_neural_network
2 items passed all tests:
   4 tests in simple_neural_network.forward_propagation
   2 tests in simple_neural_network.sigmoid_function
6 tests in 3 items.
6 passed and 0 failed.
Test passed.
```

2022-10-01 09:30 UTC, CaioCordeiro commented
@CaedenPH Could you check this one? The other one got closed when I was fixing the pre-commit.

2022-10-01 09:32 UTC, CaedenPH approved these changes
Looks good.
As a side note, you could also implement a simple `doctest` check i

2022-10-01 09:46 UTC, CaioCordeiro commented
> Looks good. As a side note, you could also implement a simple `doctest` check

Sure, could you show me an example?

2022-10-01 09:49 UTC, CaedenPH commented
> > Looks good. As a side note, you could also implement a simple `doctest` check
> 
> Sure, could you show me an example?

Very simple, just ```py
if __name__ == "__main__":
    import doctest

    doctest.testmod()
```
@CaioCordeiro

2022-10-01 10:02 UTC, CaedenPH requested changes

2022-10-01 10:02 UTC, CaedenPH commented on neural_network/simple_neural_network.py
> +import doctest
```suggestion
```

2022-10-01 10:02 UTC, CaedenPH commented on neural_network/simple_neural_network.py
> +    print(doctest.testmod())
```suggestion
    import doctest

    doctest.testmod()
```

2022-10-01 10:11 UTC, CaioCordeiro commented on neural_network/simple_neural_network.py
> +import doctest
Done

2022-10-01 10:12 UTC, CaioCordeiro commented on neural_network/simple_neural_network.py
> +    print(doctest.testmod())
Done

2022-10-01 10:15 UTC, CaedenPH approved these changes

2022-10-01 10:15 UTC, CaedenPH commented on neural_network/simple_neural_network.py
> +    expected = int(input("Expected value: "))
```suggestion
    
    expected = int(input("Expected value: "))
```

2022-10-01 12:07 UTC, CaedenPH approved these changes

2022-10-30 07:05 UTC, cclauss approved these changes

2022-10-30 07:05 UTC, merged