Add Ideal Gas Law for physics
TheAlgorithms/Python pull request #6503
Opened 2022-10-02 03:03 UTC by kavienanj

### Ideal Gas Law consists of 2 functions with return computed values for pressure and volume of a gas system according to given input values.

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-02 08:32 UTC, CaedenPH approved these changes
Looks good

2022-10-02 08:32 UTC, CaedenPH commented on physics/ideal_gas_law.py
> +    print(f"{examle_2_volume} [m^3]")
```suggestion
    print(f"{examle_2_volume} [m^3]")

```

2022-10-02 08:32 UTC, CaedenPH commented on physics/ideal_gas_law.py
> +
```suggestion
```

2022-10-02 12:13 UTC, kavienanj commented
Added the suggestions! Please accept these changes

2022-10-16 16:17 UTC, ZeroDayOwl requested changes

2022-10-16 16:17 UTC, ZeroDayOwl commented on physics/ideal_gas_law.py
> +UNIVERSAL_GAS_CONSTANT = 8.314462
I think you can add the units of R in a comment.

2022-10-16 16:17 UTC, ZeroDayOwl commented on physics/ideal_gas_law.py
> +    283731.01575
IMO you should add some failed cases in the doctest.

2022-10-16 16:17 UTC, ZeroDayOwl commented on physics/ideal_gas_law.py
> +    print(f"{examle_2_volume} [m^3]")
You can exclude this part in the algorithm.

2022-10-16 16:45 UTC, CaedenPH commented on physics/ideal_gas_law.py
> +    pressure: float = moles * kelvin * UNIVERSAL_GAS_CONSTANT / volume
```suggestion
    pressure = moles * kelvin * UNIVERSAL_GAS_CONSTANT / volume
```

2022-10-16 16:45 UTC, CaedenPH commented on physics/ideal_gas_law.py
> +    volume: float = moles * kelvin * UNIVERSAL_GAS_CONSTANT / pressure
```suggestion
    volume = moles * kelvin * UNIVERSAL_GAS_CONSTANT / pressure
```

2022-10-16 16:45 UTC, CaedenPH commented on physics/ideal_gas_law.py
> +    return volume
```suggestion
    return moles * kelvin * UNIVERSAL_GAS_CONSTANT / pressure
```

2022-10-17 05:32 UTC, CaedenPH reviewed
Last things from me

2022-10-17 05:32 UTC, CaedenPH commented on physics/ideal_gas_law.py
> +        raise Exception("Invalid inputs. Enter positive value.")
```suggestion
        raise ValueError("Invalid inputs. Enter positive value.")
```

2022-10-17 05:32 UTC, CaedenPH commented on physics/ideal_gas_law.py
> +        raise Exception("Invalid inputs. Enter positive value.")
```suggestion
        raise ValueError("Invalid inputs. Enter positive value.")
```

2022-10-17 05:32 UTC, CaedenPH commented on physics/ideal_gas_law.py
> +    """
```suggestion
    >>> pressure_of_gas_system(3, -0.46, 23.5)
    Traceback (most recent call last):
        ...
    ValueError: Invalid inputs. Enter positive value.
    """
```

2022-10-17 05:32 UTC, CaedenPH commented on physics/ideal_gas_law.py
> +    """
```suggestion
    >>> volume_of_gas_system(3, -0.46, 23.5)
    Traceback (most recent call last):
        ...
    ValueError: Invalid inputs. Enter positive value.
    """
```

2022-10-30 10:17 UTC, CaedenPH commented
@cclauss I think this is worthy of review - Perhaps committing my changes might be good, however the pr in general looks good

2022-10-30 10:26 UTC, cclauss approved these changes

2022-10-30 10:26 UTC, merged