Add binary insertion sort algorithm
TheAlgorithms/Python pull request #6509
Opened 2022-10-02 03:53 UTC by testourii

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-02 06:17 UTC, dhruvmanila requested changes
Hey, thanks for taking your time to contribute! The documentation needs to be updated to reflect the new algorithm. There are some typing improvements and optimizations. I'll take a second look at the implemented algorithm after these changes are incorporated, but this is a good start!

2022-10-02 06:17 UTC, dhruvmanila commented on sorts/binary_insertion_sort.py
> +def binary_search(collection: list, val: int, start: int, end: int) -> int:
Provide the container element type as well: `list[<type>]`

2022-10-02 06:17 UTC, dhruvmanila commented on sorts/binary_insertion_sort.py
> +    :param collection: some ascending sorted collection with comparable items
The docstring is a direct copy paste from `searches/binary_search.py`. Please update it as per the function.

2022-10-02 06:17 UTC, dhruvmanila commented on sorts/binary_insertion_sort.py
> +    :param collection: some mutable ordered collection with heterogeneous
The docstring is a direct copy paste from `sorts/insertion_sort.py`. Please update it as per the function.

2022-10-02 06:17 UTC, dhruvmanila commented on sorts/binary_insertion_sort.py
> +def binary_insertion_sort(collection: list) -> list:
Provide the container element type as well: `list[<type>]`

2022-10-02 06:17 UTC, dhruvmanila commented on sorts/binary_insertion_sort.py
> +        val = collection[index]
Using `enumerate` would be much more efficient here

2022-10-02 06:17 UTC, dhruvmanila commented on sorts/binary_insertion_sort.py
> +if __name__ == "__main__":
It's better to provide a simple CLI interface using `argparse` than to run the tests. They can be run using the `python -m doctest` command as well.

2022-10-03 11:38 UTC, testourii commented
@dhruvmanila I think I fixed the technical and conventional errors on this one. Could you take a look?

2022-10-03 13:26 UTC, dhruvmanila requested changes

2022-10-03 13:26 UTC, dhruvmanila commented on sorts/binary_insertion_sort.py
> +def binary_search(collection: list[int], value: int, start: int, end: int) -> int:
This algorithm is incorrect and breaks with the following initial tests:
```python
binary_search([1, 2, 3, 4, 5], 2, 0, 1)  # gives 2
binary_search([1, 2, 3, 4, 5], 2, 0, 4)  # gives 2
```

Please test out the algorithms thoroughly. Also, if possible, use existing implementation from `searches/binary_search.py`

2022-10-04 16:59 UTC, testourii commented
@dhruvmanila I used the existing implementation of searches/binary_search.py as you mentioned. To access the required file (which is in another folder (searches), I added the following lines:
```
import sys
sys.path.append("../searches")
from binary_search import bisect_left
```
which violates flake8's hooks for using an import after an instruction(E402) . By sequence, the test failed.

2022-10-06 15:32 UTC, dhruvmanila commented on sorts/binary_insertion_sort.py
> +python3 binary_insertion_sort.py
Please update this part as per the recent changes.

2022-10-09 12:38 UTC, testourii commented
@dhruvmanila  I think I fixed the issue and the docs. Could you take a look?

2022-10-17 07:11 UTC, testourii commented
@dhruvmanila  i think the branch is ready to be merged

2023-08-18 02:26 UTC, tianyizheng02 reviewed
Thanks for your contribution, but we already have an implementation of binary insertion sort that's very similar to yours. I know that your PR is older than the current implementation and should've probably been merged first, but unfortunately the other maintainers merged a newer PR instead—sorry.

2023-08-18 02:26 UTC, closed without merging