BinarySearch in 2D array with O(n) Time complexity #6513: an pr under Hacktoberfest
TheAlgorithms/Python pull request #6523
Opened 2022-10-02 06:29 UTC by sofezticated-gentleman

In this pr I am submitting my solution for the aforementioned issue under the festival of Hacktoberfest

### Describe your change:
Over here I am submitting my algo for Binsearch for the aforementioned issue

* [x ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-02 08:57 UTC, sofezticated-gentleman commented
@dhruvmanila can you please review my pr

2022-10-02 12:23 UTC, cclauss commented on matrix/matrix_binary_search.py
> +    r = int((lower_bound+upper_bound)/2)
Make it clear that you want an int, by using floor division (//).

2022-10-02 12:24 UTC, cclauss commented on matrix/matrix_binary_search.py
> +    if((lower_bound == r) or (upper_bound == r)):
```suggestion
    if r in (lower_bound, upper_bound):
```

2022-10-02 12:25 UTC, cclauss commented on matrix/matrix_binary_search.py
> +    if (array[r] < value):
As discussed in CONTRIBUTING.md, please run this code thru psf/black to get rid of all these extra parentheses.  This ain't JavaScript.

2022-10-02 12:27 UTC, cclauss commented on matrix/matrix_binary_search.py
> +
psf/black will get rid of all these unneeded lines.

2022-10-02 12:28 UTC, cclauss commented on matrix/matrix_binary_search.py
> +    True
How about a test that returns False?

2022-10-02 13:30 UTC, sofezticated-gentleman commented
@cclauss i have done the required changes can you please help me out. I am facing issues in checks but aint able to understand them. where am i going wrong.

2022-10-02 13:49 UTC, cclauss commented on matrix/matrix_binary_search.py
> +    if (array[r] == value):
```suggestion
    if array[r] == value:

```

2022-10-02 13:49 UTC, cclauss commented on matrix/matrix_binary_search.py
> +            index = index + 1
```suggestion
        index += 1

```

2022-10-02 13:50 UTC, cclauss commented on matrix/matrix_binary_search.py
> +def mat_bin_search(value: int, matrix: list) -> bool:
```suggestion


def mat_bin_search(value: int, matrix: list) -> bool:
```

2022-10-02 13:51 UTC, cclauss commented on matrix/matrix_binary_search.py
> +    if array[r] > value:
```suggestion
    else:
```

2022-10-02 14:02 UTC, cclauss commented on matrix/matrix_binary_search.py
> +    >>> binary_search(matrix, 0, len(matrix) - 1, 1)
```suggestion
    >>> binary_search(matrix, 0, len(matrix) - 1, 1)
```
Remove the space at the end of the line or get psf/black to do it for you.  See CONTRIBUTING.md.

2022-10-02 14:02 UTC, cclauss commented on matrix/matrix_binary_search.py
> +
```suggestion
```

2022-10-02 15:06 UTC, cclauss commented on matrix/matrix_binary_search.py
> +def mat_bin_search(value: int, matrix: list) -> bool:
You NEED two blank lines before and after a function of psf/black will fail your pull request.  See CONTRIBUTING.md
```suggestion


def mat_bin_search(value: int, matrix: list) -> bool:
```

2022-10-02 15:07 UTC, cclauss commented on matrix/matrix_binary_search.py
> +    True
```suggestion
    True
```

2022-10-02 15:12 UTC, cclauss commented on matrix/matrix_binary_search.py
> +              [18, 21, 23, 26, 30]]
Use ... for line continuation in doctests...
```suggestion
    >>> matrix = [[1, 4, 7, 11, 15],
    ...           [2, 5, 8, 12, 19],
    ...           [3, 6, 9, 16, 22],
    ...           [10, 13, 14, 17, 24],
    ...           [18, 21, 23, 26, 30]]
```

2022-10-03 06:06 UTC, sofezticated-gentleman commented
@cclauss can you please review my pr, i done the required changes

2022-10-03 13:47 UTC, dhruvmanila commented
Why is there another binary search? We already have them!

2022-10-03 13:55 UTC, sofezticated-gentleman commented
@dhruvmanila, a issue was opened a day ago for a 2d binary search in a matrix and so i tried to make a pr, also its my second issue, I think so theres no 2d binary search in the matrix repo....

2022-10-03 14:23 UTC, dhruvmanila requested changes
Please link the issue to the PR. Search algorithms do not return a boolean value, they return the position of the element.

In this case, it should return the position of the value in the matrix like `[y, x]` where `y` would be the index of the subarray in which the element exists and `x` would be the index of the element in that subarray.

2022-10-03 14:44 UTC, sofezticated-gentleman commented
> Please link the issue to the PR. Search algorithms do not return a boolean value, they return the position of the element.
> 
> In this case, it should return the position of the value in the matrix like `[y, x]` where `y` would be the index of the subarray in which the element exists and `x` would be the index of the element in that subarray.

Oh thank you @dhruvmanila I will make those changes ASAP

2022-10-03 15:39 UTC, sofezticated-gentleman commented
@dhruvmanila I have done the requested changes, but then too my build tests are failing, what are build tests and why is my code failing in them , can you please help me out...

2022-10-06 21:29 UTC, MaximSmolskiy commented
> @dhruvmanila I have done the requested changes, but then too my build tests are failing, what are build tests and why is my code failing in them , can you please help me out...

@sofezticated-gentleman Your second test for `mat_bin_search` function fails (log is listed below).

```
=================================== FAILURES ===================================
_____________ [doctest] matrix.matrix_binary_search.mat_bin_search _____________
034     >>> matrix = [[1, 4, 7, 11, 15],
035     ...           [2, 5, 8, 12, 19],
036     ...           [3, 6, 9, 16, 22],
037     ...           [10, 13, 14, 17, 24],
038     ...           [18, 21, 23, 26, 30]]
039     >>> target = 1
040     >>> mat_bin_search(target, matrix)
041     [0, 0]
042     >>> target = 34
043     >>> mat_bin_search(target, matrix)
UNEXPECTED EXCEPTION: IndexError('list index out of range')
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/doctest.py", line 1350, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest matrix.matrix_binary_search.mat_bin_search[4]>", line 1, in <module>
  File "/home/runner/work/Python/Python/matrix/matrix_binary_search.py", line 49, in mat_bin_search
    while matrix[index][0] < value:
IndexError: list index out of range
/home/runner/work/Python/Python/matrix/matrix_binary_search.py:43: UnexpectedException
```

2022-10-07 08:44 UTC, cclauss commented on matrix/matrix_binary_search.py
> +            break
```suggestion
    while matrix[index][0] < value and index <= len(matrix):
```

2022-10-07 16:31 UTC, CaedenPH commented on matrix/matrix_binary_search.py
> +    >>> target = 23
```suggestion
```
You aren't passing `target`, so you don't use the variable

2022-10-07 16:31 UTC, CaedenPH commented on matrix/matrix_binary_search.py
> +    >>> target = 1
```suggestion
```

2022-10-07 16:31 UTC, CaedenPH commented on matrix/matrix_binary_search.py
> +def binary_search(array: list, lower_bound: int, upper_bound: int, value: int) -> int:
```suggestion
def binary_search(array: list, value: int) -> int:
```
I don't think `lower_bound` and `upper_bound` parameters do much. If the person wants to change the upper and lower bound they should pass the list indexed to the upper and lower bound, such as 

`>>> binary_search([1,2,3,4,5][1:3])`

2022-10-07 16:31 UTC, CaedenPH commented on matrix/matrix_binary_search.py
> +    Array: A 1d sorted array
```suggestion
    array: A 1d sorted array
```

2022-10-08 14:34 UTC, SUGARXUST commented
Is this still relevant? I would like to work on this.

2022-10-10 13:19 UTC, anuragshuklajec commented
Please assign this to me !

2022-10-10 13:31 UTC, cclauss commented
Please looks at the `Details` buttons next to the failing tests.
```
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

matrix/matrix_binary_search.py:13:14: F821 undefined name 'lower_bound'
matrix/matrix_binary_search.py:13:28: F821 undefined name 'upper_bound'
matrix/matrix_binary_search.py:16:8: F821 undefined name 'lower_bound'
matrix/matrix_binary_search.py:16:23: F821 undefined name 'upper_bound'
matrix/matrix_binary_search.py:19:44: F821 undefined name 'upper_bound'
matrix/matrix_binary_search.py:21:36: F821 undefined name 'lower_bound'

mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

matrix/matrix_binary_search.py:13: error: Name "lower_bound" is not defined
matrix/matrix_binary_search.py:13: error: Name "upper_bound" is not defined
matrix/matrix_binary_search.py:16: error: Name "lower_bound" is not defined
matrix/matrix_binary_search.py:16: error: Name "upper_bound" is not defined
matrix/matrix_binary_search.py:19: error: Name "upper_bound" is not defined
matrix/matrix_binary_search.py:21: error: Name "lower_bound" is not defined
Found 6 errors in 1 file (checked 1041 source files)
```
FAILED matrix/matrix_binary_search.py::matrix.matrix_binary_search.binary_search
FAILED matrix/matrix_binary_search.py::matrix.matrix_binary_search.mat_bin_search

2022-10-10 14:21 UTC, anuragshuklajec commented
Unable to locate the file !
I have fixed errors in my local machine.
Allow me to contribute

2022-10-11 11:39 UTC, anuragshuklajec commented
I am ready with the solution kindly help me with the file path

2022-10-16 23:28 UTC, cclauss commented
Please read CONTRIBUTING.md.

Hacktoberfest is strenuous for our team of active volunteer maintainers. That small team now has ___200+ open pull requests___ to review.  We have __high standards for our submissions__ which are described in [`CONTRIBUTING.md`](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#contributing-guidelines).  Our continuous integration tests help to ensure that our standards are met before we review and merge deserving pull requests.  This is further complicated by the fact that we already have [lots of algorithms](https://github.com/TheAlgorithms/Python/blob/master/DIRECTORY.md) and would like to avoid duplicates.

For these reasons, I will **close all open pull requests failing tests** so that our unpaid team has a smaller mountain to climb.  If you want us to land your pull request, please read [`CONTRIBUTING.md`](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#contributing-guidelines) _carefully_ and try again.

2022-10-16 23:28 UTC, closed without merging