Dodecahedron surface area and volume
TheAlgorithms/Python pull request #6606
Opened 2022-10-03 10:39 UTC by shri30yans

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [X] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-16 16:13 UTC, ZeroDayOwl requested changes

2022-10-16 16:13 UTC, ZeroDayOwl commented on maths/dodecahedron.py
> +    print("Volume: ", dodecahedron_volume(edge=edge))
```suggestion
```

2022-10-16 16:13 UTC, ZeroDayOwl commented on maths/dodecahedron.py
> +if __name__ == "__main__":
```suggestion
if __name__ == "__main__":
    import doctest
    doctest.testmod()
```

2022-10-16 16:13 UTC, ZeroDayOwl commented on maths/dodecahedron.py
> +if __name__ == "__main__":
Incorporate those changes.

2022-10-31 17:14 UTC, cclauss approved these changes

2022-10-31 17:14 UTC, cclauss commented on maths/dodecahedron.py
> +    return volume
```suggestion
    return ((15 + (7 * (5 ** (1 / 2)))) / 4) * (edge**3)
```

2022-10-31 17:14 UTC, cclauss commented on maths/dodecahedron.py
> +    return surface_area
```suggestion
    return 3 * ((25 + 10 * (5 ** (1 / 2))) ** (1 / 2)) * (edge**2)
```

2022-10-31 17:15 UTC, merged