Update README.md
TheAlgorithms/Python pull request #6771
Opened 2022-10-06 17:25 UTC by Abinashbunty

Added Google Cirq references

### Describe your change:
Added references to Google Cirq which is one of the most popular frameworks for developing quantum algorithms.

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-07 12:42 UTC, Abinashbunty reviewed
All the necessary changes updated. Requesting review for merge.

2022-10-07 12:42 UTC, Abinashbunty commented on strings/barcode_validator.py
> +def eval_key(code: int):
Done

2022-10-07 12:42 UTC, Abinashbunty commented on strings/barcode_validator.py
> +def eval_key(code: int):
Done

2022-10-07 12:42 UTC, Abinashbunty commented on strings/barcode_validator.py
> +def eval_key(code: int):
Done

2022-10-07 12:42 UTC, Abinashbunty commented on strings/barcode_validator.py
> +def is_valid(code: int):
Done

2022-10-07 12:42 UTC, Abinashbunty commented on strings/barcode_validator.py
> +def is_valid(code: int):
Done

2022-10-12 17:50 UTC, Abinashbunty commented
@cclauss Requesting a review. 😄 Thanks!

2022-10-12 18:06 UTC, cclauss requested changes

2022-10-12 18:06 UTC, cclauss commented on strings/barcode_validator.py
> +    number_barcode = int(barcode)
As discussed in `CONTRIBUTING.md`…
```suggestion
    barcode = int(input("Enter a barcode: ").strip())
```

2022-10-12 18:06 UTC, cclauss commented on strings/barcode_validator.py
> +def is_valid(code: int) -> bool:
```suggestion
def is_barcode_valid(barcode: int) -> bool:
```

2022-10-12 18:10 UTC, cclauss commented on strings/barcode_validator.py
> +    >>> eval_key(8718452538119)
Also, "abcdefghijklm"

2022-10-12 21:10 UTC, Abinashbunty commented on strings/barcode_validator.py
> +def eval_key(code: int) -> int:
Done

2022-10-12 21:10 UTC, Abinashbunty commented on strings/barcode_validator.py
> +    >>> eval_key(8718452538119)
Done

2022-10-12 21:10 UTC, Abinashbunty commented on strings/barcode_validator.py
> +    number_barcode = int(barcode)
Done

2022-10-12 21:11 UTC, Abinashbunty commented on strings/barcode_validator.py
> +        raise ValueError("Barcode '{}' has alphabets in it".format(barcode))
Done

2022-10-12 21:34 UTC, Abinashbunty commented on strings/barcode_validator.py
> +def is_valid(code: int) -> bool:
Done

2022-10-12 21:35 UTC, Abinashbunty commented
@cclauss Done with the changes requested. 😄

2022-10-12 22:45 UTC, cclauss approved these changes

2022-10-12 22:54 UTC, Abinashbunty commented
Thanks @cclauss 😊 Will it be merged automatically?

2022-10-12 22:56 UTC, merged