Added spheres union
TheAlgorithms/Python pull request #6879
Opened 2022-10-09 15:25 UTC by matteomessmer

### My change
Added the algorithm for calculating the volume of spheres union.

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-20 17:09 UTC, matteomessmer commented
@Kush1101 do you have any update on my PR?

2022-10-20 19:35 UTC, CaedenPH commented
> @Kush1101 do you have any update on my PR?

Kush seems to be an inactive user

2022-10-20 19:39 UTC, CaedenPH requested changes
Personally, I preferred the f-strings, but everything else seems good

2022-10-21 06:17 UTC, matteomessmer commented
@CaedenPH oh my mistake, another PR changed the strings and I overwrote that with the previous version

2022-10-27 11:13 UTC, cclauss commented on maths/volume.py
> +    45.814892864851146
A few more tests please including some with bad inputs. 0, negative numbers, floating point numbers, letters, None, etc.

2022-10-27 11:14 UTC, cclauss commented on maths/volume.py
> +    )  # ~= 28.3
```suggestion
    #  ~= 28.3
    print(f"Hollow Circular Cylinder: {vol_hollow_circular_cylinder(1, 2, 3) = }")
```

2022-10-27 16:27 UTC, matteomessmer commented
@cclauss I fixed some stuff and added more test

2022-10-27 17:45 UTC, cclauss approved these changes

2022-10-27 17:45 UTC, merged