Create binary_search_matrix.py
TheAlgorithms/Python pull request #6995
Opened 2022-10-11 12:28 UTC by anuragshuklajec

Added an algorithm to search in matrix

### Describe your change:
Added an algorithm to search in row sorted matrix using Binary Search.

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-11 17:52 UTC, CaedenPH requested changes
At the end of the file please include 
```py
if __name__ == "__main__":
    import doctest

    doctest.testmod()
```
This tests your files

2022-10-13 16:57 UTC, CaedenPH approved these changes
@cclauss 
Can we get your review?

2022-10-13 17:11 UTC, cclauss commented on matrix/binary_search_matrix.py
> +        doctest.testmod()
```suggestion

if __name__ == "__main__":
    import doctest

    doctest.testmod()
```

2022-10-13 20:03 UTC, cclauss approved these changes

2022-10-13 20:03 UTC, merged