Added area_rectangle.py file
TheAlgorithms/Python pull request #7026
Opened 2022-10-12 07:32 UTC by AdityaWadkar

This script will return area of rectangle

### Describe your change:

- [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
- [x] All new Python files are placed inside an existing directory.
- [x] All filenames are in all lowercase characters with no spaces or dashes.
- [x] All functions and variable names follow Python naming conventions.
- [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
- [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-12 10:41 UTC, CaedenPH requested changes
Please run the doctests with ```py
if __name__ == "__main__":
    import doctest
 
    doctest.testmod()

```

2022-10-16 04:29 UTC, ZeroDayOwl requested changes

2022-10-16 04:29 UTC, ZeroDayOwl commented on maths/area_rectangle.py
> +Basic of this concept..
```suggestion
The area of a rectangle is defined as the product 
of its two adjacent sides.
```

2022-10-16 04:29 UTC, ZeroDayOwl commented on maths/area_rectangle.py
> +https://en.wikipedia.org/wiki/Rectangle
```suggestion
Source : https://en.wikipedia.org/wiki/Rectangle
```

2022-10-16 04:29 UTC, ZeroDayOwl commented on maths/area_rectangle.py
> +"""area of rectangle."""
```suggestion
```

2022-10-16 04:29 UTC, ZeroDayOwl commented on maths/area_rectangle.py
> +    print(area(10, 20))  # --> 10,20
```suggestion
```

2022-10-16 05:10 UTC, AdityaWadkar reviewed
Please make a quick review  so that my code will get merged in your repository

2022-10-16 16:04 UTC, ZeroDayOwl commented
@AdityaWadkar it seems you didn't incorporate the changes suggested. Please review them and update your algorithm.

2022-11-02 13:05 UTC, closed without merging