Added some more comments to volume.py in maths folder
TheAlgorithms/Python pull request #7080
Opened 2022-10-13 03:14 UTC by advik-student-dev

added some more comments (to formulas which need it) which make the code more readable and understandable. might make a list of all the formulas on the top, later

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-13 06:54 UTC, cclauss requested changes
I have moved the comments down to be just above the calculations.  I have changed the order of the terms to be the same in both the comments and the calculations.  I have changed `Volume -` to `Volume is` because `-` has a special meaning in calculations.  ;-)

Please fix the line that is failing our tests because it has more than 88 characters.

2022-10-13 06:54 UTC, cclauss commented on maths/volume.py
>  Wikipedia reference: https://en.wikipedia.org/wiki/Volume
```suggestion
Find the volume of various shapes.
* https://en.wikipedia.org/wiki/Volume
* https://en.wikipedia.org/wiki/Spherical_cap
```

2022-10-13 06:54 UTC, cclauss commented on maths/volume.py
> +# Imports
```suggestion
```

2022-10-13 06:54 UTC, cclauss commented on maths/volume.py
> +# Functions for calculating volumes of shapes
```suggestion
```

2022-10-13 06:54 UTC, cclauss commented on maths/volume.py
> +    Calculate the Volume of the spherical cap
```suggestion
    Calculate the volume of the spherical cap.
```

2022-10-13 06:54 UTC, cclauss commented on maths/volume.py
>      return 1 / 3 * pi * pow(height, 2) * (3 * radius - height)
```suggestion
    if height < 0 or radius < 0:
        raise ValueError("vol_spherical_cap() only accepts non-negative values")
    # Volume is 1/3 pi * height squared * (3 * radius - height)
    return 1 / 3 * pi * pow(height, 2) * (3 * radius - height)
```

2022-10-13 06:54 UTC, cclauss commented on maths/volume.py
>      return 4 / 3 * pi * pow(radius, 3)
```suggestion
    if radius < 0:
        raise ValueError("vol_sphere() only accepts non-negative values")
    # Volume is radius cubed * pi * 4/3
    return pow(radius, 3) * pi * 4 / 3
```

2022-10-13 06:54 UTC, cclauss commented on maths/volume.py
>      return 2 / 3 * pi * pow(radius, 3)
```suggestion
    if radius < 0:
        raise ValueError("vol_hemisphere() only accepts non-negative values")
    # Volume is radius cubed * pi * 2/3
    return pow(radius, 3) * pi * 2 / 3
```

2022-10-13 06:54 UTC, cclauss commented on maths/volume.py
>      return pi * pow(radius, 2) * height
```suggestion
    if height < 0 or radius < 0:
        raise ValueError("vol_circular_cylinder() only accepts non-negative values")
    # Volume is radius squared * height * pi
    return pow(radius, 2) * height * pi
```

2022-10-13 06:54 UTC, cclauss commented on maths/volume.py
> +    # Volume - 1/3 * pi * height * (radius_1 squared + radius_2 squared + radius_1 * radius_2)
Tests are failing on:
* maths/volume.py:388:89: E501 __line too long__ (94 > 88 characters)

Also, please move this line down to be just above the calculation.  Make sure that the order of the values in the comment and in the calculation are the same.

2022-10-13 06:57 UTC, cclauss commented on maths/volume.py
> +    # Volume - (outer_radius squared - inner_radius squared) * pi * height
Please move this comment down to be just above the calculation to make it easier for the reader to understand.

2022-10-13 07:02 UTC, cclauss commented on maths/volume.py
> +    return pow(radius, 3) * pi * 4 / 3
```suggestion
    # Volume is 4/3 * pi * radius cubed
    return  4 / 3 * pi * pow(radius, 3)
```

2022-10-13 16:40 UTC, Aadi077 requested changes
Change "volume -" to "volume is" because - has another meaning which would not apply.

2022-10-16 05:48 UTC, advik-student-dev reviewed
thank u for the changes!

2022-10-16 05:50 UTC, advik-student-dev commented
how do i commit your changes?

2022-10-16 13:25 UTC, raghavasrujan commented
Hello Sir, Can you assign this to me?

2022-10-16 13:28 UTC, cclauss approved these changes

2022-10-16 13:28 UTC, merged