check whether integer is even or odd using bit manupulation
TheAlgorithms/Python pull request #7099
Opened 2022-10-13 09:26 UTC by luciferx48

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-13 10:01 UTC, CaedenPH approved these changes
Looks good

2022-10-13 10:03 UTC, CaedenPH commented
@luciferx48 
I forgot to mention, could you add the algorithm to the DIRECTORY.md file please

2022-10-13 10:50 UTC, luciferx48 commented
@CaedenPH thnx for reviewing, Directory.md updated

2022-10-13 10:53 UTC, CaedenPH requested changes
In the DIRECTORY.md, algorithms should be in alphabetical order

2022-10-23 12:34 UTC, CaedenPH approved these changes
@cclauss Can we get your review?

2022-10-23 12:43 UTC, cclauss commented on bit_manipulation/even_or_not.py
> +        return False
```suggestion
    return number & 1 == 0
```

2022-10-23 17:21 UTC, luciferx48 commented
@cclauss can you merge or close this PR

2022-10-23 17:26 UTC, cclauss approved these changes

2022-10-23 17:26 UTC, merged