Create speed_conversions.py
TheAlgorithms/Python pull request #7128
Opened 2022-10-13 15:25 UTC by Abinashbunty

### Describe your change:
Code to convert speed from one unit to another 

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-13 16:51 UTC, CaedenPH reviewed
First, you don't need two sets of the same doctests

Second, you may want to consider having a dictionary of each unit and instead of chaining lots of `if/elif`'s, you can just make dictionary lookups.

In addition, I don't think you should return the rounded speed, instead just leave it long

2022-10-13 23:21 UTC, Abinashbunty commented
> In addition, I don't think you should return the rounded speed, instead just leave it long

I made the changes except for this one as this was producing too long results due to precision of `float` type. Is it fine? I rounded to 3 decimal places so that It looks neat.

2022-10-13 23:22 UTC, Abinashbunty commented
@cclauss Is this fine? 😄

2022-10-14 07:17 UTC, cclauss requested changes

2022-10-14 07:17 UTC, cclauss commented on conversions/speed_conversions.py
> +
Let's decrease the amount of scrolling required to read the implementation.  ;-)
```suggestion
    >>> convert_speed(100, "km/h", "mph")
    62.137
    >>> convert_speed(100, "km/h", "knot")
    53.996
    >>> convert_speed(100, "m/s", "km/h")
    360.0
    >>> convert_speed(100, "m/s", "mph")
    223.694
    >>> convert_speed(100, "m/s", "knot")
    194.384
    >>> convert_speed(100, "mph", "km/h")
    160.934
    >>> convert_speed(100, "mph", "m/s")
    44.704
    >>> convert_speed(100, "mph", "knot")
    86.898
    >>> convert_speed(100, "knot", "km/h")
    185.2
    >>> convert_speed(100, "knot", "m/s")
    51.444
```

2022-10-14 07:17 UTC, cclauss commented on conversions/speed_conversions.py
> +
```suggestion
```

2022-10-14 07:17 UTC, cclauss commented on conversions/speed_conversions.py
> +    Convert speed from one unit to another unit using the speed_chart
```suggestion
    Convert speed from one unit to another using the speed_charts above.
```

2022-10-14 07:17 UTC, cclauss commented on conversions/speed_conversions.py
> +
```suggestion
```

2022-10-14 07:17 UTC, cclauss commented on conversions/volume_conversions.py
> +    ...
```suggestion
        ...
```

2022-10-14 09:56 UTC, Abinashbunty commented on conversions/speed_conversions.py
> +
Done

2022-10-14 10:00 UTC, Abinashbunty commented
Now it's all set I hope. 😄 @cclauss

2022-10-14 10:02 UTC, Abinashbunty commented on conversions/volume_conversions.py
> +    ...
Updated in PR #7116

2022-10-14 17:50 UTC, Abinashbunty commented
@cclauss Now this can be merged. I resolved the conflict it was having due to another PR. 😄

2022-10-14 21:42 UTC, cclauss approved these changes

2022-10-14 21:42 UTC, merged