Add stalin sort algorithm
TheAlgorithms/Python pull request #7311
Opened 2022-10-16 11:40 UTC by turtleship69

### Describe your change:
Implement stalin sort algorithm in pure python in `stalin_sort.py`

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-16 15:58 UTC, ZeroDayOwl requested changes

2022-10-16 15:58 UTC, ZeroDayOwl commented on sorts/stalin_sort.py
> +python stalin_sort.py
```suggestion
```

2022-10-16 15:58 UTC, ZeroDayOwl commented on sorts/stalin_sort.py
> +    :return: all of the items that were in order
```suggestion
    :return: all of the items that were in order
    
```

2022-10-16 15:58 UTC, ZeroDayOwl commented on sorts/stalin_sort.py
> +if __name__ == "__main__":
```suggestion
if __name__ == "__main__":
    import doctest
    doctest.testmod()
```

2022-10-16 15:58 UTC, ZeroDayOwl commented on sorts/stalin_sort.py
> +    print(stalin_sort(unsorted))
```suggestion
```

2022-10-16 16:00 UTC, ZeroDayOwl commented on sorts/stalin_sort.py
> +    print(stalin_sort(unsorted))
Hey @turtleship69 you don't need to use `input()` or `print()` function for the algorithm.

2022-10-28 07:00 UTC, CaedenPH reviewed
Small changes

2022-10-28 08:47 UTC, CaedenPH approved these changes
@cclauss Can you review please

2022-10-28 11:58 UTC, cclauss commented on sorts/stalin_sort.py
> +    """Pure python implementation of the stalin sort algorithm in Python
```suggestion
    """Pure Python implementation of the stalin sort algorithm
```

2022-10-28 11:59 UTC, cclauss commented on sorts/stalin_sort.py
> +    if collection == []:
All other falsy values are just as dangerous as an empty list.
```suggestion
    if not collection:
```

2022-10-29 14:48 UTC, CaedenPH commented
@cclauss This is ready for merge

2022-10-29 15:43 UTC, cclauss commented
This is a useless algorithm that destroys data.  I believe that there is enough of a shrine to this silliness at https://github.com/gustavo-depaula/stalin-sort

2022-10-29 15:43 UTC, closed without merging