Create superdense_coding.py
TheAlgorithms/Python pull request #7349
Opened 2022-10-17 03:59 UTC by KevinJoven11

### Describe your change:

Add quantum superdense coding algorithm. The principal idea is to send two classical bits in to one quantum bit (qubit.)

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-19 08:49 UTC, poyea approved these changes
Thank you for your pull request!🤩

2022-10-19 10:54 UTC, CaedenPH requested changes
Please fix the `qasm_simulator` deprecation (#7308)

2022-10-19 10:54 UTC, CaedenPH commented on quantum/superdense_coding.py
> +    backend = Aer.get_backend("qasm_simulator")
`qasm_simulator` has been deprecated (#7308)

2022-10-19 10:54 UTC, CaedenPH commented on quantum/superdense_coding.py
> +    >>> superdense_coding(0,0)
```suggestion

    >>> superdense_coding(0,0)
```

2022-10-23 12:54 UTC, prateekiiest approved these changes

2022-10-23 12:54 UTC, merged

2022-10-23 12:56 UTC, CaedenPH commented
@prateekiiest I had made a pretty important comment that `qasm_simulator` is deprecated, so this algorithm will raise warnings and someone will need to fix this

2022-10-23 12:59 UTC, prateekiiest commented
@CaedenPH  made a revert PR. sorry for missing that

2022-10-23 13:00 UTC, prateekiiest commented
Closing as per PR comments. Thanks