Face Recognition Algorithm Using EigenFaces
TheAlgorithms/Python pull request #7372
Opened 2022-10-17 16:03 UTC by aditi-dey29

### Describe your change:
I have added a face recognition algorithm, implemented using numpy and matrix algebra. It is a .ipynb file, and the code can also be run via the google colab link shared in the file. The algorithm and the detailed explanation has been included in the file itself.

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-17 17:18 UTC, aditi-dey29 commented
This is a submission required for #Hactoberfest.
The tests are failing might be due to .py file. The collab notebook, whose link has been included in the file is running perfectly.

2022-10-19 10:37 UTC, ZeroDayOwl commented on computer_vision/face_recognition_using_eigenfaces.py
> +Used the approach mentioned in the research paper by Matthew Turk and Alex Pentland, for face recognition using Eigenfaces. The algorithm was implemented using basic matrix algebra and numpy. <br>
```suggestion
Used the approach mentioned in the research paper by Matthew Turk and Alex Pentland, for face recognition using Eigenfaces. The algorithm was implemented using basic matrix algebra and numpy.
```

2022-10-19 10:37 UTC, ZeroDayOwl commented on computer_vision/face_recognition_using_eigenfaces.py
> +
Perhaps try to make a generalised algorithm which can be applied using any value instead of using those specific assets.

2022-10-19 10:37 UTC, ZeroDayOwl commented on computer_vision/face_recognition_using_eigenfaces.py
> +            return name.__hash__()
Add doctest.

2022-10-19 10:37 UTC, ZeroDayOwl commented on computer_vision/face_recognition_using_eigenfaces.py
> +"""
Well, get rid of the raw HTML you pasted here.

2022-10-19 10:39 UTC, ZeroDayOwl commented
@cclauss is it permitted to copy other's project and paste it just mentioning the source? Because it seems the whole code here is just directly copied from [here.](https://colab.research.google.com/drive/1InXv7hbjSBRkuLZgpf9SCFQcxu2m924B#scrollTo=t0rjkbbTaQi9)

2022-10-19 10:43 UTC, aditi-dey29 commented
> @cclauss is it permitted to copy other's project and paste it just mentioning the source? Because it seems the whole code here is just directly copied from [here.](https://colab.research.google.com/drive/1InXv7hbjSBRkuLZgpf9SCFQcxu2m924B#scrollTo=t0rjkbbTaQi9)

yes that google Collaboratory is also mine. I originally wrote it there, but since there is no way to upload .ipynb files in this repo, I downloaded that as a .py and uploaded it here.

thanks for all the suggestions, I'll change them as soon as possible.

2022-10-19 10:43 UTC, CaedenPH requested changes
Please read our [contributing](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md) guidelines that says
> You did your work - no plagiarism allowed
> Any plagiarized work will not be merged.

2022-10-19 10:44 UTC, cclauss commented on computer_vision/face_recognition_using_eigenfaces.py
> +!pip install opencv-python
```suggestion
# !pip install opencv-python
```

2022-10-19 10:46 UTC, cclauss commented on computer_vision/face_recognition_using_eigenfaces.py
> +!pip install opencv-python
Perhaps it would be better to contribute this to https://github.com/TheAlgorithms/Jupyter which will be more tolerant of !-commands in Python code.

2022-10-19 10:56 UTC, aditi-dey29 commented on computer_vision/face_recognition_using_eigenfaces.py
> +!pip install opencv-python
Thank you so much!
Just did this. Can you now check?

2022-10-19 11:08 UTC, closed without merging

2022-10-19 14:02 UTC, ZeroDayOwl commented
> > @cclauss is it permitted to copy other's project and paste it just mentioning the source? Because it seems the whole code here is just directly copied from [here.](https://colab.research.google.com/drive/1InXv7hbjSBRkuLZgpf9SCFQcxu2m924B#scrollTo=t0rjkbbTaQi9)
> 
> yes that google Collaboratory is also mine. I originally wrote the code there, but since there is no way to upload .ipynb files in this repo, I downloaded that as a .py and uploaded it here.
> 
> thanks for all the suggestions, I'll change them as soon as possible.

Oh then it's alright. Thanks for contributing!