Andgate
TheAlgorithms/Python pull request #7388
Opened 2022-10-17 19:39 UTC by ajain35

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-18 14:50 UTC, realstealthninja requested changes

2022-10-18 14:50 UTC, realstealthninja commented on boolean_algebra/andgate.py
> +    print("Truth Table of AND Gate:")
please use a multi line string

2022-10-18 14:50 UTC, realstealthninja commented on boolean_algebra/andgate.py
> +def and_gate(input_1: int, input_2: int) -> int:
What about cases in which user provides a value that is not one or zero?

2022-10-28 06:55 UTC, CaedenPH commented
@cclauss 
This pull request has already been implemented here 

https://github.com/TheAlgorithms/Python/blob/master/boolean_algebra/and_gate.py

This pr should be closed

2022-10-28 11:56 UTC, cclauss commented
Duplicate https://github.com/TheAlgorithms/Python/blob/master/boolean_algebra/and_gate.py

2022-10-28 11:56 UTC, closed without merging