Update gaussian_naive_bayes.py
TheAlgorithms/Python pull request #7407
Opened 2022-10-18 18:20 UTC by mvsg2

Using the seaborn.heatmap library to plot the confusion matrix instead of the plot_confusion_matrix method from the sklearn.metrics module.

### Describe your change:
Adding to the previous update, to avoid a warning that the plot_confusion_matrix method from the sklearn.metrics throws, I have used the heatmap module of seaborn which takes an argument - the confusion matrix obtained from the confusion_matrix method in the sklearn.metrics library.

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-18 18:35 UTC, mvsg2 commented on machine_learning/gaussian_naive_bayes.py
> -import seaborn as sns # For plotting a heatmap of the confusion matrix. This way will not throw any warning.
Sorry, didn't mean to import them again...

2022-10-18 19:27 UTC, cclauss commented
Please read CONTRIBUTING.md.  Algorithmic functions should return values and they should not print or plot.

2022-10-19 10:43 UTC, ZeroDayOwl commented
@mvsg2 you have duplicate PR #7406. Close one.

2022-10-19 10:44 UTC, ZeroDayOwl requested changes

2022-10-19 10:44 UTC, ZeroDayOwl commented on machine_learning/gaussian_naive_bayes.py
>      main()
Perhaps add doctest cases.

2022-10-19 11:43 UTC, closed without merging