Create reverse_linked_list.py
TheAlgorithms/Python pull request #7411
Opened 2022-10-18 18:56 UTC by ManishKumar219

### Describe your change:

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-18 19:05 UTC, CaedenPH requested changes
Please could you add [doctests](https://docs.python.org/3/library/doctest.html)

In addition, instead of printing the reverse linked list, would it be possible for you to return a reversed tree?

2022-10-18 19:05 UTC, CaedenPH commented on data_structures/linked_list/reverse_linked_list.py
> +
```suggestion
```

2022-10-18 19:05 UTC, CaedenPH commented on data_structures/linked_list/reverse_linked_list.py
> +
```suggestion
```

2022-10-18 19:05 UTC, CaedenPH commented on data_structures/linked_list/reverse_linked_list.py
> +llist.printList()
```suggestion
if __name__ == "__main__":
    # Driver program to test above functions
    llist = LinkedList()
    llist.push(20)
    llist.push(4)
    llist.push(15)
    llist.push(85)
    
    print("Given Linked List")
    llist.printList()
    llist.reverse()
    print("\nReversed Linked List")
    llist.printList()
 ```

2022-10-18 19:05 UTC, CaedenPH commented on data_structures/linked_list/reverse_linked_list.py
> +    def printList(self):
```suggestion
    def print_list(self):
```
Python uses `snake_case`

2022-10-18 19:05 UTC, CaedenPH commented on data_structures/linked_list/reverse_linked_list.py
> +    def push(self, new_data):
```suggestion
    def push(self, new_data) -> None:
```

2022-10-18 19:05 UTC, CaedenPH commented on data_structures/linked_list/reverse_linked_list.py
> +    def reverse(self):
```suggestion
    def reverse(self) -> None:
```

2022-10-18 19:05 UTC, CaedenPH commented on data_structures/linked_list/reverse_linked_list.py
> +    def __init__(self):
```suggestion
    def __init__(self) -> None:
```

2022-10-18 19:05 UTC, CaedenPH commented on data_structures/linked_list/reverse_linked_list.py
> +    def __init__(self, data):
```suggestion
    def __init__(self, data) -> None:
```

2022-10-19 11:28 UTC, cclauss commented
Duplicate https://github.com/TheAlgorithms/Python/blob/master/data_structures/linked_list/print_reverse.py

2022-10-19 11:28 UTC, closed without merging