Created sum_of_harmonic_series.py
TheAlgorithms/Python pull request #7504
Opened 2022-10-22 06:39 UTC by AkshitGulyan

Here in this code the formula for Harmonic sum is not used, Sum of the series is calculated by creating a list of the elements in the given Harmonic series and adding all the elements of that list !

**A list l1 is created which contains the elements of the Arithmetic Progression to which the given Harmonic Progression is linked and then a list l2 is created which contains the reciprocal of all the elements of list l1 which means list l2 contains all the elements of the given Harmonic Series.**

[Wikipedia link for better understanding of Harmonic Series](https://en.wikipedia.org/wiki/Harmonic_progression_(mathematics))

*[x] Add an algorithm?
*[ ] Fix a bug or typo in an existing algorithm?
*[ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-22 06:42 UTC, AkshitGulyan commented on maths/sum_of_harmonic_series.py
> +def main():
doctest is provided for main function at line no. 23

2022-10-22 06:42 UTC, AkshitGulyan commented on maths/sum_of_harmonic_series.py
> +    doctest.testmod()
here is the doctest

2022-10-22 11:50 UTC, ChrisO345 requested changes

2022-10-22 11:50 UTC, ChrisO345 commented on maths/sum_of_harmonic_series.py
> +def sum_of_hp(first_term, common_difference, no_of_terms):
```suggestion
def sum_of_hp(first_term: float, common_difference: float, no_of_terms: int) -> float:
```

2022-10-22 11:50 UTC, ChrisO345 commented on maths/sum_of_harmonic_series.py
> +
add doctests here: https://docs.python.org/3/library/doctest.html

2022-10-22 11:50 UTC, ChrisO345 commented on maths/sum_of_harmonic_series.py
> +    print(sum_of_hp(1 / 2, 2, 2))
```suggestion

```
this isn't needed

2022-10-22 11:50 UTC, ChrisO345 commented on maths/sum_of_harmonic_series.py
> +    doctest.testmod()
```suggestion
    import doctest
    doctest.testmod()
    
    print(sum_of_hp(1 / 2, 2, 2))
```

2022-10-22 16:19 UTC, cclauss commented on maths/sum_of_harmonic_series.py
> +        first_term = first_term + common_difference
```suggestion
        first_term += common_difference
```

2022-10-22 16:21 UTC, cclauss commented on maths/sum_of_harmonic_series.py
> +    l1 = [1 / first_term]
We require self-documenting variable names.
```suggestion
    arithmetic_progression = [1 / first_term]
```

2022-10-22 16:22 UTC, cclauss commented on maths/sum_of_harmonic_series.py
> +        l2 = [1 / x for x in l1]
```suggestion
        harmonic_series = [1 / step for step in arithmetic_progression]
```

2022-10-22 18:29 UTC, AkshitGulyan commented on maths/sum_of_harmonic_series.py
> +def sum_of_harmonic_progression(
Test File added !

2022-10-22 18:29 UTC, AkshitGulyan commented on maths/sum_of_harmonic_series.py
> +def sum_of_harmonic_progression(
Added !

2022-10-22 18:29 UTC, AkshitGulyan commented on maths/sum_of_harmonic_series.py
> +def sum_of_harmonic_progression(
Added!

2022-10-22 18:30 UTC, AkshitGulyan commented on maths/sum_of_harmonic_series.py
> +def sum_of_harmonic_progression(
Added !

2022-10-22 18:30 UTC, AkshitGulyan commented on maths/sum_of_harmonic_series.py
> +def sum_of_harmonic_progression(
Added !

2022-10-23 04:22 UTC, cclauss approved these changes
Added two doctests

2022-10-23 04:29 UTC, merged

2022-10-23 04:30 UTC, cclauss commented on maths/sum_of_harmonic_series.py
> +
These are doctests.