Matrix
TheAlgorithms/Python pull request #7533
Opened 2022-10-22 23:39 UTC by jdevers1

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-23 01:12 UTC, ChrisO345 requested changes

2022-10-23 01:12 UTC, ChrisO345 commented on matrix/count_paths.py
> +'*' will demostrate a path
```suggestion
'*' will demonstrate a path
```

2022-10-29 14:43 UTC, CaedenPH reviewed
Looks good - small changes

2022-10-29 14:43 UTC, CaedenPH commented on matrix/count_paths.py
> +def dfs(grid: "list[list[int]]", row: int, col: int, visit: set) -> int:
```suggestion
def depth_first_search(grid: list[list[int]], row: int, col: int, visit: set) -> int:
```

2022-10-29 14:43 UTC, CaedenPH commented on matrix/count_paths.py
> +    >>> dfs(grid, start_row, start_col, visited)
```suggestion
    >>> grid = [[0, 0, 0, 0], [1, 1, 0, 0], [0, 0, 0, 1], [0, 1, 0, 0]]
    >>> dfs(grid, 0, 0, set())
```

2022-10-29 14:43 UTC, CaedenPH commented on matrix/count_paths.py
> +    >>> dfs(grid, start_row, start_col, visited)
```suggestion
    >>> grid = [[0, 0, 0, 0, 0], [0, 1, 1, 1, 0], [0, 1, 1, 1, 0], [0, 0, 0, 0, 0]]
    >>> dfs(grid, 0, 0, set())
```

2022-10-30 05:08 UTC, ChrisO345 commented on matrix/count_paths.py
> +    count += dfs(grid, row, col - 1, visit)
```suggestion
    count += depth_first_search(grid, row + 1, col, visit)
    count += depth_first_search(grid, row - 1, col, visit)
    count += depth_first_search(grid, row, col + 1, visit)
    count += dfs(grid, row, col - 1, visit)
```

2022-10-30 05:19 UTC, ChrisO345 approved these changes

2022-10-30 05:20 UTC, merged