Added forward bias voltage
TheAlgorithms/Python pull request #7871
Opened 2022-10-30 13:06 UTC by sadiqebrahim

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-30 13:07 UTC, CaedenPH approved these changes
Looks good

2022-10-30 13:07 UTC, CaedenPH commented on electronics/forward_bias_current.py
> +
```suggestion
```

2022-10-30 13:10 UTC, CaedenPH commented
@cclauss I know this is on hold but its a pretty quick and easy one to merge

2022-10-30 13:18 UTC, cclauss commented on electronics/forward_bias_current.py
> +    rev_sat_current: float,  # Reverse Saturation Current
```suggestion
    forward_voltage: float,
    reverse_saturation_current: float,
```

2023-08-01 02:07 UTC, tianyizheng02 requested changes

2023-08-01 02:07 UTC, tianyizheng02 commented on electronics/forward_bias_current.py
> +from scipy.constants import Boltzmann, physical_constants
```suggestion
from scipy import constants
```
`constants` already has an easy way to get the value of constants without needing to access the underlying `physical_constants` dict: `constants.get()`

2023-08-01 02:07 UTC, tianyizheng02 commented on electronics/forward_bias_current.py
> +        )
```suggestion
    if forward_voltage < 0:
        raise ValueError("Forward voltage cannot be negative")
    if reverse_saturation_current <= 0:
        raise ValueError("Reverse saturation current must be positive")
    if reverse_saturation_current > 1e-5:
        raise ValueError("Reverse saturation current cannot be greater than 1e-5")
    return reverse_saturation_current * (
        exp(
            forward_voltage * constants.get("electron volt") / (constants.k * T)
        ) - 1
    )
```

2023-08-01 07:55 UTC, cclauss commented on electronics/forward_bias_current.py
> +    This is calculated from the given two values.
```suggestion
    Calculate the Forward Bias Current of a pn junction diode from given two values.
```

2023-09-30 17:38 UTC, closed without merging