Reduce the complexity of linear_algebra/src/polynom_for_points.py
TheAlgorithms/Python pull request #7948
Opened 2022-11-02 17:56 UTC by MaximSmolskiy

### Describe your change:

Reduce the complexity of linear_algebra/src/polynom_for_points.py from 23 to 17

Fixes: #7942

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-11-02 18:19 UTC, cclauss requested changes
Nice!  https://www.scivision.dev/python-f-string-speed

2022-11-02 18:19 UTC, cclauss commented on linear_algebra/src/polynom_for_points.py
> +        return "x=" + str(coordinates[0][0])
Shorter, faster, and easier to read.
```suggestion
        return f"x={coordinates[0][0]}"
```

2022-11-02 18:19 UTC, cclauss commented on linear_algebra/src/polynom_for_points.py
> +        solved += "x^" + str(x - (count + 1)) + "*" + str(solution[count])
```suggestion
        solved += f"x^{x - (count + 1)}*{solution[count]}"
```

2022-11-02 18:19 UTC, cclauss commented on linear_algebra/src/polynom_for_points.py
> +            solution[count] = remove_e[0] + "*10^" + remove_e[1]
```suggestion
            solution[count] = f"{remove_e[0]}*10^{remove_e[1]}"
```

2022-11-02 18:40 UTC, cclauss approved these changes
Awesome work!  Other pull requests that further reduce our `max-complexity` would be warmly received.

2022-11-02 18:40 UTC, merged

2022-11-25 12:15 UTC, will472 commented
Unsubscribe 

Sent from my iPhone

> On Nov 2, 2022, at 2:25 PM, Christian Clauss ***@***.***> wrote:
> 
> ﻿
> @cclauss requested changes on this pull request.
> 
> Nice! https://www.scivision.dev/python-f-string-speed
> 
> In linear_algebra/src/polynom_for_points.py:
> 
> >  
> -        if len(coordinates) == 1 and coordinates[0][0] == 0:
> -            check = 2
> -            solved = "x=0"
> -    except Exception:
> -        check = 3
> +    set_x = {x for x, _ in coordinates}
> +    if len(set_x) == 1:
> +        return "x=" + str(coordinates[0][0])
> Shorter, faster, and easier to read.
> 
> ⬇️ Suggested change
> -        return "x=" + str(coordinates[0][0])
> +        return f"x={coordinates[0][0]}"
> In linear_algebra/src/polynom_for_points.py:
> 
> >  
> -        return solved
> +    while count < x:
> +        remove_e: list[str] = solution[count].split("E")
> +        if len(remove_e) > 1:
> +            solution[count] = remove_e[0] + "*10^" + remove_e[1]
> +        solved += "x^" + str(x - (count + 1)) + "*" + str(solution[count])
> ⬇️ Suggested change
> -        solved += "x^" + str(x - (count + 1)) + "*" + str(solution[count])
> +        solved += f"x^{x - (count + 1)}*{solution[count]}"
> In linear_algebra/src/polynom_for_points.py:
> 
> >  
> -        return solved
> +    while count < x:
> +        remove_e: list[str] = solution[count].split("E")
> +        if len(remove_e) > 1:
> +            solution[count] = remove_e[0] + "*10^" + remove_e[1]
> ⬇️ Suggested change
> -            solution[count] = remove_e[0] + "*10^" + remove_e[1]
> +            solution[count] = f"{remove_e[0]}*10^{remove_e[1]}"
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.

2022-11-25 12:25 UTC, cclauss commented
@will472 Please click the `unsubscribe` at the bottom of the right column of this page.