Add unbounded_knapsack.py
TheAlgorithms/Python pull request #7999
Opened 2022-11-21 13:17 UTC by kenzonobre

### Describe your change:

Add unbounded knapsack algorithm, which is an extension of the 0-1 knapsack problem.

0-1 Knapsack Problem :
https://en.wikipedia.org/wiki/Knapsack_problem
https://www.geeksforgeeks.org/0-1-knapsack-problem-dp-10/

Unbounded knapsack : 
https://www.geeksforgeeks.org/unbounded-knapsack-repetition-items-allowed/

* [X] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [X] This pull request is all my own work -- I have not plagiarized.
* [X] I know that pull requests will not be merged if they fail the automated tests.
* [X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [X] All new Python files are placed inside an existing directory.
* [X] All filenames are in all lowercase characters with no spaces or dashes.
* [X] All functions and variable names follow Python naming conventions.
* [X] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [X] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [X] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [X] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-12-14 17:14 UTC, kenzonobre commented
@cclauss could you please review my code? I could work on it more if necessary, but I think it looks good

2022-12-14 17:25 UTC, CaedenPH approved these changes
Looks good to me, but I'm sure Cclauss will find some problems ;)

2023-06-06 13:45 UTC, kenzonobre commented
@cclauss could you please review my code? I could work on it more if necessary, but I think it looks good

2023-06-06 14:22 UTC, cclauss requested changes
* [ ] How is this different than all our other knapsack algorithms?
* [ ] Is it faster?  Can we prove that with a benchmark?
* [ ] How is this algorithm unbound if the first parameter is `capacity`?
* [ ] Please add a test that demonstrates how would this unbound algorithm would deal with `weights` and `values` that were never-ending `cycles`?  https://docs.python.org/3/library/itertools.html#itertools.cycle

2023-06-06 14:22 UTC, cclauss commented on knapsack/unbounded_knapsack.py
> +
```suggestion
```

2023-06-06 14:22 UTC, cclauss commented on knapsack/unbounded_knapsack.py
> +    >>> knapsack(c, items_weights, items_values)
```suggestion
    >>> knapsack(capacity=70, weights=(40, 900, 120), values=(10, 20, 30))
```
Please repeat for the other tests.

Please add tests for:
`capacity = 0`
`capacity - -5`
`len(values)` != `len(weights)`
`len(values) == 5` and `len(weights) == 0`
etc.

2023-09-30 17:38 UTC, closed without merging