Add backward_warping to digital_image_processing
TheAlgorithms/Python pull request #8014
Opened 2022-12-04 13:22 UTC by TimelessPersona

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-12-07 07:51 UTC, abhishekmulik commented
Looks good !! nice work

2022-12-07 12:18 UTC, glass2300 reviewed
looks good, nice

2022-12-08 18:29 UTC, CaedenPH requested changes
Please could you add some [doctests](https://docs.python.org/3/library/doctest.html)

2022-12-08 18:29 UTC, CaedenPH commented on digital_image_processing/backward_warping/backward_warping.py
> +    M4 = np.array([[1, 0.2, 0], [0.2, 1, 0], [0, 0, 1]])
```suggestion
    M1 = np.array([[1, 0, 50], [0, 1, 100], [0, 0, 1]])
    M2 = np.array([[1.5, 0, 0], [0, 1.5, 0], [0, 0, 1]])
    M3 = np.array(
        [
            [np.cos(angle), -np.sin(angle), 0],
            [np.sin(angle), np.cos(angle), 0],
            [0, 0, 1],
        ]
    )
    M4 = np.array([[1, 0.2, 0], [0.2, 1, 0], [0, 0, 1]])
    
    angle = np.deg2rad(15)
```

2023-09-30 04:45 UTC, closed without merging

2023-09-30 04:45 UTC, tianyizheng02 commented
Closing due to lack of doctests and lack of response