Add autoclave cipher
TheAlgorithms/Python pull request #8029
Opened 2022-12-14 17:06 UTC by VictorRS27

### Describe your change:

I'm adding the autoclave or autokey cipher.
Is similar to the vigenerè cipher, but using the own plaintext as the key.
The code implements an encrypt and a decrypt function.
For more info:
https://en.wikipedia.org/wiki/Autokey_cipher

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-12-14 17:22 UTC, CaedenPH requested changes
Please link some documentation at the start of the file and include more doctests within each function

2022-12-14 17:22 UTC, CaedenPH commented on ciphers/autoclave.py
> +
```suggestion
```
Typically, we want the parameter names to be self-documenting so this isn't really necessary

2022-12-14 17:22 UTC, CaedenPH commented on ciphers/autoclave.py
> +    if key == "":
```suggestion
    if not plaintext:
        raise ValueError("plaintext is empty")
    if not key:
```

2022-12-14 17:22 UTC, CaedenPH commented on ciphers/autoclave.py
> +    key = key + plaintext
```suggestion
    key += plaintext
```

2022-12-14 17:22 UTC, CaedenPH commented on ciphers/autoclave.py
> +def encrypt(plaintext, key) -> str:
```suggestion
def encrypt(plaintext, key) -> str:
```
These parameters need to be typehinted

2022-12-14 17:22 UTC, CaedenPH commented on ciphers/autoclave.py
> +decrypt("jsqqs avvwo", "coffee")
please move this into an `if __name__ == "__main__":` block

2022-12-15 06:49 UTC, cclauss commented on ciphers/autoclave.py
> +def encrypt(plaintext, key) -> str:
Clave is Latin for key so the more popular name for this algorithm is autokey.
```suggestion
”””
https://en.wikipedia.org/wiki/Autokey_cipher
> An autokey cipher (also known as the autoclave cipher) is a cipher that incorporates the message (the plaintext into the key. The key is generated from the message in some automated fashion, sometimes by selecting certain letters from the text or, more commonly, by adding a short primer key to the front of the message.
”””


def encrypt(plaintext, key) -> str:
```

2022-12-15 06:52 UTC, cclauss commented on ciphers/autoclave.py
> +    if type(plaintext) != str:
PEP8: Use `isinstance(plaintext, str)` instead of directly comparing types.

2022-12-18 22:06 UTC, cclauss approved these changes

2022-12-18 22:26 UTC, merged

2026-09-06 16:27 UTC, cclauss commented
@priya-sundaram-dev Several years ago, when I merged this pull request, I disabled five unrelated algorithms.  I have no idea why I disabled them, but perhaps they were slowing down our CI tests.  Can you please create a pull request that re-enables them and also re-enables neural_network/perceptron.py.DISABLED, as discussed in:
* #15206

2026-09-06 16:47 UTC, priya-sundaram-dev commented
Done — opened #15208. It re-enables the four ML examples plus `neural_network/perceptron.py`.

The reason they wouldn't come back as-is: they'd bit-rotted against scikit-learn. `plot_confusion_matrix` and the Boston dataset were both removed in scikit-learn 1.2, so `--doctest-modules` couldn't even import the files. I swapped in `ConfusionMatrixDisplay.from_estimator` and `load_diabetes`, dropped the artificial `time.sleep()`s, and for the perceptron I seeded a local RNG + capped the training loop so it can't spin forever on non-separable data. All doctests + ruff pass locally.