Deblur and Denoise using Richardson Lucy Deconvolution for Computer Vision tasks
TheAlgorithms/Python pull request #8038
Opened 2022-12-20 03:43 UTC by rzimmerdev

### Describe your change:
I've added the Richardson Lucy deconvolution algorithm, as well as some supporting auxiliary methods.
This algorithm is useful for recovering degraded images, given a known noise and/or blurring function.

* [x] Add an algorithm?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [X] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [X] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-12-21 08:05 UTC, alleycat786 approved these changes
tq so much!

2022-12-21 08:05 UTC, alleycat786 approved these changes
tq so much!

2022-12-21 08:06 UTC, alleycat786 approved these changes
tq so muchh! good work

2022-12-21 08:07 UTC, alleycat786 approved these changes
tq!

2022-12-21 08:07 UTC, alleycat786 commented
tq so much good work

2022-12-21 08:09 UTC, alleycat786 approved these changes
tq so much

2023-08-13 21:33 UTC, tianyizheng02 requested changes

2023-08-13 21:33 UTC, tianyizheng02 commented on computer_vision/richardson_lucy.py
> +    for i in range(steps):
```suggestion
    for _ in range(steps):
```
`i` is never used in the loop body, and this is causing the pre-commit to fail

2023-08-13 21:33 UTC, tianyizheng02 commented on computer_vision/haralick_descriptors.py
Wrong PR, already included in #8004

2023-08-13 21:33 UTC, tianyizheng02 commented on computer_vision/richardson_lucy.py
> +    using Fourier transformations.
```suggestion
    using Fourier transforms.
```
Nitpick: "Fourier transforms", not "Fourier transformations"

2023-08-13 21:33 UTC, tianyizheng02 commented on computer_vision/richardson_lucy.py
> +        return matrix
If the kernel is too big, why not raise an error?

2023-08-13 21:33 UTC, tianyizheng02 commented on computer_vision/richardson_lucy.py
> +    steps = int(input())
Can we get prompt messages for the `input` calls

2023-08-13 21:33 UTC, tianyizheng02 commented on computer_vision/richardson_lucy.py
> +    p, q = (size for size in reference.shape)
Are these variables necessary? Why not just use `reference.shape[0]` and `reference.shape[1]`?

2023-08-13 21:33 UTC, tianyizheng02 commented on computer_vision/richardson_lucy.py
> +def get_motion_psf(shape: tuple, angle: float, num_pixel_dist: int = 20) -> np.ndarray:
```suggestion
def get_motion_psf(shape: tuple[int, int], angle: float, num_pixel_dist: int = 20) -> np.ndarray:
```

2023-09-30 04:49 UTC, tianyizheng02 commented
This PR is unfortunately taking too long and too much effort to fix, and I don't have the time because we maintainers have to clear out the backlog of PRs as much as possible before Hacktoberfest. In addition, it appears that this PR has failing doctests even when the code formatting and styling has been fixed.

2023-09-30 04:49 UTC, closed without merging