add word_break dynamic approach up -> down.
TheAlgorithms/Python pull request #8039
Opened 2022-12-20 11:10 UTC by alexpantyukhin

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-12-20 11:14 UTC, alexpantyukhin commented on dynamic_programming/word_break.py
> +def word_break(s: str, word_dict: list[str]) -> bool:
fixed

2022-12-20 19:26 UTC, CaedenPH reviewed
Looks good, just small changes

2022-12-20 19:56 UTC, alexpantyukhin commented
fixed

2022-12-21 05:21 UTC, CaedenPH approved these changes
@cclauss Can you review please

2022-12-29 06:01 UTC, alexpantyukhin commented
@cclauss Could you please review this PR? It's important to know your feedback about this.

2022-12-29 21:33 UTC, cclauss requested changes

2022-12-29 21:33 UTC, cclauss commented on dynamic_programming/word_break.py
> +sequence of one or more dictionary words.
It is a list of `words` so it is confusing for the reader if we call it a dict.
```suggestion
Given a string and a list of words, return true if the string can be
segmented into a space-separated sequence of one or more words.
```

2022-12-29 21:33 UTC, cclauss commented on dynamic_programming/word_break.py
> +Note that the same word in the dictionary may be reused
```suggestion
Note that the same word may be reused
```

2022-12-29 21:33 UTC, cclauss commented on dynamic_programming/word_break.py
> +The Trie keeps all wordDict words. It will be useful for scanning
```suggestion
The Trie will be used to store the words. It will be useful for scanning
```

2022-12-29 21:33 UTC, cclauss commented on dynamic_programming/word_break.py
> +def word_break(string: str, word_dict: list[str]) -> bool:
```suggestion
def word_break(string: str, words: list[str]) -> bool:
```

2022-12-29 21:33 UTC, cclauss commented on dynamic_programming/word_break.py
> +    ValueError: the word_dict should a list of non empty string
```suggestion
    ValueError: the words should be a list of non-empty strings
```

2022-12-29 21:33 UTC, cclauss commented on dynamic_programming/word_break.py
> +    ValueError: the word_dict should a list of non empty string
```suggestion
    ValueError: the words should be a list of non-empty strings
```

2022-12-29 21:33 UTC, cclauss commented on dynamic_programming/word_break.py
> +        raise ValueError("the word_dict should a list of non empty string")
```suggestion
        raise ValueError("the words should be a list of non-empty strings")
```

2022-12-29 21:33 UTC, cclauss commented on dynamic_programming/word_break.py
> +    for word in word_dict:
```suggestion
    for word in words:
```

2022-12-29 21:33 UTC, cclauss commented on dynamic_programming/word_break.py
> +        isinstance(item, str) and len(item) > 0 for item in word_dict
```suggestion
    if not isinstance(words, list) or not all(
        isinstance(item, str) and len(item) > 0 for item in words
```

2022-12-29 21:33 UTC, cclauss commented on dynamic_programming/word_break.py
> +    def is_breakable(index: int) -> bool:
All functions need tests.

2022-12-30 05:42 UTC, alexpantyukhin commented on dynamic_programming/word_break.py
> +    def is_breakable(index: int) -> bool:
fixed, thanks!

2022-12-30 05:47 UTC, cclauss approved these changes

2022-12-30 05:47 UTC, merged