Remove a slash in path to save the file correctly on Linux
TheAlgorithms/Python pull request #8053
Opened 2022-12-27 09:11 UTC by Erfaniaa

### Describe your change:

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-12-27 12:55 UTC, CaedenPH approved these changes
Looks good - Great spot

2022-12-27 12:57 UTC, CaedenPH approved these changes
Looks good - Great spot

2022-12-27 15:56 UTC, itsamirhn commented on computer_vision/flip_augmentation.py
>          file_root = f"{OUTPUT_DIR}/{file_name}_FLIP_{letter_code}"
```suggestion
        file_root = os.path.join(OUTPUT_DIR, f"{file_name}_FLIP_{letter_code}")
```

2022-12-27 21:23 UTC, cclauss commented on computer_vision/flip_augmentation.py
>          file_root = f"{OUTPUT_DIR}/{file_name}_FLIP_{letter_code}"
Can we use `pathlib` instead?

2023-08-13 22:10 UTC, tianyizheng02 requested changes

2023-08-13 22:10 UTC, tianyizheng02 commented on computer_vision/flip_augmentation.py
>          file_root = f"{OUTPUT_DIR}/{file_name}_FLIP_{letter_code}"
```suggestion
        file_root = Path(OUTPUT_DIR, f"{file_name}_FLIP_{letter_code}")
```

2023-08-15 20:37 UTC, cclauss approved these changes

2023-08-15 20:37 UTC, merged