Update permutations.py
TheAlgorithms/Python pull request #8102
Opened 2023-01-26 07:47 UTC by sundaram2021

Earlier in the permutation function it is creating an infinite recursion which is causing an error 

instead of that I used backtracking to get the output

*[x]  Fixed a bug or typo in an existing algorithm in permutations.py?

2023-01-26 07:58 UTC, CaedenPH requested changes
Instead of deleting the old code, perhaps create an alternate function using the backtracking method, while keeping the original function.

2023-01-26 08:17 UTC, sundaram2021 commented
I have created a new function named as permute2 with the backtracking method

2023-04-24 06:02 UTC, rohan472000 requested changes

2023-04-24 06:02 UTC, rohan472000 commented on data_structures/arrays/permutations.py
> +
remove `from typing import List` as it is unused , creating pre-commit error.

2023-05-17 00:16 UTC, ChrisO345 submitted a review, later dismissed

2023-05-17 00:16 UTC, ChrisO345 commented on data_structures/arrays/permutations.py
> +    def backtrack(first=0):
```suggestion
	 """
    Return all permutations.
    >>> from itertools import permutations
    >>> numbers= [1,2,3]
    >>> all(list(nums) in permute2(numbers) for nums in permutations(numbers))
    True
    """
    def backtrack(first=0):
```

2023-05-17 14:52 UTC, sundaram2021 commented on data_structures/arrays/permutations.py
> +    def backtrack(first=0):
added that

2023-05-18 23:40 UTC, ChrisO345 requested changes
This needs to be inline

2023-05-18 23:40 UTC, ChrisO345 commented on data_structures/arrays/permutations.py
> +     [[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 2, 1], [3, 1, 2]]
```suggestion
    [[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 2, 1], [3, 1, 2]]
```

2023-05-19 01:07 UTC, sundaram2021 commented on data_structures/arrays/permutations.py
> +     [[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 2, 1], [3, 1, 2]]
can i commit your suggestion

2023-05-31 00:56 UTC, ChrisO345 approved these changes

2023-05-31 00:57 UTC, merged