Sort the linked list using quicksort technique
TheAlgorithms/Python pull request #8115
Opened 2023-02-03 07:19 UTC by Darpan-Balar

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2023-02-03 07:31 UTC, CaedenPH requested changes
Please typehint every function parameter and return.
Please also add [doctests](https://docs.python.org/3/library/doctest.html)

2023-02-03 07:31 UTC, CaedenPH commented on data_structures/linked_list/quicksort_linkedlist.py
> +    def printll(self):
```suggestion
    def print_linked_list(self):
```

2023-02-03 07:31 UTC, CaedenPH commented on data_structures/linked_list/quicksort_linkedlist.py
> +        return
```suggestion
```
Unecessary

2023-02-03 07:31 UTC, CaedenPH commented on data_structures/linked_list/quicksort_linkedlist.py
> +        return
```suggestion
```
Unecessary

2023-02-03 07:31 UTC, CaedenPH commented on data_structures/linked_list/quicksort_linkedlist.py
> +        if temp == None:
```suggestion
        if temp is None:
```

2023-02-03 07:31 UTC, CaedenPH commented on data_structures/linked_list/quicksort_linkedlist.py
> +            return "Linked List is empty"
```suggestion
            return
```
Returning `str` is a bad idea - Either raise an error, return, or print that it is empty

2023-02-03 07:31 UTC, CaedenPH commented on data_structures/linked_list/quicksort_linkedlist.py
> +    if start == None or start.next == None:
```suggestion
    if start is None or start.next is None:
```

2023-02-03 07:31 UTC, CaedenPH commented on data_structures/linked_list/quicksort_linkedlist.py
> +        return
```suggestion
```
Again, unnecessary

2023-04-24 18:43 UTC, rohan472000 requested changes

2023-04-24 18:43 UTC, rohan472000 commented on data_structures/linked_list/quicksort_linkedlist.py
> +        return
For the first issue in `ruff` failure, you can simply remove the `return` statement as it is not doing anything useful.

2023-04-24 18:43 UTC, rohan472000 commented on data_structures/linked_list/quicksort_linkedlist.py
> +        if temp == None:
you should replace the comparison to `None` with `is None` in line-36.

2023-04-24 18:43 UTC, rohan472000 commented on data_structures/linked_list/quicksort_linkedlist.py
> +        "Enter the space seperated values of numbers to be inserted in linkedlist prompted below:"
For the line length issue in line-81, you can split the line into two or more shorter lines

2023-09-30 04:41 UTC, closed without merging

2023-09-30 04:41 UTC, tianyizheng02 commented
Closing due to lack of response and lack of unit tests.