added documentation
TheAlgorithms/Python pull request #8129
Opened 2023-02-08 14:04 UTC by Another9621

### Describe your change:

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2023-02-08 14:06 UTC, Another9621 commented
added documentation to \Python\data_structures\arrays\prefix_sum file under __init__ function
![doc](https://user-images.githubusercontent.com/98016085/217552451-7b71ff1e-4227-4c9e-b1f1-516ce4caaa3b.png)

2023-02-10 11:36 UTC, CaedenPH requested changes
These documentation changes are quite trivial and don't add much information that the user doesn't know

2023-02-10 11:36 UTC, CaedenPH commented on data_structures/arrays/permutations.py
> +        return [nums.copy()] #returns a copy of list nums
This is self explanatory

2023-02-10 11:36 UTC, CaedenPH commented on data_structures/arrays/permutations.py
> +if any error is there it will print the error and its cause in stdout'''
Instead of adding this to every algorithm file, perhaps you could mention the purpose of this in the README, or some other informativ eplace

2023-02-10 11:36 UTC, CaedenPH commented on data_structures/arrays/prefix_sum.py
> +        i.e, element at index 3 of prefix_sum has value=(array[0]+array[1]+array[2])"""
This is again self explanatory

2023-04-01 12:29 UTC, closed without merging