Documentation
TheAlgorithms/Python pull request #8646
Opened 2023-04-12 17:47 UTC by Ranausama420

### Describe your change:

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2023-04-14 23:24 UTC, tianyizheng02 commented
How is this PR different from #8633?

2023-05-10 09:43 UTC, ChrisO345 commented
In order to merge a PR, all test must pass, can you try to fix these errors.

2023-05-11 16:36 UTC, CaedenPH requested changes
This change does not add any information that the person reading the code cannot infer themselves - Seems pointless

2023-05-11 16:36 UTC, CaedenPH commented on ciphers/mixed_keyword_cypher.py
> +    temp = list(set(key))
This is not a documentation change

2023-05-11 16:36 UTC, CaedenPH commented on ciphers/mixed_keyword_cypher.py
> +      based on a key-shift cipher"""
Firstly, this isn't inside of a function and isn't formatted
Secondly, what does this tell the user that we don't already know? Everything you said is clearly shown by typehints and naming conventions

2023-05-11 16:36 UTC, CaedenPH commented on ciphers/mixed_keyword_cypher.py
> +    print(len_temp)
Remove these prints
```suggestion
```

2023-05-11 16:36 UTC, CaedenPH commented on ciphers/mixed_keyword_cypher.py
> +
```suggestion
```
Along with this random temp code

2023-05-11 16:36 UTC, CaedenPH commented on ciphers/mixed_keyword_cypher.py
> +     indices of the alphabets list as keys and the values fromthe corresponding modalpha lists as values"""
These should be in the forms of comments, not docstrings

2023-05-11 22:04 UTC, tianyizheng02 commented
@CaedenPH this PR is basically identical to an earlier PR #8633 (same commits as this one), so one of the two should be closed. We can probably keep this PR since you already started a review on this one.

There's also an even earlier PR #8626 by a different author that fixes the same issue #8622, so it'd be good if you could take a look at that one as well.

2023-05-11 22:06 UTC, tianyizheng02 requested changes
> This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.

Please make separate PRs for your changes to `mixed_keyword_cypher.py` and your changes to the other files

2023-07-31 01:19 UTC, tianyizheng02 commented
Closed as duplicate of #8633

2023-07-31 01:19 UTC, closed without merging