Create mergesortedarrays.py
TheAlgorithms/Python pull request #8692
Opened 2023-04-25 17:36 UTC by kylekirch

Merges arrays that are sorted in ascending order. The resulting array contains all elements of both arrays in ascending order.

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2023-04-25 17:39 UTC, kylekirch commented
This is my first commit to this repo, the algo I have put together merges arrays that are sorted in ascending order. The resulting array contains all elements of both arrays in ascending order. This algo is commonly used in many different situations.

2023-04-25 23:49 UTC, amirsoroush commented on data_structures/arrays/mergesortedarrays.py
> +    while i < len(arr1) and j < len(arr2):
test

2023-04-26 14:49 UTC, rohan472000 requested changes
use `black .` for pre-commit failure , also check CONTRIBUTING.md in repo for pre-requisites before making PRs.

2023-04-26 14:51 UTC, rohan472000 requested changes

2023-04-26 14:51 UTC, rohan472000 commented on data_structures/arrays/mergesortedarrays.py
> +    """
add more unique doctests with empty lists.

2023-09-30 17:38 UTC, closed without merging