The input can be either comma or space separated value -- Improved user experience
TheAlgorithms/Python pull request #8721
Opened 2023-05-11 19:29 UTC by Prade7

### Describe your change:

The code change was done in binary_search.py file and it will allow user to give input as comma separated or space separated value as input .

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2023-05-11 19:33 UTC, Prade7 commented
I didn't change any other file . I don't know why it is failing

2023-05-12 06:22 UTC, tianyizheng02 requested changes
The current change will parse the input incorrectly if there are commas in the numbers themselves, so that case needs to be handled

2023-05-12 06:22 UTC, tianyizheng02 commented on searches/binary_search.py
> +    if "," in user_input:
This would break if there were both commas and spaces in the input, i.e. `1,000 1,001 1,002`

2023-05-12 06:22 UTC, tianyizheng02 commented on searches/binary_search.py
> +        collection = sorted(map(int, user_input.split(",")))
```suggestion
        collection = sorted(int(num) for num in user_input.split(","))
```

2023-05-12 06:22 UTC, tianyizheng02 commented on searches/binary_search.py
> +        collection = sorted(map(int, user_input.split(" ")))
```suggestion
        collection = sorted(int(num) for num in user_input.split(" "))
```

2023-05-12 06:22 UTC, tianyizheng02 commented on searches/binary_search.py
> +        collection = sorted(map(int, user_input.split(" ")))
```suggestion
        collection = sorted(int(num) for num in user_input.split(" "))
```

2023-05-12 06:26 UTC, tianyizheng02 commented
> I didn't change any other file . I don't know why it is failing

It's failing because `ruff` found errors in some other files that was edited by a previous contributor. Try running `ruff check --fix .` to see if that can automatically fix the errors.

2023-05-21 06:29 UTC, tianyizheng02 commented on searches/binary_search.py
> +    if "," in user_input:
Just believing that the user won't provide input in a certain way generally isn't a good way to deal with user input. If it's something that a user might reasonably do then we should still handle it somehow. At the very least, you could just prohibit the user from using both commas and spaces at the same time.

2023-08-01 01:13 UTC, tianyizheng02 commented
I'm closing this PR because, as I've pointed out already, it doesn't properly handle both commas and spaces. Unfortunately, we're currently trying to clear the massive backlog of open PRs, and we don't have the time to completely rework this PR.

2023-08-01 01:13 UTC, closed without merging