Create count negative numbers in matrix algorithm
TheAlgorithms/Python pull request #8813
Opened 2023-06-08 15:33 UTC by CaedenPH

### Describe your change:
Three implementations of this algorithm are implemented and benchmarked together with doctests

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2023-06-08 15:50 UTC, CaedenPH commented
Note this pr supposedly has lack of tests however the benchmark function shouldn't have doctests anyway
https://github.com/TheAlgorithms/Python/blob/master/ciphers/atbash.py#L41
As shown, this benchmark function doesnt have doctests either

2023-06-09 13:03 UTC, cclauss commented
When would we want to use this algorithm?

2023-06-09 13:04 UTC, cclauss commented on matrix/count_negative_numbers_in_sorted_matrix.py
> +Given an `m x n` matrix grid which is sorted in non-increasing order
```suggestion
Given an `m x n` matrix grid which is sorted in decreasing order
```

2023-06-09 13:04 UTC, cclauss commented on matrix/count_negative_numbers_in_sorted_matrix.py
> +both row-wise and column-wise, return the number of negative numbers in grid.
```suggestion
both first row-wise and then column-wise, return the number of negative numbers in grid.
```

2023-06-09 15:16 UTC, cclauss commented on matrix/count_negative_numbers_in_sorted_matrix.py
> +both row-wise and column-wise, return the number of negative numbers in grid.
Now I understand better...
```suggestion
Given an matrix of numbers in which all rows and all columns are sorted in decreasing
order, return the number of negative numbers in grid.
```

2023-06-09 16:48 UTC, CaedenPH commented
> When would we want to use this algorithm?

@cclauss If you have a grid of sorted numbers in descending order in a matrix, this algorithm can be used to count the number of negative numbers. Not sure when someone would want to use it, but then again when would someone want to use the quine from other/quine?
As far as I'm aware this repository is just about algorithms, not necessarily useful ones. 

To answer your previous comment about validating the matrix, I don't think that is necessary. For searches that require sorted arrays, there aren't checks to ensure that those arrays are sorted so I think indicating that the matrix must be sorted is good enough

2023-06-10 06:10 UTC, cclauss requested changes
This is looking cool!!

2023-06-10 06:10 UTC, cclauss commented on matrix/count_negative_numbers_in_sorted_matrix.py
> +    return total
```suggestion
    return len([number for row in grid for number in row if number < 0])
```

2023-06-10 06:10 UTC, cclauss commented on matrix/count_negative_numbers_in_sorted_matrix.py
> +    return total
```suggestion
    total = 0
    for row in grid:
        for i, number in enumerate(row):
            if number < 0:
                total += len(row) - i
                break
    return total
```

2023-06-10 06:10 UTC, cclauss commented on matrix/count_negative_numbers_in_sorted_matrix.py
> +
Let's generate `grid` just once and then import it.
```suggestion

grid = generate_large_matrix()


```

2023-06-10 06:10 UTC, cclauss commented on matrix/count_negative_numbers_in_sorted_matrix.py
> +        ",count_negatives_brute_force_with_break,generate_large_matrix"
```suggestion
        ",count_negatives_brute_force_with_break,grid"
```

2023-06-10 06:10 UTC, cclauss commented on matrix/count_negative_numbers_in_sorted_matrix.py
> +        time = timeit(f"{func}(generate_large_matrix())", setup=setup, number=5000)
Let's keep the runtime for the fastest algorithm at about 1 second.
```suggestion
        time = timeit(f"{func}(grid=grid)", setup=setup, number=500)
```

2023-06-10 11:54 UTC, CaedenPH commented
@cclauss All changes have been implemented and tests are passing

2023-06-10 12:21 UTC, cclauss approved these changes
Nice!  Thanks for doing this.

2023-06-10 12:21 UTC, merged

2023-06-10 12:27 UTC, cclauss commented
I have never figured out https://docs.python.org/3/library/bisect.html but it would be interesting to benchmark against an implementation that leveraged it.