Adel Docker devcontainer configuration files
TheAlgorithms/Python pull request #8887
Opened 2023-07-23 17:57 UTC by HManiac74

Added configuration files for running the repo in a Docker dev Container

2023-07-23 18:12 UTC, cclauss requested changes
We already have GitPod...  Why is this any better than that?

We run on Python 3.11 so please upgrade from `bullseye` to `bookworm` and remove all comments about Python < 3.11.

Remove all the comments about Node.js because this repo has none of that.

2023-07-23 18:12 UTC, cclauss commented on .devcontainer/devcontainer.json
> +				"python.linting.pylintPath": "/usr/local/py-utils/bin/pylint"
We use `ruff` to replace all of this.  Please ensure that `ruff` is working properly.
```suggestion
				"python.defaultInterpreterPath": "/usr/local/bin/python",
				"python.linting.enabled": true,
				"python.formatting.blackPath": "/usr/local/py-utils/bin/black",
				"python.linting.mypyPath": "/usr/local/py-utils/bin/mypy",
```

2023-07-23 18:12 UTC, cclauss commented on .devcontainer/devcontainer.json
> +
Add a \n to the end of both files to get rid of ⛔ as seen at https://github.com/TheAlgorithms/Python/pull/8887/files#

2023-07-25 17:18 UTC, cclauss commented on requirements.txt
> +ruff
Not needed.  Please remove.  There is a difference between runtime dependencies and testing dependencies.

2023-07-25 17:20 UTC, cclauss commented on .devcontainer/Dockerfile
> +RUN pip3 --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt
```suggestion
RUN pip3 --disable-pip-version-check --no-cache-dir install ruff -r /tmp/pip-tmp/requirements.txt
```

2023-07-25 17:27 UTC, cclauss commented on .devcontainer/Dockerfile
> +# RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && npm install -g <your-package-here>" 2>&1
```suggestion
# https://github.com/microsoft/vscode-dev-containers/blob/main/containers/python-3/README.md
ARG VARIANT=3.11-bookworm
FROM mcr.microsoft.com/vscode/devcontainers/python:${VARIANT}
COPY requirements.txt /tmp/pip-tmp/
RUN python3 -m pip install --upgrade pip \
  && python3 -m pip install --no-cache-dir install ruff -r /tmp/pip-tmp/requirements.txt
```

2023-07-25 17:35 UTC, cclauss requested changes

2023-07-25 17:35 UTC, cclauss commented on .devcontainer/devcontainer.json
> +			// Use -bullseye variants on local on arm64/Apple Silicon.
```suggestion
```

2023-07-25 17:35 UTC, cclauss commented on .devcontainer/devcontainer.json
> +			"NODE_VERSION": "lts/*"
```suggestion
```

2023-07-25 17:35 UTC, cclauss commented on .devcontainer/devcontainer.json
> +			]
In a **future** PR, it would be cool to add... https://github.com/astral-sh/ruff-vscode

2023-07-25 18:24 UTC, cclauss commented on .devcontainer/Dockerfile
> +RUN python3 -m pip install --upgrade pip \
🚫

2023-07-25 18:46 UTC, CaedenPH requested changes
As cclauss mentioned, we have a gitpod config file, and I don't see much value in adding devcontainer config files, primarily due to the fact that this is unlike other repositories, and that it is a group of standalone files that don't require much, if any config
This also only customises for a singular tool, vscode, excluding other text editors/IDE's
Even still, if this is decided to be merged, perhaps it would be ideal to add information on how to set up this container in the `CONTRIBUTING.md`

2023-07-25 19:05 UTC, HManiac74 commented
Some people might prefer a local development container, and VSCode is a very good IDE, and platform independent, so I thought this might be a good idea

2023-07-25 20:23 UTC, cclauss approved these changes
Let's see if this AND GitPod can cohabitate without nullifying each other.  Contributors can choose their favorite.

Let's reserve the right to revert this contribution if users protest or if it does not bring sufficient value.

@CaedenPH is correct that we need docs in CONTRIBUTING.md so @HManiac74 please create a follow-on PR that helps folks to get started.

2023-07-25 20:23 UTC, merged