Create is valid email address algorithm
TheAlgorithms/Python pull request #8907
Opened 2023-07-29 21:45 UTC by CaedenPH

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-07-31 07:05 UTC, madhavgaba commented on strings/is_valid_email_address.py
> +    ("i.like.underscores@but_its_not_allowed_in_this_part", False),
can you add for empty string?

2023-08-01 02:18 UTC, tianyizheng02 requested changes

2023-08-01 02:18 UTC, tianyizheng02 commented on strings/is_valid_email_address.py
> +    ):
```suggestion
    # (4.) Validate the placement of "." characters in the local-part
    if (
        local_part.startswith(".")
        or local_part.endswith(".")
        or ".." in local_part
    ):
```
No regex necessary

2023-08-01 02:18 UTC, tianyizheng02 commented on strings/is_valid_email_address.py
> +    if domain.startswith(".") or domain.endswith(".") or re.search(r"\.\.+", domain):
```suggestion
    # (7.) Validate the placement of "." characters in the domain
    if domain.startswith(".") or domain.endswith(".") or ".." in domain:
```
No regex necessary

2023-08-01 02:18 UTC, tianyizheng02 commented on strings/is_valid_email_address.py
> +    ...     assert is_valid_email_address(email) is valid
```suggestion
    ...     assert is_valid_email_address(email) == valid
```

2023-08-10 14:11 UTC, CaedenPH commented on strings/is_valid_email_address.py
> +    ("i.like.underscores@but_its_not_allowed_in_this_part", False),
Good idea!

2023-08-10 14:14 UTC, CaedenPH commented on strings/is_valid_email_address.py
> +    if domain.startswith(".") or domain.endswith(".") or re.search(r"\.\.+", domain):
Good point

2023-08-14 01:09 UTC, tianyizheng02 requested changes

2023-08-14 01:09 UTC, tianyizheng02 commented on strings/is_valid_email_address.py
> +        print(f"Email address {email} is {'not ' if is_valid else ''}valid")
```suggestion
        print(f"Email address {email} is {'not ' if not is_valid else ''}valid")
```
Typo?

2023-08-14 08:13 UTC, CaedenPH commented on strings/is_valid_email_address.py
> +        print(f"Email address {email} is {'not ' if is_valid else ''}valid")
Yep 😁

2023-08-14 08:28 UTC, tianyizheng02 approved these changes
LGTM

2023-08-14 08:28 UTC, merged