Kausthub kannan
TheAlgorithms/Python pull request #8962
Opened 2023-08-14 17:57 UTC by kausthub-kannan

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-08-15 22:44 UTC, tianyizheng02 requested changes
Just some minor formatting changes, but otherwise LGTM

2023-08-15 22:44 UTC, tianyizheng02 commented on neural_network/activation_functions/leaky_rectified_linear_unit.py
> +
Formatting
```suggestion
    >>> leaky_rectified_linear_unit(np.array([2.3, 0.6, -2, -3.8]), alpha=0.3)
    array([ 2.3 ,  0.6 , -0.6 , -1.14])

    >>> leaky_rectified_linear_unit(np.array([-9.2, -0.3, 0.45, -4.56]), alpha=0.067)
    array([-0.6164 , -0.0201 ,  0.45   , -0.30552])
```

2023-08-15 22:44 UTC, tianyizheng02 commented on neural_network/activation_functions/leaky_rectified_linear_unit.py
> +https://en.wikipedia.org/wiki/Rectifier_(neural_networks)#Leaky_ReLU
Minor grammar/spelling fixes
```suggestion
Leaky Rectified Linear Unit (Leaky ReLU)

Use Case: Leaky ReLU solves the issue of dead neurons, or the vanishing gradient problem.
Refer the below link for more information:
https://en.wikipedia.org/wiki/Rectifier_(neural_networks)#Leaky_ReLU
```

2023-08-16 19:23 UTC, kausthub-kannan commented
Thank you for correcting me. I have done the requested changes with a few improvements.

2023-08-17 01:22 UTC, tianyizheng02 approved these changes

2023-08-17 01:22 UTC, merged

2023-08-17 01:22 UTC, tianyizheng02 commented
Thanks for your contribution!