Rewrite of base85.py
TheAlgorithms/Python pull request #9069
Opened 2023-09-20 02:51 UTC by ChrisO345

### Describe your change:

See #8965 
See #6216 

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-09-23 09:15 UTC, rohan472000 commented
Now build will pass as #9078 is merged.

2023-09-24 05:33 UTC, tianyizheng02 requested changes

2023-09-24 05:33 UTC, tianyizheng02 commented on ciphers/base85.py
> +    return sum(char * 85**i for i, char in enumerate(digits[::-1]))
```suggestion
    return sum(char * 85**i for i, char in enumerate(reversed(digits)))
```

2023-09-24 05:33 UTC, tianyizheng02 commented on ciphers/base85.py
> +    binary_data = "".join([bin(ord(d))[2:].zfill(8) for d in data.decode("utf-8")])
Can we use a generator instead?
```suggestion
    binary_data = "".join(bin(ord(d))[2:].zfill(8) for d in data.decode("utf-8"))
```

2023-09-24 05:33 UTC, tianyizheng02 commented on ciphers/base85.py
> +    )
Why not just
```suggestion
    result = "".join(
        _base10_to_85(chunk)[::-1] for chunk in b85_chunks
    )
```

2023-09-24 05:33 UTC, tianyizheng02 commented on ciphers/base85.py
> +    results = [(bin(_base85_to_10(chunk))[2::].zfill(32)) for chunk in b85_segments]
```suggestion
    results = [bin(_base85_to_10(chunk))[2::].zfill(32) for chunk in b85_segments]
```

2023-09-24 05:33 UTC, tianyizheng02 commented on ciphers/base85.py
> +    offset = 0 if null_values % 5 != 0 else 1
```suggestion
    offset = int(null_values % 5 == 0)
```

2023-09-24 05:33 UTC, tianyizheng02 commented on ciphers/base85.py
> +    return bytes(result[: -null_values + offset], "utf-8")
```suggestion
    return bytes(result[: offset - null_values], "utf-8")
```

2023-09-24 06:10 UTC, ChrisO345 commented on ciphers/base85.py
> +    )
```suggestion
    result = "".join(_base10_to_85(chunk)[::-1] for chunk in b85_chunks)
```

2023-09-24 07:36 UTC, tianyizheng02 approved these changes

2023-09-24 07:36 UTC, merged