Changed knuth_morris_pratt to be consistent with str.find()
TheAlgorithms/Python pull request #9079
Opened 2023-09-23 09:59 UTC by Akashram28

### Describe your change:

function kmp() now returns the first occurrence of the pattern. If the pattern does not exist in the given text, it returns -1 

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-09-23 10:03 UTC, rohan472000 commented
Change bool return type to int.

2023-09-23 10:31 UTC, rohan472000 commented
In your PR description, you should tick whatever suits your PR but don't delete other checkboxes, also tick that checkbox for bug fixing or doc change which u deleted.

2023-09-23 10:33 UTC, rohan472000 requested changes

2023-09-23 10:33 UTC, rohan472000 commented on strings/knuth_morris_pratt.py
> +def kmp(pattern: str, text: str) -> int:
```suggestion
def knuth_morris_pratt(pattern: str, text: str) -> int:
```

2023-09-23 10:33 UTC, rohan472000 commented on strings/knuth_morris_pratt.py
> +def kmp(pattern: str, text: str) -> int:
As `kmp` is vague not understandable to others.

2023-09-23 10:54 UTC, rohan472000 commented
@cclauss , kindly review it.

2023-09-23 12:03 UTC, amirsoroush commented
Thanks. "doctests" are more desirable than print statements. While we're at it, let's write some tests instead.

2023-09-23 12:08 UTC, amirsoroush commented
Just to note, you can use some keywords in your commit message to link a pull request to an issue, that way if your PR is accepted, the linked issue gets closed automatically.

2023-09-23 12:29 UTC, rohan472000 approved these changes
LGTM

2023-09-23 13:58 UTC, cclauss commented
I added doctests that fail...
```
=================================== FAILURES ===================================
___________ [doctest] strings.knuth_morris_pratt.knuth_morris_pratt ____________
009     1) Preprocess pattern to identify any suffixes that are identical to prefixes
010 
011         This tells us where to continue from if we get a mismatch between a character
012         in our pattern and the text.
013 
014     2) Step through the text one character at a time and compare it to a character in
015         the pattern updating our location within the pattern if necessary
016 
017     >>> kmp = "knuth_morris_pratt"
018     >>> knuth_morris_pratt(kmp, "kn") == kmp.find("kn")
Expected:
    True
Got:
    False
```

2023-09-23 15:08 UTC, rohan472000 commented
> I added doctests that fail...
> 
> ```
> =================================== FAILURES ===================================
> ___________ [doctest] strings.knuth_morris_pratt.knuth_morris_pratt ____________
> 009     1) Preprocess pattern to identify any suffixes that are identical to prefixes
> 010 
> 011         This tells us where to continue from if we get a mismatch between a character
> 012         in our pattern and the text.
> 013 
> 014     2) Step through the text one character at a time and compare it to a character in
> 015         the pattern updating our location within the pattern if necessary
> 016 
> 017     >>> kmp = "knuth_morris_pratt"
> 018     >>> knuth_morris_pratt(kmp, "kn") == kmp.find("kn")
> Expected:
>     True
> Got:
>     False
> ```
> 
> As discussed in CONTRIBUTING.md, you can run these on your own computer with: `python3 -m doctest -v strings/knuth_morris_pratt.py`

I'm getting false too for that doctest.

2023-09-23 15:23 UTC, rohan472000 commented
![image](https://github.com/TheAlgorithms/Python/assets/96521078/83f936e6-28f2-45cc-937a-3c84c581b74b)
individually both are giving false, but why not true when doing `==`.

2023-09-23 15:40 UTC, rohan472000 commented
while testing the doctests added by @cclauss with existing code of `knuth_morris_pratt.py` in repo, it is also failing.

2023-09-23 15:58 UTC, Akashram28 commented
> ![image](https://user-images.githubusercontent.com/96521078/270116933-83f936e6-28f2-45cc-937a-3c84c581b74b.png) in
<img width="781" alt="knuth_morris_pratt" src="https://github.com/TheAlgorithms/Python/assets/68014251/2f0c10a7-dadb-403e-995d-d9806b1ee246">
dividually both are giving false, but why not true when doing `==`.

The pattern is the first parameter, the text is the second

2023-09-24 07:12 UTC, cclauss commented
If we are going to be consistant with [`str.find()`](https://docs.python.org/3/library/stdtypes.html#str.find) then we should change `knuth_morris_pratt(sub, text)` to `knuth_morris_pratt(text, sub)` to match the calling conventions and `knuth_morris_pratt(text, sub) == text.find(sub)` should always be True.

2023-09-30 05:23 UTC, closed without merging