New branch
TheAlgorithms/Python pull request #9087
Opened 2023-09-24 21:28 UTC by Muhammadummerr

I have made updates to the rat_in_maze.py file to enhance code clarity. 
These updates include:
1.Adding more descriptive comments to explain the logic and steps of the maze-solving algorithm. 
2.Introducing variables that allow for easy customization of the source and destination cells within the maze.

2023-09-25 02:11 UTC, rohan472000 commented
Kindly tick the checkboxes while raising PR, don't delete them.

2023-09-25 07:24 UTC, Muhammadummerr commented
> Kindly tick the checkboxes while raising PR, don't delete them.

Ok, but now how to tick checkboxes when PR is raised?

2023-09-25 07:26 UTC, rohan472000 commented
Replace `• [ ]` to `• [x]`

2023-09-25 07:29 UTC, Muhammadummerr commented
Sorry, but where?

2023-09-25 07:32 UTC, rohan472000 commented
While creating PR, you will get a box to describe the change, below in the box there are multiple checkboxes to tick.

2023-09-25 07:35 UTC, Muhammadummerr commented
should I delete this PR now, and create another one and tick checkboxes?

2023-09-25 07:37 UTC, rohan472000 commented
No...copy from that link which I provided, and paste it in description box above, then tick required checkboxes.

2023-09-25 07:38 UTC, rohan472000 commented
Also revise the PR title, don't include 9066, this should be in description box, see contributing guidelines beforehand.

2023-09-25 07:50 UTC, Muhammadummerr commented
Thanks a lot, your guidance meant a lot to me:)

2023-09-26 15:34 UTC, dlesnoff commented on backtracking/rat_in_maze.py
> +        The maze consists of walls (0s) and open paths (1s).
Notice that the solution path in the input goes through 0s that you (and the original author) depict as walls.
I would expect the solution to go through open paths.

```suggestion
        The maze consists of walls (1s) and open paths (0s).
```

2023-09-26 15:52 UTC, Muhammadummerr reviewed
thanks for the correction.

2023-09-27 13:09 UTC, dlesnoff commented
I am not familiar with the Python repository, but I think that you should reflect the changes in the unittest.
What happens if I change the starting cell and the end cell?
An example in the docstring with this new feature would be welcome too.

2023-09-29 01:59 UTC, rohan472000 requested changes

2023-09-29 01:59 UTC, rohan472000 commented on backtracking/rat_in_maze.py
> +            Return: True if the maze has a solution or False if it does not.
```suggestion
 True if the maze has a solution or False if it does not.
```

2023-09-29 01:59 UTC, rohan472000 commented on backtracking/rat_in_maze.py
> +    <<<<<<< HEAD
```suggestion
    HEAD :
```

2023-09-29 01:59 UTC, rohan472000 commented on backtracking/rat_in_maze.py
> +    >>>>>>> origin/new_branch
```suggestion
    Origin/new_branch :
```

2023-09-29 02:04 UTC, rohan472000 commented
At line 19, a lack of a blank line after >>>: '>>>>>>> origin/new_branch' is given in error but text '>>>>>>> origin/new_branch' doesn't appear to be related to the code or docstring.

I have suggested change, commit that and see if it resolves the issue or not.

2023-09-29 07:20 UTC, rohan472000 reviewed
`solve_maze` function should return the solved maze as its result instead of printing it directly.

Try to implement if that possible.

2023-09-29 08:04 UTC, Muhammadummerr commented
> `solve_maze` function should return the solved maze as its result instead of printing it directly.
> 
> Try to implement if that possible.

And if a path doesn't exist or incorrect coordinates for the source or destination are provided, it should print 'No solution exists' or 'Incorrect coordinates are given' and return None.Right?

2023-09-29 08:06 UTC, rohan472000 commented
`None` would be better.

2023-09-29 10:10 UTC, rohan472000 commented
Use `ruff .` then `ruff . --fix` to rectify ruff issues.

2023-09-29 10:16 UTC, Muhammadummerr commented
> Use `ruff .` then `ruff . --fix` to rectify ruff issues.

3 errors found ,then how should I resolve them without using ruff --fix . 
On running the file it showing error of whitespaces ====== ,How it can be resolved?

2023-09-29 10:18 UTC, rohan472000 commented
run : `ruff . --fix`

2023-09-29 10:22 UTC, Muhammadummerr commented
> run : `ruff . --fix`

still 3 errors found
Desktop\Python\backtracking\rat_in_maze.py:35:89: E501 Line too long (93 > 88 characters)
Desktop\Python\backtracking\rat_in_maze.py:82:89: E501 Line too long (93 > 88 characters)
Desktop\Python\backtracking\rat_in_maze.py:105:89: E501 Line too long (216 > 88 characters)

2023-09-29 10:48 UTC, Muhammadummerr commented
> run : `ruff . --fix`

using black . showing All done but ruff . --fix showing 3 erros found

2023-09-29 11:19 UTC, Muhammadummerr commented
I understand what the problem is. The output of solve_maze is a 2D array written in the docstring as [[0, 1, 1], [0, 0, 1], [0, 0, 1]], but it exceeds the 88-character word limit. Now, when I format the line, the expected output does not match the obtained output. Can you help me in how to approach this issue now?

2023-09-29 12:04 UTC, rohan472000 requested changes

2023-09-29 12:04 UTC, rohan472000 commented on backtracking/rat_in_maze.py
> +) -> bool:
```suggestion
) -> list[list[int]] or None:
```

2023-09-29 15:20 UTC, rohan472000 requested changes
Remove print statement as it is returning None.

2023-09-29 15:20 UTC, rohan472000 commented on backtracking/rat_in_maze.py
> +        print("Invalid source coordinates")
```suggestion
        
```

2023-09-29 15:20 UTC, rohan472000 commented on backtracking/rat_in_maze.py
> +        print("Invalid destination coordinates")
```suggestion
        
```

2023-09-29 15:20 UTC, rohan472000 commented on backtracking/rat_in_maze.py
>          print("No solution exists!")
```suggestion
        
```

2023-09-30 04:19 UTC, tianyizheng02 commented
Thank you for your contribution, but unfortunately we're not accepting new PRs at the moment. We're currently trying to clear our backlog of existing PRs in preparation for Hacktoberfest. If you want to contribute, please wait until after October 1 to do so. See [this discussion](https://github.com/TheAlgorithms/Python/discussions/8912#discussion-5458835) for more info.

2023-09-30 04:19 UTC, closed without merging

2023-10-01 09:46 UTC, dlesnoff commented
> At line 19, a lack of a blank line after >>>: '>>>>>>> origin/new_branch' is given in error but text '>>>>>>> origin/new_branch' doesn't appear to be related to the code or docstring.

> I have suggested change, commit that and see if it resolves the issue or not.

The '>>>>>>>' and '======' stuff comes from the git merge. When there is a conflict (a file being changed in the two original branches), `git` modify the file and let the two code versions in the same file separated by `<<<<<<<`, `==========` and `>>>>>>`. See [the Git documentation](https://git-scm.com/docs/git-merge#_how_conflicts_are_presented).

> @[Muhammadummerr](https://github.com/Muhammadummerr) Muhammadummerr deleted the new_branch branch

Why did you deleted the branch? It is a temporary closed PR.