Added minimum platforms required problem
TheAlgorithms/Python pull request #9120
Opened 2023-09-28 22:06 UTC by Siddharthrajrana

Fixes #9119

Added a new problem based on the **Greedy Algorithm**: **Minimum Platforms Required Problem**.

### Problem Description

Given arrival and departure times of all trains that reach a railway station. Find the minimum number of platforms required for the railway station so that no train is kept waiting.
Consider that all the trains arrive on the same day and leave on the same day. Arrival and departure time can never be the same for a train but we can have arrival time of one train equal to departure time of the other. At any given instance of time, same platform can not be used for both departure of a train and arrival of another train. In such cases, we need different platforms.

Input: n = 6 
arr[] = {0900, 0940, 0950, 1100, 1500, 1800}
dep[] = {0910, 1200, 1120, 1130, 1900, 2000}

Output: 3
Explanation: 
Minimum 3 platforms are required to 
safely arrive and depart all trains.

Reference: https://practice.geeksforgeeks.org/problems/minimum-platforms-1587115620/1

### Solution Approach

First we will sort both arrays. When there is sorted events, it will be easy to maintain 
the count of trains that have arrived but not departed. The total platforms needed at one 
time can be found by taking the difference between arrivals and departures at that time and 
the maximum value of all times will be the final answer.

### Checklist:

* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-09-29 06:51 UTC, rohan472000 commented
Use `ruff . --fix` to rectify ruff issues.

2023-09-29 12:00 UTC, rohan472000 requested changes

2023-09-29 12:00 UTC, rohan472000 commented on greedy_methods/minimum_platforms_required.py
> +    >>> minimum_platforms_required([900, 945, 955, 1100, 1500, 1800],
Add more edge and unique doctests.

2023-09-30 04:14 UTC, tianyizheng02 commented
Thank you for your contribution, but unfortunately we're not accepting new PRs at the moment. We're currently trying to clear our backlog of existing PRs in preparation for Hacktoberfest. If you want to contribute, please wait until after October 1 to open a new PR.

2023-09-30 04:14 UTC, closed without merging