Added solution for project euler problem 197
TheAlgorithms/Python pull request #9121
Opened 2023-09-28 22:58 UTC by hamzahasann

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-09-29 07:00 UTC, rohan472000 requested changes

2023-09-29 07:00 UTC, rohan472000 commented on project_euler/problem_197/sol1.py
> +def f(x: float) -> float:
Give descriptive name to the function.

2023-09-29 07:01 UTC, rohan472000 requested changes

2023-09-29 07:01 UTC, rohan472000 commented on project_euler/problem_197/sol1.py
> +    return round(u + f(u), 9)
`round` is creating issue as return type of this function is `float`.

2023-09-30 04:14 UTC, tianyizheng02 commented
Thank you for your contribution, but unfortunately we're not accepting new PRs at the moment. We're currently trying to clear our backlog of existing PRs in preparation for Hacktoberfest. If you want to contribute, please wait until after October 1 to open a new PR.

2023-09-30 04:14 UTC, closed without merging