Create polynomial_hash.py
TheAlgorithms/Python pull request #9160
Opened 2023-10-01 02:24 UTC by prasad-chavan1

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-10-27 16:54 UTC, tianyizheng02 requested changes
What is the hashing algorithm here?

2023-10-27 16:54 UTC, tianyizheng02 commented on hashes/polynomial_hash.py
> +# Output: 877483825
Please encapsulate all driver code in a `__main__` block.

2023-10-27 16:54 UTC, tianyizheng02 commented on hashes/polynomial_hash.py
> +Calculate the hash of a string using a polynomial rolling hash function.
If this is a polynomial rolling hash, then why not name the file and function `polynomial_rolling_hash`?

2024-09-30 09:10 UTC, cclauss commented
Closing require_type_hints PRs to prepare for Hacktoberfest 2024

2024-09-30 09:10 UTC, closed without merging