Updated Heap algorithm
TheAlgorithms/Python pull request #9316
Opened 2023-10-01 17:34 UTC by abhinavjha98

### Describe your change:

Refactored the Heap's algorithm to improve clarity and efficiency. Updated docstring to include doctests ensuring consistent whitespace and better documentation of function behavior.

- [ ] Add an algorithm?
- [x] Fix a bug or typo in an existing algorithm?
- [x] Documentation change?

### Checklist:
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Python files are placed inside an existing directory.
- [x] All filenames are in all lowercase characters with no spaces or dashes.
- [x] All functions and variable names follow Python naming conventions.
- [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
- [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
- [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
- [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-10-01 17:45 UTC, cclauss commented on divide_and_conquer/heaps_algorithm_iterative.py
> -    True
Removing tests is not a good idea.

2023-10-01 17:45 UTC, cclauss requested changes
Please do not remove tests.

2023-10-01 17:47 UTC, cclauss commented on divide_and_conquer/heaps_algorithm_iterative.py
> +    Pure python implementation of the Heap's algorithm (recursive version),
```suggestion
    Pure Python implementation of the Heap's algorithm (recursive version),
```

2023-10-01 18:10 UTC, cclauss commented
What are the advantages of the proposed changes?  Are they faster?  Can we prove that with a `timeit` benchmark.
* https://github.com/search?q=repo%253ATheAlgorithms%252FPython%20timeit
* https://docs.python.org/3/library/timeit.html

2023-10-02 05:49 UTC, abhinavjha98 commented
# Proposed Changes to Heap's Algorithm

## Advantages

### Simplification
The revised version introduces a more self-contained approach by passing the result list (`res`) directly to the recursive function. This decouples the function from outer-scope variables, enhancing its modularity and readability.

### Efficiency
Relocating the `len(arr) <= 1` check outside the recursive function ensures it's executed only once. This offers a performance boost, especially for longer input lists, by reducing unnecessary checks.

## `timeit` Benchmark Results

| Test List       | Original Algorithm (s) | Proposed Algorithm (s) |
|-----------------|------------------------|------------------------|
| `[1, 2, 3, 4]`  | 0.111138824            | 0.067861666            |

For the input list `[1, 2, 3, 4]`, the proposed algorithm is notably faster than the original, showcasing its better scalability with larger inputs.

## Conclusion

The proposed changes, while introducing enhanced code clarity, also offer improved performance for more extensive input lists, making a compelling case for this revision.

2023-10-02 06:16 UTC, cclauss reviewed
Nice progress...  Please do the following.
1. Put our tests back in place.
2. Create a `generate()` and a `generate_slow()` implementation.
3. Add the `timeit` test so that visitors can see why optimization matters.
4. Fix the `mypy` error: https://results.pre-commit.ci/run/github/63476337/1696182601.7cGNYtBUSy2tdmrH2FhuvQ

2024-09-30 09:31 UTC, cclauss commented
Closing tests_are_failing PRs to prepare for Hacktoberfest 2024.

2024-09-30 09:31 UTC, closed without merging