add median of two sorted array
TheAlgorithms/Python pull request #9386
Opened 2023-10-02 06:35 UTC by BamaCharanChhandogi

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-10-02 06:44 UTC, BamaCharanChhandogi commented
This is the first PR of the Median of two sorted arrays. 
@cclauss please check.

2023-10-02 07:05 UTC, cclauss requested changes
Under what circumstances would this algorithm be used?

2023-10-02 07:05 UTC, cclauss commented on data_structures/arrays/median_two_array.py
> +            return (float(middle1) + float(middle2)) / 2.0
```suggestion
        # Merge the arrays into a single sorted array.
        merged = sorted(nums1 + nums2)
        length = len(merged)
        if total % 2 == 1:  # If the total number of elements is odd
            return float(merged[total // 2])  # then return the middle element

        # If the total number of elements is even, calculate
        # the average of the two middle elements as the median.
        middle1 = merged[total // 2 - 1]
        middle2 = merged[total // 2]
        return (float(middle1) + float(middle2)) / 2.0
```

2023-10-02 07:05 UTC, cclauss commented on data_structures/arrays/median_two_array.py
> +        0.0
Please add tests:
```
>>> find_median_sorted_arrays([], [])
>>> find_median_sorted_arrays([], [1])
>>> find_median_sorted_arrays([-1_000], (1_000))
>>> find_median_sorted_arrays((-1.1, -2.2), [-3.3, -4.4])

2023-10-02 07:24 UTC, BamaCharanChhandogi commented on data_structures/arrays/median_two_array.py
> +    def find_median_sorted_arrays(self, nums1: list[int], nums2: list[int]) -> float:
done

2023-10-02 07:25 UTC, BamaCharanChhandogi commented on data_structures/arrays/median_two_array.py
> +            The median of the two sorted arrays.
done

2023-10-02 07:25 UTC, BamaCharanChhandogi commented on data_structures/arrays/median_two_array.py
> +            return (float(middle1) + float(middle2)) / 2.0
done

2023-10-02 07:25 UTC, BamaCharanChhandogi commented on data_structures/arrays/median_two_array.py
> +        0.0
done

2023-10-02 07:41 UTC, BamaCharanChhandogi commented
Thanks for the guidance.

2023-10-02 08:05 UTC, cclauss commented
https://github.com/TheAlgorithms/Python/pull/9386#pullrequestreview-1652185734

2023-10-02 08:12 UTC, BamaCharanChhandogi commented
I think I have resolved all.

2023-10-02 08:16 UTC, cclauss commented
https://github.com/TheAlgorithms/Python/pull/9386#pullrequestreview-1652185734

2023-10-02 08:34 UTC, BamaCharanChhandogi commented
You are saying I will add  the answer to Your question in docstring.
Right?

2023-10-02 12:10 UTC, BamaCharanChhandogi commented
@cclauss please check

2023-10-02 21:56 UTC, BamaCharanChhandogi commented
Hello @cclauss, Please tell me if anything needed.

2023-10-03 13:39 UTC, BamaCharanChhandogi commented
@cclauss please check

2023-10-04 17:39 UTC, BamaCharanChhandogi commented
@cclauss check please

2023-10-04 18:18 UTC, cclauss approved these changes

2023-10-04 18:18 UTC, merged