Power of 4
TheAlgorithms/Python pull request #9505
Opened 2023-10-02 16:57 UTC by siddwarr

### Describe your change:
Added the code for the leetcode problem 342
This is the most optimal solution using bit manipulation to check if a number is divisible by 4 or not

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-10-05 15:57 UTC, siddwarr commented on bit_manipulation/power_of_4.py
> +    TypeError: unsupported operand type(s) for &: 'float' and 'float'
Added the type check

2023-10-05 22:08 UTC, ChrisO345 requested changes

2023-10-05 22:08 UTC, ChrisO345 commented on bit_manipulation/power_of_4.py
> +    False
```suggestion
    False
    >>> power_of_4(64)
    True
```

2023-10-06 10:39 UTC, siddwarr commented on bit_manipulation/power_of_4.py
> +    False
added

2023-10-06 10:39 UTC, siddwarr commented
added power_of_4(64) testcase

2023-10-08 19:40 UTC, ChrisO345 approved these changes

2023-10-08 19:40 UTC, merged