Updated check_bipartite_graph_dfs.py
TheAlgorithms/Python pull request #9525
Opened 2023-10-02 18:57 UTC by debnath003

### Describe your change:

Updated the check_bipartite_graph_dfs.py in the graph folder which will reduce the time complexity. Furthermore I also included doctest module for testing some test cases included in the code.

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-10-02 19:15 UTC, debnath003 commented
@tianyizheng02 please merge my PR, awaiting your review

2023-10-03 04:51 UTC, debnath003 commented
@tianyizheng02 awaiting your review #9525

2023-10-03 06:51 UTC, debnath003 commented
@tianyizheng02 could you please approve my PR review #9525?  This is my first time contributing in this repository. Also please include hacktoberfest accepted label! Thanks again

2023-10-03 10:33 UTC, debnath003 commented
@tianyizheng02 please look after this PR #9525 and merge this PR for hacktoberfest

2023-10-04 17:33 UTC, debnath003 commented
@tianyizheng02 @cclauss please look after this PR #9525 and merge the PR, so that it can be eligible for hacktoberfest. Please also add hacktoberfest-accepted label. Thanks a lot!

2023-10-04 17:56 UTC, cclauss commented on graphs/check_bipartite_graph_dfs.py
> +        graph (DefaultDict[int, List[int]]): An adjacency list representing the graph.
Please do not repeat the datatypes which are already stated in the function signature and verified by mypy.  Readers become confused if one instance is changed and the other is not.  Please use the additional space to define what an adjacency list is.
```suggestion
        graph: An adjacency list representing the graph.
```

2023-10-04 17:58 UTC, cclauss commented on graphs/check_bipartite_graph_dfs.py
> +        bool: True if the graph is Bipartite, False otherwise.
```suggestion
        True if there is no edge that connects vertices of the same set, False otherwise.
```

2023-10-04 18:01 UTC, cclauss commented on graphs/check_bipartite_graph_dfs.py
> +    def dfs(node, color):
I do not love `dfs` -- too cryptic.

2023-10-04 18:04 UTC, cclauss requested changes

2023-10-04 18:04 UTC, cclauss commented on graphs/check_bipartite_graph_dfs.py
> +        return True
```suggestion
        return any(vis[nbor] == color or (vis[nbor] == -1 and not dfs(nbor, 1 - color)) for nbor in graph[node])
```

2023-10-04 18:12 UTC, cclauss commented
if you do `pipx install pre-commit` and the `pre-commit install` at the root of this repo's directory then `black` (code formatting) and `ruff` (linting) will run automatically on each `git commit`.

2023-10-04 18:15 UTC, debnath003 commented
> if you do `pipx install pre-commit` and the `pre-commit install` at the root of this repo's directory then `black` (code formatting) and `ruff` (linting) will run automatically on each `git commit`.

I have actually done that in vscode, but the change that you have given seemingly shows some format errors, which is alright; Apart from that is the code okay, as edited by the changes that you have suggested? @cclauss

2023-10-04 18:18 UTC, debnath003 commented
@cclauss looks like the code is having some error, in build, could you please point out the error?

2023-10-04 18:39 UTC, debnath003 commented
@cclauss idk what is the error, it should return correct code, but the doctest is getting failed, could you please check and suggest some change in the error part?

2023-10-04 19:35 UTC, debnath003 commented
@cclauss I have made the required changes, and the checks are also correct, could you please review that and merge the PR? It will be very helpful in hacktoberfest also if you add the hacktoberfest-accepted label

2023-10-05 14:46 UTC, debnath003 commented
@cclauss @tianyizheng02 please someone check the review and approve my PR! Awaiting for review!

2023-10-05 15:39 UTC, cclauss commented
This is complex code so let's use self-documenting function and variable names to help readers to understand.

We should not shorten names to simplify the code formatting but use understandable name and leave to code formatting to psf/black.

I am not sure if `nbor` was supposed to be `neighbour`.  ;-)

2023-10-05 15:45 UTC, debnath003 commented
All the checks have passed! @cclauss

2023-10-05 15:47 UTC, debnath003 commented
> This is complex code so let's use function and variable names that are self-documenting to help readers understand.
> 
> We should not shorten names to simplify the code formatting but use understandable names and leave the code formatting to psf/black.
> 
> I am unsure if `nbor` was supposed to be `neighbour`. ;-)

I actually did it intentionally, so that my formatting can be correct according to the ruff linter 😅 @cclauss

2023-10-05 17:31 UTC, cclauss commented
https://docs.astral.sh/ruff/faq/#is-ruff-compatible-with-black ;-) They both run in our `pre-commit`.
https://github.com/TheAlgorithms/Python/blob/87494f1fa1022368d154477bdc035fd01f9e4382/.pre-commit-config.yaml#L18-L26

2023-10-05 17:32 UTC, cclauss approved these changes
Nice work!!!

2023-10-05 17:33 UTC, merged

2023-10-05 17:33 UTC, debnath003 commented
> https://docs.astral.sh/ruff/faq/#is-ruff-compatible-with-black ;-) They both run in our `pre-commit`.
> 
> https://github.com/TheAlgorithms/Python/blob/87494f1fa1022368d154477bdc035fd01f9e4382/.pre-commit-config.yaml#L18-L26

I think I forgot it 😅

2023-10-05 17:33 UTC, debnath003 commented
> Nice work!!!

Please add hacktober-accepted label so that it can be accepted in hacktoberfest

2023-10-05 17:41 UTC, cclauss commented
Hacktoberfest knows this repo... They will accept this automatically but just in case...

2023-10-05 17:42 UTC, debnath003 commented
Thanks a lot @cclauss !