Stock Buy and Sell
TheAlgorithms/Python pull request #9601
Opened 2023-10-03 14:17 UTC by shivjaiswal-coder

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-10-04 23:20 UTC, ChrisO345 requested changes

2023-10-04 23:20 UTC, ChrisO345 commented on data_structures/arrays/buy_and_sell_stock.py
> +print("Maximum profit (Type 2):", max_profit_type2)
```suggestion
if __name__ == "__main__":
    prices_type = [7, 1, 5, 3, 6, 4]
    # Example usage for Type 1: Single day to buy one stock and a different day in the future to sell that stock
    trader_type1 = StockBuySell(prices_type)
    max_profit_type1 = trader_type1.max_profit_type1()
    print("Maximum profit (Type 1):", max_profit_type1)

    # Example usage for Type 2: Hold at most one share of the stock at any time
    trader_type2 = StockBuySell(prices_type)
    max_profit_type2 = trader_type2.max_profit_type2()
    print("Maximum profit (Type 2):", max_profit_type2)
```

2023-10-04 23:20 UTC, ChrisO345 commented on data_structures/arrays/buy_and_sell_stock.py
> +class StockBuySell:
There is no need for this to be in a class.

2024-09-30 09:09 UTC, cclauss commented
Closing require_type_hints PRs to prepare for Hacktoberfest 2024

2024-09-30 09:09 UTC, closed without merging