Refined Bitmark
TheAlgorithms/Python pull request #9699
Opened 2023-10-04 13:10 UTC by imSanko

### Describe your change:

Refined Bitmark

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #9698".

2023-10-04 13:17 UTC, imSanko commented
@cclauss Can you take a look I've just added a few stuff

2023-10-04 14:58 UTC, cclauss commented on dynamic_programming/bitmask.py
> +    def __init__(self, task_performed, total_tasks):
No type hint, no doctests?

2023-10-05 03:50 UTC, imSanko commented
@cclauss can you have a glance and let me know

2023-10-05 04:48 UTC, cclauss requested changes

2023-10-05 04:48 UTC, cclauss commented on dynamic_programming/bitmask.py
> +    def __init__(self, task_performed, total_tasks):
This is not resolved.  Please read CONTRIBUTING.md.  Functions need type hints and doctests.

2023-10-05 09:18 UTC, cclauss commented
To fix the `pre-commit errors` go to https://github.com/imSanko/Python and click the `Sync fork` and then `Update branch` buttons.

2023-10-05 09:25 UTC, cclauss commented on dynamic_programming/bitmask.py
> +    def __init__(self, task_performed, total_tasks):
```suggestion
    def __init__(self, task_performed: list[list[int]], total_tasks: int) -> None:
```

2023-10-05 15:06 UTC, imSanko reviewed
from collections import defaultdict
from typing import List, Dict

class TaskAssignment:
    def __init__(self, task_performed: List[List[int]], total_tasks: int) -> None:
        """
        Initialize the TaskAssignment class.

        Parameters:
        task_performed (List[List[int]]): List of lists where each inner list represents
            the tasks that can be performed by a person.
        total_tasks (int): The total number of tasks to be assigned.
        """
        self.total_tasks = total_tasks
        self.dp = [[-1 for _ in range(total_tasks + 1)] for _ in range(1 << len(task_performed))]
        self.task: Dict[int, List[int]] = defaultdict(list)
        self.final_mask: int = (1 << len(task_performed)) - 1

    def count_ways_until(self, mask: int, task_no: int) -> int:
        """
        Recursively count the number of ways to assign tasks to people.

        Parameters:
        mask (int): Bitmask representing the tasks assigned to people.
        task_no (int): The current task number being considered.

        Returns:
        int: The number of ways to assign tasks.

        Doctest:
        >>> assignment = TaskAssignment([[1, 2], [2, 3]], 3)
        >>> assignment.count_ways_until(0, 1)
        4
        """
        if mask == self.final_mask:
            return 1
        if task_no > self.total_tasks:
            return 0
        if self.dp[mask][task_no] != -1:
            return self.dp[mask][task_no]

        total_ways_util: int = self.count_ways_until(mask, task_no + 1)

        if task_no in self.task:
            for person in self.task[task_no]:
                if mask & (1 << person):
                    continue
                total_ways_util += self.count_ways_until(mask | (1 << person), task_no + 1)

        self.dp[mask][task_no] = total_ways_util
        return self.dp[mask][task_no]

    def count_total_ways(self, task_performed: List[List[int]]) -> int:
        """
        Count the total number of ways to distribute tasks to people.

        Parameters:
        task_performed (List[List[int]]): List of lists where each inner list represents
            the tasks that can be performed by a person.

        Returns:
        int: The total number of ways to distribute tasks.

        Doctest:
        >>> assignment = TaskAssignment([[1, 2], [2, 3]], 3)
        >>> assignment.count_total_ways([[1], [2], [3]])
        2
        """
        for person, tasks in enumerate(task_performed):
            for task in tasks:
                self.task[task].append(person)

        return self.count_ways_until(0, 1)

if __name__ == "__main__":
    total_tasks = 5
    task_performed = [[1, 3, 4], [1, 2, 5], [3, 4]]
    
    assignment = TaskAssignment(task_performed, total_tasks)
    total_ways = assignment.count_total_ways(task_performed)
    
    print("Total number of ways to distribute tasks:", total_ways)

2023-10-05 15:06 UTC, imSanko commented on dynamic_programming/tempCodeRunnerFile.py
> +    def count_ways_until(self, mask: int, task_no: int) -> int:
from collections import defaultdict
from typing import List, Dict

class TaskAssignment:
    def __init__(self, task_performed: List[List[int]], total_tasks: int) -> None:
        """
        Initialize the TaskAssignment class.

        Parameters:
        task_performed (List[List[int]]): List of lists where each inner list represents
            the tasks that can be performed by a person.
        total_tasks (int): The total number of tasks to be assigned.
        """
        self.total_tasks = total_tasks
        self.dp = [[-1 for _ in range(total_tasks + 1)] for _ in range(1 << len(task_performed))]
        self.task: Dict[int, List[int]] = defaultdict(list)
        self.final_mask: int = (1 << len(task_performed)) - 1

    def count_ways_until(self, mask: int, task_no: int) -> int:
        """
        Recursively count the number of ways to assign tasks to people.

        Parameters:
        mask (int): Bitmask representing the tasks assigned to people.
        task_no (int): The current task number being considered.

        Returns:
        int: The number of ways to assign tasks.

        Doctest:
        >>> assignment = TaskAssignment([[1, 2], [2, 3]], 3)
        >>> assignment.count_ways_until(0, 1)
        4
        """
        if mask == self.final_mask:
            return 1
        if task_no > self.total_tasks:
            return 0
        if self.dp[mask][task_no] != -1:
            return self.dp[mask][task_no]

        total_ways_util: int = self.count_ways_until(mask, task_no + 1)

        if task_no in self.task:
            for person in self.task[task_no]:
                if mask & (1 << person):
                    continue
                total_ways_util += self.count_ways_until(mask | (1 << person), task_no + 1)

        self.dp[mask][task_no] = total_ways_util
        return self.dp[mask][task_no]

    def count_total_ways(self, task_performed: List[List[int]]) -> int:
        """
        Count the total number of ways to distribute tasks to people.

        Parameters:
        task_performed (List[List[int]]): List of lists where each inner list represents
            the tasks that can be performed by a person.

        Returns:
        int: The total number of ways to distribute tasks.

        Doctest:
        >>> assignment = TaskAssignment([[1, 2], [2, 3]], 3)
        >>> assignment.count_total_ways([[1], [2], [3]])
        2
        """
        for person, tasks in enumerate(task_performed):
            for task in tasks:
                self.task[task].append(person)

        return self.count_ways_until(0, 1)

if __name__ == "__main__":
    total_tasks = 5
    task_performed = [[1, 3, 4], [1, 2, 5], [3, 4]]
    
    assignment = TaskAssignment(task_performed, total_tasks)
    total_ways = assignment.count_total_ways(task_performed)
    
    print("Total number of ways to distribute tasks:", total_ways)

2023-10-05 15:06 UTC, closed without merging

2023-10-05 15:06 UTC, cclauss commented on dynamic_programming/bitmask.py
> +from typing import List, Dict
These are not needed in Python 3.12 (or with `from __future__ import annotations`), just use `list` and `dict`.

2023-10-05 15:07 UTC, cclauss commented on dynamic_programming/bitmask.py
> +    def __init__(self, task_performed: List[List[int]], total_tasks: int) -> None:
```suggestion
    def __init__(self, task_performed: list[list[int]], total_tasks: int) -> None:
```

2023-10-05 15:08 UTC, cclauss commented on dynamic_programming/bitmask.py
> +        task_performed (List[List[int]]): List of lists where each inner list represents
Please do not repeat the datatypes that are stated above and checked by mypy.  Readers get confused if one changes and the other does not.
```suggestion
        task_performed: List of lists where each inner list represents
```