Created folder for losses in Machine_Learning
TheAlgorithms/Python pull request #9969
Opened 2023-10-07 04:10 UTC by THEGAMECHANGER416

### Describe your change:
Added a directory named `losses` in `machine_learning` that contains two loss functions namely `binary_cross_entropy.py` and `mean_squared_error.py`

* [x] Add an algorithm?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-10-07 05:44 UTC, THEGAMECHANGER416 commented
@darkstar Can you please approve this P.R for hacktoberfest ?
P.S. Sorry for all the messages, the code now runs perfectly and passes all tests. 
Thanks

2023-10-07 07:04 UTC, cclauss commented on machine_learning/losses/binary_cross_entropy.py
> +    return bce_loss
```suggestion
    return np.mean(bce_loss)
```
https://docs.astral.sh/ruff/rules/unnecessary-assign/

2023-10-07 07:05 UTC, cclauss commented on machine_learning/losses/mean_squared_error.py
> +    return mse
https://docs.astral.sh/ruff/rules/unnecessary-assign/

2023-10-07 07:06 UTC, cclauss commented on machine_learning/losses/mean_squared_error.py
> +    >>> mse
```suggestion
    >>> mean_squared_error(true_values, predicted_values)
```

2023-10-07 07:07 UTC, cclauss commented on machine_learning/losses/binary_cross_entropy.py
> +    >>> bce_loss
```suggestion
    >>> binary_cross_entropy(true_labels, predicted_probs)
```

2023-10-07 09:33 UTC, tianyizheng02 requested changes
Could we also name the directory `loss_functions` rather than `losses`? I feel that it's more accurate.

2023-10-07 09:33 UTC, tianyizheng02 commented on machine_learning/losses/mean_squared_error.py
> +    return np.mean(squared_errors)
```suggestion
    squared_errors = (y_true - y_pred) ** 2
    return np.mean(squared_errors)
```
You can just use Python operators on numpy ndarrays

2023-10-07 09:33 UTC, tianyizheng02 commented on machine_learning/losses/mean_squared_error.py
> +import numpy as np
Please include an explanation of MSE (along with a link to a source as well as the formula) in a header docstring

2023-10-07 09:33 UTC, tianyizheng02 commented on machine_learning/losses/binary_cross_entropy.py
> +import numpy as np
Please include an explanation of BSE (along with a link to a source as well as the formula) in a header docstring

2023-10-07 10:31 UTC, THEGAMECHANGER416 commented
@tianyizheng02 Done all the requested changes
Thanks

2023-10-07 16:24 UTC, tianyizheng02 requested changes

2023-10-07 16:24 UTC, tianyizheng02 commented on machine_learning/loss_functions/mean_squared_error.py
> +        raise ValueError("Input arrays must have the same length.")
Can we have a doctest that tests this case?

2023-10-07 16:24 UTC, tianyizheng02 commented on machine_learning/loss_functions/binary_cross_entropy.py
> +    # Clip predicted probabilities to avoid log(0) and log(1)
Can we have an ndarray length check like in `mean_squared_error.py`? And a doctest for that case as well

2023-10-08 07:55 UTC, THEGAMECHANGER416 commented
@tianyizheng02  Did all the requested changes. Hope you'll merge this now.
Thanks

2023-10-08 16:04 UTC, tianyizheng02 approved these changes
Thanks for your contribution!

2023-10-08 16:04 UTC, merged