Updated test cases of power_sum.py
TheAlgorithms/Python pull request #9978
Opened 2023-10-07 05:37 UTC by Muhammadummerr

### Describe your change:

I reduced the test cases, so it will run faster than before

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

2023-10-07 05:58 UTC, Muhammadummerr commented
The issue remains unresolved.

2023-10-07 07:38 UTC, Muhammadummerr commented
power_sum.py has been removed from that list :)

2023-10-09 02:20 UTC, Muhammadummerr commented
@cclauss

2023-10-10 04:10 UTC, tianyizheng02 requested changes
Could you also modify the code to use the `**` operator instead of the `pow` function from `math`?

2023-10-10 04:10 UTC, tianyizheng02 commented on backtracking/power_sum.py
> +    # print(backtrack(80, 1, 1, 0, 0))
Do you plan to keep this line of code?

2023-10-10 04:18 UTC, tianyizheng02 commented
Also, please put the issue number in your PR's description:
> - [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

This way, GitHub can automatically link your PR to the original issue. However, don't use the word "fixes", because your PR doesn't completely fix the issue on its own.

2023-10-10 06:11 UTC, cclauss commented
On your computer, please run:
`time python3 -m doctest backtracking/power_sum.py`
on both the new code and the old code so we know how much faster the new code is.

2023-10-13 04:41 UTC, Muhammadummerr commented
**OLD CODE**
TotalSeconds      : 2.757677
TotalMilliseconds : 2757.677

**NEW CODE**
TotalSeconds      : 1.067801
TotalMilliseconds : 1067.801

2023-10-14 08:24 UTC, tianyizheng02 approved these changes

2023-10-14 08:25 UTC, tianyizheng02 approved these changes

2023-10-14 08:25 UTC, tianyizheng02 commented on backtracking/power_sum.py
> +    i_to_n = int(current_number**power)
```suggestion
    i_to_n = current_number ** power
```
Removing unnecessary `int` cast (the variables are already ints)

2023-10-14 08:27 UTC, tianyizheng02 commented
Contributes to #9718

2023-10-14 08:31 UTC, merged